//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSMutableCopying.h"

@class CPTColor, NSDictionary, NSString;

@interface CPTTextStyle : NSObject <NSCoding, NSCopying, NSMutableCopying>
{
    float fontSize;
    NSString *fontName;
    CPTColor *color;
    int textAlignment;
    int lineBreakMode;
}

+ (id)textStyleWithStyle:(id)arg1;
+ (id)textStyle;
+ (id)textStyleWithAttributes:(id)arg1;
@property(nonatomic) int lineBreakMode; // @synthesize lineBreakMode;
@property(nonatomic) int textAlignment; // @synthesize textAlignment;
@property(copy, nonatomic) CPTColor *color; // @synthesize color;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName;
@property(nonatomic) float fontSize; // @synthesize fontSize;
- (void).cxx_destruct;
- (id)debugQuickLookObject;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
@property(readonly, nonatomic) NSDictionary *attributes; // @dynamic attributes;

@end

