//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WKNavigationDelegate.h"

@class NSMutableArray, NSString, WKProcessPool, WKWebView;

@interface FBWKCookieInjector : NSObject <WKNavigationDelegate>
{
    WKWebView *_dummyWKWebView;
    CDUnknownBlockType _completionBlock;
    WKProcessPool *_wkProcessPool;
    FBWKCookieInjector *_self;
    NSMutableArray *_hosts;
    id <FBWebViewAnalytics> _analytics;
}

+ (void)_logCookieInjectedIntoNSHTTPCookieStorage:(id)arg1 host:(id)arg2 analytics:(id)arg3;
+ (void)_logCookieInjectedIntoWKProcessPoolCookies:(id)arg1 oldCookieNames:(id)arg2 analytics:(id)arg3;
+ (BOOL)_URLHost:(id)arg1 matchesHost:(id)arg2;
+ (BOOL)_isValidCookieFragment:(id)arg1;
+ (id)_hosts;
+ (void)injectFBCookiesIntoNSHTTPCookieStorageFromWKNavigationResponse:(id)arg1 analytics:(id)arg2;
+ (void)injectFBCookiesFromNSHTTPCookieStorageIntoWKProcessPool:(id)arg1 analytics:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) id <FBWebViewAnalytics> analytics; // @synthesize analytics=_analytics;
- (void).cxx_destruct;
- (void)_injectForPendingHosts;
- (void)_injectFBCookiesFromNSHTTPCookieStorageIntoWKProcessPool:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

