//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGAlbumCameraViewControllerDelegate.h"
#import "IGAlbumFullscreenViewControllerDelegate.h"
#import "IGAlbumTitleViewControllerDelegate.h"

@class IGAlbumCameraViewController, IGAlbumCreationViewModel, IGAlbumFullscreenViewController, NSString;

@interface IGAlbumCreationViewController : UIViewController <IGAlbumCameraViewControllerDelegate, IGAlbumFullscreenViewControllerDelegate, IGAlbumTitleViewControllerDelegate>
{
    id <IGAlbumCreationViewControllerDataDelegate> _dataDelegate;
    id <IGAlbumCreationViewControllerNavigationDelegate> _navigationDelegate;
    unsigned int _viewMode;
    IGAlbumCreationViewModel *_viewModel;
    id <UIViewControllerTransitioningDelegate> _albumTitleTransitionDelegate;
    IGAlbumFullscreenViewController *_fullscreenController;
    IGAlbumCameraViewController *_cameraViewController;
}

@property(readonly, nonatomic) IGAlbumCameraViewController *cameraViewController; // @synthesize cameraViewController=_cameraViewController;
@property(retain, nonatomic) IGAlbumFullscreenViewController *fullscreenController; // @synthesize fullscreenController=_fullscreenController;
@property(retain, nonatomic) id <UIViewControllerTransitioningDelegate> albumTitleTransitionDelegate; // @synthesize albumTitleTransitionDelegate=_albumTitleTransitionDelegate;
@property(retain, nonatomic) IGAlbumCreationViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) unsigned int viewMode; // @synthesize viewMode=_viewMode;
@property(nonatomic) __weak id <IGAlbumCreationViewControllerNavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
@property(nonatomic) __weak id <IGAlbumCreationViewControllerDataDelegate> dataDelegate; // @synthesize dataDelegate=_dataDelegate;
- (void).cxx_destruct;
- (void)currentAlbumUpdated:(id)arg1;
- (void)albumTitleViewController:(id)arg1 didFinishWithTitle:(id)arg2;
- (void)albumFullscreenViewControllerDidTapCameraButton:(id)arg1;
- (void)albumFullscreenViewControllerShouldDismiss:(id)arg1;
- (void)albumCameraViewController:(id)arg1 didTapDisabledAsset:(id)arg2;
- (void)albumCameraViewControllerDidTapRetake:(id)arg1;
- (void)albumCameraViewControllerDidTapCurrentAlbumButton:(id)arg1;
- (void)albumCameraViewControllerDidTapTitle:(id)arg1;
- (void)albumCameraViewControllerDidTapAddPeople:(id)arg1;
- (void)albumCameraViewController:(id)arg1 didPickAsset:(id)arg2;
- (void)albumCameraViewControllerDidDismiss:(id)arg1;
- (void)albumCameraViewController:(id)arg1 didEnterState:(int)arg2;
- (void)dismiss;
- (void)switchChildViewControllersFromController:(id)arg1 toController:(id)arg2;
- (void)initFullscreenController;
- (void)setupViewMode;
- (BOOL)prefersStatusBarHidden;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

