//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGImageView;

@interface IGAlbumTabBarEntryCellImageView : UIView
{
    IGImageView *_imageView;
}

@property(retain, nonatomic) IGImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)sizeToFit;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithPhoto:(id)arg1;

@end

