//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserSession, NSMutableSet;

@interface IGAuthHelper : NSObject
{
    BOOL _isForcingOut;
    IGUserSession *_currentUserSession;
    unsigned int _lastAccountSwitchEntryPoint;
    NSMutableSet *_authUserData;
}

+ (void)doLocalLogoutStepsAffectingAllUsers;
+ (void)doLocalLogoutStepsSpecificToUser:(id)arg1;
+ (id)userSessionCookiesPredicate;
+ (void)migrateOldCurrentUser;
+ (id)authenticatedUserFromUser:(id)arg1;
+ (id)currentUser;
+ (id)sharedAuthHelper;
@property(nonatomic) BOOL isForcingOut; // @synthesize isForcingOut=_isForcingOut;
@property(retain, nonatomic) NSMutableSet *authUserData; // @synthesize authUserData=_authUserData;
@property(nonatomic) unsigned int lastAccountSwitchEntryPoint; // @synthesize lastAccountSwitchEntryPoint=_lastAccountSwitchEntryPoint;
@property(retain, nonatomic) IGUserSession *currentUserSession; // @synthesize currentUserSession=_currentUserSession;
- (void).cxx_destruct;
- (void)syncWithIGCookieStorageForUserWithPK:(id)arg1;
- (void)swapFromCookiesOfUserWithPk:(id)arg1 toCookiesOfUserWithPk:(id)arg2;
- (BOOL)cookiesAreValidForUserID:(id)arg1;
- (BOOL)currentUserIsLoggedIn;
- (void)onProfilePictureFailed:(id)arg1;
- (void)onProfilePictureChanged:(id)arg1;
- (void)removeProfilePicture;
- (void)uploadProfilePicture:(id)arg1 fromOption:(int)arg2;
- (id)profilePictureDataFromImage:(id)arg1;
- (void)sendServerLogoutRequestForUserWithPK:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)logOutAllUsersWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)logOutUser:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)handleLoginRequiredByServer;
- (void)clearAllUsers;
- (void)clearCurrentUser;
- (void)saveCookiesForInternalUsers;
- (void)handleLoginError;
- (void)logInWithUserDictionary:(id)arg1 facebookAccessToken:(id)arg2 authLogInType:(int)arg3;
- (void)logInWithDictionary:(id)arg1 facebookAccessToken:(id)arg2 authLogInType:(int)arg3;
- (void)logInWithAuthenticatedUser:(id)arg1 facebookAccessToken:(id)arg2 authLogInType:(int)arg3;
- (void)switchToAuthenticatedUserWithForce:(id)arg1 authLogInType:(int)arg2 defaultSelectedTab:(int)arg3 entryPoint:(unsigned int)arg4;
- (void)switchToNilUserWithEntryPoint:(unsigned int)arg1;
- (void)switchToLastAccessedUserWithForceDueToAddUserCancel;
- (void)switchToLastAccessedUserWithForceDueToCurrentUserLogoutWithEntryPoint:(unsigned int)arg1;
- (void)switchToAuthenticatedUser:(id)arg1 defaultSelectedTab:(int)arg2 entryPoint:(unsigned int)arg3;
- (void)synchronizeUserWithKeychain:(id)arg1;
- (BOOL)hasMultipleAccounts;
- (BOOL)hasMaximumNumberOfAccounts;
- (id)currentAuthenticatedUsersSortedByAccessTime;
- (id)currentAuthenticatedUsers;
- (id)authenticatedUserMatchingUserPK:(id)arg1;
- (void)archive;
- (void)updateCurrentUser:(id)arg1;
- (void)updateCurrentUserWithDictForCurrentUser:(id)arg1;
- (void)storeLastUserPK:(id)arg1;
- (id)lastUserPK;
- (void)removeOldUserData;
- (id)oldCurrentUser;
- (void)removeOldStoredUsersData;
- (id)oldStoredUsers;
- (void)storeAuthUserData:(id)arg1;
- (id)storedAuthUserData;
- (void)unarchiveUsers;
- (void)setCurrentUser:(id)arg1;
- (void)restoreCurrentUser;
- (id)init;
- (void)getProfanityFilterSetting:(CDUnknownBlockType)arg1 failureHandler:(CDUnknownBlockType)arg2;
- (void)changeProfanityFilterSetting:(BOOL)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)changePrivacySetting:(BOOL)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)renewBackupCodesWithSuccessHandler:(CDUnknownBlockType)arg1 failureHandler:(CDUnknownBlockType)arg2;
- (void)disableTwoFactorWithSuccessHandler:(CDUnknownBlockType)arg1 failureHandler:(CDUnknownBlockType)arg2;
- (void)sendTwoFactorSMSToPhoneNumber:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)accountSecurityInfoWithSuccessHandler:(CDUnknownBlockType)arg1 failureHandler:(CDUnknownBlockType)arg2;
- (void)robocallTwoFactorLoginForUser:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)resendTwoFactorLoginSMSForUser:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)requestSupportForSupportType:(unsigned int)arg1 user:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
- (void)assistedAccountRecoveryAction:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)verifySignUpSMSCodeWithPhoneNumber:(id)arg1 validationCode:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
- (void)requestSignUpSMSCodeWithPhoneNumber:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)verifyAccountRecoveryEmailConfirmationCodeWithEmail:(id)arg1 confirmationCode:(id)arg2 successHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
- (void)resendAccountRecoveryEmailConfirmationCodeWithEmail:(id)arg1 successHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (void)fetchSuggestedUsernamesWithEmail:(id)arg1 fullName:(id)arg2 successfulHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
- (void)uploadProfilePicture:(id)arg1 successfulHandler:(CDUnknownBlockType)arg2 failureHandler:(CDUnknownBlockType)arg3;
- (id)phoneRegistrationWithSignUpInfoDict:(id)arg1 profileInfo:(id)arg2 successfulHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;
- (id)submitSignUpRequestWithInfo:(id)arg1 profileInfo:(id)arg2 successfulHandler:(CDUnknownBlockType)arg3 failureHandler:(CDUnknownBlockType)arg4;

@end

