//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGAudioNUXController;

@protocol IGAudioNUXControllerDelegate <NSObject>
- (BOOL)audioNUXControllerIsVideoPlaying:(IGAudioNUXController *)arg1;
- (BOOL)audioNUXControllerIsPlayingSound:(IGAudioNUXController *)arg1;
- (BOOL)audioNUXControllerVideoHasSound:(IGAudioNUXController *)arg1;
@end

