//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGAYMFUserCell;

@protocol IGAYMFUserCellDelegate <NSObject>
- (void)didTapAYMFUserCell:(IGAYMFUserCell *)arg1;
- (void)didFollowAYMFUserCell:(IGAYMFUserCell *)arg1;
- (void)didDismissAYMFUserCell:(IGAYMFUserCell *)arg1;
@end

