//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

@class IGGroupedTableViewFooterView, NSArray;

@interface IGBackupCodesViewController : IGGroupedTableViewController
{
    BOOL _showBackupCodeAlert;
    BOOL _submitting;
    NSArray *_backupCodes;
    IGGroupedTableViewFooterView *_backupCodeFooterView;
    IGGroupedTableViewFooterView *_actionsFooterView;
}

@property(nonatomic) BOOL submitting; // @synthesize submitting=_submitting;
@property(nonatomic) BOOL showBackupCodeAlert; // @synthesize showBackupCodeAlert=_showBackupCodeAlert;
@property(retain, nonatomic) IGGroupedTableViewFooterView *actionsFooterView; // @synthesize actionsFooterView=_actionsFooterView;
@property(retain, nonatomic) IGGroupedTableViewFooterView *backupCodeFooterView; // @synthesize backupCodeFooterView=_backupCodeFooterView;
@property(retain, nonatomic) NSArray *backupCodes; // @synthesize backupCodes=_backupCodes;
- (void).cxx_destruct;
- (void)updateTableViewAfterFetch;
- (void)dataFetchFailedWithError:(id)arg1;
- (void)dataFetchedWithResponse:(id)arg1;
- (void)fetchNewBackupCodes;
- (void)selectedBackupCodeActionRow:(int)arg1;
- (void)selectedBackupCodeRow:(int)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (void)configureActionCell:(id)arg1 forRow:(int)arg2;
- (void)configureBackupCodeCell:(id)arg1 forRow:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)saveImageToLibrary:(id)arg1;
- (void)backupCodesScreenshot;
- (void)copyBackupCodesToClipboard;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithBackupCodes:(id)arg1 showBackupCodeAlert:(BOOL)arg2;

@end

