//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"

@class IGNonCurrentUserDefaults, NSArray, NSMutableOrderedSet, NSString;

@interface IGBlendedSearchRecentItemsOrderStore : NSObject <IGUserSessionClearableObject>
{
    BOOL _needsToBeArchived;
    NSMutableOrderedSet *_mutableRecentItems;
    NSString *_userSessionPK;
    IGNonCurrentUserDefaults *_sessionUserDefaults;
    NSArray *_itemControllers;
}

+ (void)clearForUserPK:(id)arg1;
@property(nonatomic) BOOL needsToBeArchived; // @synthesize needsToBeArchived=_needsToBeArchived;
@property(readonly, nonatomic) NSArray *itemControllers; // @synthesize itemControllers=_itemControllers;
@property(retain, nonatomic) IGNonCurrentUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
@property(retain, nonatomic) NSString *userSessionPK; // @synthesize userSessionPK=_userSessionPK;
- (void).cxx_destruct;
- (void)willLogOut;
- (void)willSwitchUsers;
- (void)archiveIfNeeded;
- (void)saveRecentItems:(id)arg1;
- (id)itemControllerForItem:(id)arg1;
- (id)restoreRecentItems;
- (id)itemControllerForItemType:(id)arg1;
- (void)clearHistory;
- (id)recentItems;
@property(readonly, nonatomic) NSMutableOrderedSet *mutableRecentItems; // @synthesize mutableRecentItems=_mutableRecentItems;
- (void)addRecentItem:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (void)dealloc;
- (id)initWithUserSessionPK:(id)arg1 sessionUserDefaults:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

