//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

#import "IGBusinessConversionFlowStep.h"
#import "IGGraphQLParsing.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class FBSDKAccessToken, IGBusinessConversionLoggingHelper, IGFacebookPageInfo, NSArray, NSString, UIView;

@interface IGBusinessConversionPageSelectionViewController : IGGroupedTableViewController <IGGraphQLParsing, UITableViewDataSource, UITableViewDelegate, IGBusinessConversionFlowStep>
{
    BOOL _isFetchingPages;
    id <IGBusinessConversionViewControllerDelegate> _delegate;
    FBSDKAccessToken *_accessToken;
    NSArray *_pageInfoObjects;
    UIView *_headerView;
    IGFacebookPageInfo *_selectedPageInfo;
    IGBusinessConversionLoggingHelper *_loggingHelper;
}

@property(retain, nonatomic) IGBusinessConversionLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(nonatomic) BOOL isFetchingPages; // @synthesize isFetchingPages=_isFetchingPages;
@property(retain, nonatomic) IGFacebookPageInfo *selectedPageInfo; // @synthesize selectedPageInfo=_selectedPageInfo;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSArray *pageInfoObjects; // @synthesize pageInfoObjects=_pageInfoObjects;
@property(retain, nonatomic) FBSDKAccessToken *accessToken; // @synthesize accessToken=_accessToken;
@property(nonatomic) __weak id <IGBusinessConversionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)analyticsFlowStep;
- (id)parseGraphQLResponseWithResult:(id)arg1 error:(id *)arg2;
- (void)fetchPages;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)prefersStatusBarHidden;
- (void)progressToNextViewController;
- (void)updateNextButton;
- (id)newHeaderViewForTableViewWithWidth:(float)arg1;
- (id)titleForFooterInSection:(int)arg1;
- (id)titleForHeaderInSection:(int)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithFacebookAccessToken:(id)arg1 loggingHelper:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

