//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGBusinessConversionFlowStep.h"
#import "IGCoreTextLinkHandler.h"

@class IGBusinessConversionLoggingHelper, IGButton, IGCoreTextView, NSString, UIImageView, UILabel;

@interface IGBusinessConversionViewController : IGViewController <IGCoreTextLinkHandler, IGBusinessConversionFlowStep>
{
    BOOL _didDeclineFacebookAuth;
    id <IGBusinessConversionViewControllerDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    IGButton *_continueButton;
    UIImageView *_businessIconImageView;
    IGCoreTextView *_disclaimerLabel;
    IGBusinessConversionLoggingHelper *_loggingHelper;
}

+ (id)businessConversionNavigationControllerWithEntrypoint:(id)arg1 delegate:(id)arg2;
@property(retain, nonatomic) IGBusinessConversionLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(nonatomic) BOOL didDeclineFacebookAuth; // @synthesize didDeclineFacebookAuth=_didDeclineFacebookAuth;
@property(retain, nonatomic) IGCoreTextView *disclaimerLabel; // @synthesize disclaimerLabel=_disclaimerLabel;
@property(retain, nonatomic) UIImageView *businessIconImageView; // @synthesize businessIconImageView=_businessIconImageView;
@property(retain, nonatomic) IGButton *continueButton; // @synthesize continueButton=_continueButton;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <IGBusinessConversionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)analyticsFlowStep;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)onCancelModal;
- (BOOL)prefersStatusBarHidden;
- (void)openPageSelectionViewControllerWithAccessToken:(id)arg1;
- (void)openPageSelectionViewControllerWithCurrentUserAccessToken;
- (id)initializeContinueButtonWithFrame:(struct CGRect)arg1;
- (void)getAccessTokenAndPushBusinessSelectorIfPossible;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithEntrypoint:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

