//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGVideoGlyphView, UIImageView, UILabel;

@interface IGChannelOverlayView : UIView
{
    IGVideoGlyphView *_playIcon;
    UILabel *_headerLabel;
    UILabel *_titleLabel;
    UIImageView *_backgroundView;
}

@property(readonly, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(readonly, nonatomic) IGVideoGlyphView *playIcon; // @synthesize playIcon=_playIcon;
- (void).cxx_destruct;
- (float)maxWidthForLabels;
- (id)textKerning;
- (id)titleAttributesUseSmallFont:(BOOL)arg1;
- (id)headerAttributes;
- (void)layoutBackgroundView;
- (void)layoutHeader;
- (void)layoutTitle;
- (void)layoutPlayIcon;
- (void)setupTitleLabel;
- (void)setupHeaderLabel;
- (void)setupPlayIcon;
- (void)setupBackgroundView;
- (void)setupSubviews;
- (void)setTitle:(id)arg1;
- (void)setHeader:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

