//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGClusterBrowsingCategoriesButtonsView, NSNumber;

@protocol IGClusterBrowsingCategoriesButtonsViewDelegate <NSObject>
- (void)categoriesButtonsViewDidSkip:(IGClusterBrowsingCategoriesButtonsView *)arg1;
- (void)categoriesButtonsView:(IGClusterBrowsingCategoriesButtonsView *)arg1 didTapClusterID:(NSNumber *)arg2 atPosition:(int)arg3;
@end

