//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

#import "IGCollectionViewLayoutAdditions.h"

@class NSDictionary, NSString;

@interface IGCollectionViewGridLayout : UICollectionViewLayout <IGCollectionViewLayoutAdditions>
{
    float _supplementaryHeaderViewHeight;
    float _supplementaryFooterViewHeight;
    float _headerAdjustmentAmount;
    int _numberOfColumns;
    float _spacing;
    NSDictionary *_layoutInfo;
    int _numberOfItems;
    float _itemSideLength;
}

@property(readonly, nonatomic) float itemSideLength; // @synthesize itemSideLength=_itemSideLength;
@property(readonly, nonatomic) int numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(retain, nonatomic) NSDictionary *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(readonly, nonatomic) float spacing; // @synthesize spacing=_spacing;
@property(readonly, nonatomic) int numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) float headerAdjustmentAmount; // @synthesize headerAdjustmentAmount=_headerAdjustmentAmount;
@property(nonatomic) float supplementaryFooterViewHeight; // @synthesize supplementaryFooterViewHeight=_supplementaryFooterViewHeight;
@property(nonatomic) float supplementaryHeaderViewHeight; // @synthesize supplementaryHeaderViewHeight=_supplementaryHeaderViewHeight;
- (void).cxx_destruct;
- (struct _NSRange)itemsInRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (void)prepareLayout;
- (void)invalidateLayoutWithContext:(id)arg1;
@property(readonly, nonatomic) struct CGSize itemSize;
- (id)initWithNumberOfColumns:(int)arg1 spacing:(float)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

