//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGCoreTextLinkHandler.h"
#import "IGProfilePictureImageViewDelegate.h"

@class IGCommentModel, IGCoreTextView, IGLabel, IGProfilePictureImageView, NSString, UIActivityIndicatorView, UIImageView;

@interface IGCommentContentView : UIView <IGCoreTextLinkHandler, IGProfilePictureImageViewDelegate>
{
    IGCommentModel *_comment;
    id <IGCommentContentViewDelegate> _delegate;
    IGProfilePictureImageView *_profilePic;
    IGCoreTextView *_coreTextView;
    IGLabel *_metadataLabel;
    UIImageView *_statusView;
    UIActivityIndicatorView *_activityIndicator;
}

+ (float)commentWidthForWidth:(float)arg1;
+ (float)commentXOffset;
+ (float)heightForComment:(id)arg1 width:(float)arg2;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIImageView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) IGLabel *metadataLabel; // @synthesize metadataLabel=_metadataLabel;
@property(retain, nonatomic) IGCoreTextView *coreTextView; // @synthesize coreTextView=_coreTextView;
@property(retain, nonatomic) IGProfilePictureImageView *profilePic; // @synthesize profilePic=_profilePic;
@property(nonatomic) __weak id <IGCommentContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IGCommentModel *comment; // @synthesize comment=_comment;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)profilePictureTapped:(id)arg1;
- (void)updateStatus;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

