//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGLRUCache, NSMapTable, NSObject<OS_dispatch_queue>;

@interface IGDecodedImageCache : NSObject
{
    IGLRUCache *_cache;
    NSMapTable *_weakTrackingMapTable;
    NSObject<OS_dispatch_queue> *_mapTableAccessQueue;
}

+ (id)sharedDecodedImageCache;
+ (int)defaultCostLimit;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *mapTableAccessQueue; // @synthesize mapTableAccessQueue=_mapTableAccessQueue;
@property(readonly, nonatomic) NSMapTable *weakTrackingMapTable; // @synthesize weakTrackingMapTable=_weakTrackingMapTable;
@property(readonly, nonatomic) IGLRUCache *cache; // @synthesize cache=_cache;
- (void).cxx_destruct;
- (void)removeAllImages;
- (void)removeImageForURL:(id)arg1;
- (void)saveImage:(id)arg1 dataLength:(id)arg2 forURL:(id)arg3;
- (id)dataLengthForURL:(id)arg1;
- (id)imageForURL:(id)arg1;
- (void)setTotalCostLimit:(int)arg1;
- (id)init;

@end

