//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectContentUploadInfo;

@protocol IGDirectContentUploadInfoObserver <NSObject>
- (void)notifyStatusChangedForUploadInfo:(IGDirectContentUploadInfo *)arg1;

@optional
- (void)notifyUploadProgressForUploadInfo:(IGDirectContentUploadInfo *)arg1 withUploadProgress:(float)arg2;
@end

