//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGDirectThreadNotificationHelper : NSObject
{
}

+ (void)handleNotificationBarTapForThread:(id)arg1 recipientPK:(id)arg2;
+ (void)showDirectNotificationWithContent:(id)arg1 forThread:(id)arg2 recipientPK:(id)arg3;
+ (id)sharedThreadNotificationHelper;
- (void)didReceiveAddContentNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

