//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGDirectThreadViewControllerDelegate.h"
#import "IGUIPerfLoggable.h"

@class IGUIPerfLogResult, NSString;

@protocol IGDirectInboxControllerType <IGDirectThreadViewControllerDelegate, IGUIPerfLoggable>
- (void)pushToThreadWithThreadId:(NSString *)arg1 animated:(BOOL)arg2 logResult:(IGUIPerfLogResult *)arg3;
- (void)refreshDataWithClearCount:(BOOL)arg1;
- (void)scrollToTopAnimated:(BOOL)arg1;
- (unsigned int)inboxSubscriptionStatus;
@end

