//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGDirectContentUploadable.h"

@class IGUploadModel, NSData, NSURL;

@protocol IGDirectContentMediaUploadable <IGDirectContentUploadable>
@property(nonatomic) struct CGSize aspectRatio;
@property(retain, nonatomic) IGUploadModel *uploadModel;
@property(readonly, nonatomic) BOOL useMainCameraUploadFlow;
@property(retain, nonatomic) NSData *imageData;
@property(readonly, nonatomic) NSURL *cacheKeyURL;
@end

