//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGDirectContent.h"

#import "IGDirectContentSuppressable.h"

@class NSArray, NSString;

@interface IGDirectThreadActionLog : IGDirectContent <IGDirectContentSuppressable>
{
    BOOL _hideInThread;
    NSString *_title;
    NSArray *_boldInfo;
}

@property(retain, nonatomic) NSArray *boldInfo; // @synthesize boldInfo=_boldInfo;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) BOOL hideInThread; // @synthesize hideInThread=_hideInThread;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)digestDescription;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)contentTypeString;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

