//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGButton, IGCoreTextView, UIButton;

@interface IGDirectPushPromptView : UIView
{
    id <IGDirectPushPromptViewDelegate> _delegate;
    IGCoreTextView *_titleLabel;
    IGCoreTextView *_messageLabel;
    UIButton *_dismissButton;
    IGButton *_settingsButton;
}

+ (id)messageStyledStringForText:(id)arg1;
+ (id)titleStyledStringForText:(id)arg1;
+ (float)heightForTitle:(id)arg1 andMessage:(id)arg2 withWidth:(float)arg3;
@property(retain, nonatomic) IGButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) IGCoreTextView *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) IGCoreTextView *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <IGDirectPushPromptViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dismissButtonTapped;
- (void)settingsButtonTapped;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 andTitle:(id)arg2 andMessage:(id)arg3 andButtonText:(id)arg4;

@end

