//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView<IGDirectResponseOverlayable>;

@protocol IGDirectResponseOverlayViewDelegate <NSObject>
- (void)overlayViewDidTapOnButton:(UIView<IGDirectResponseOverlayable> *)arg1;
- (void)overlayViewDidTap:(UIView<IGDirectResponseOverlayable> *)arg1;
@end

