//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedPhotoViewDelegate.h"
#import "IGTimerProxyObjectType.h"

@class IGEventViewerAnalyticsLogger, IGEventViewerPlaybackItem, IGTimerProxy, NSString, NSTimer;

@interface IGEventViewerPhotoPlaybackController : NSObject <IGFeedPhotoViewDelegate, IGTimerProxyObjectType>
{
    id <IGEventViewerPhotoPlaybackControllerDelegate> _delegate;
    NSTimer *_timer;
    IGTimerProxy *_timerProxy;
    IGEventViewerPlaybackItem *_playbackItem;
    IGEventViewerAnalyticsLogger *_logger;
    double _timerProgress;
}

@property(readonly, nonatomic) IGEventViewerAnalyticsLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) IGEventViewerPlaybackItem *playbackItem; // @synthesize playbackItem=_playbackItem;
@property(nonatomic) double timerProgress; // @synthesize timerProgress=_timerProgress;
@property(retain, nonatomic) IGTimerProxy *timerProxy; // @synthesize timerProxy=_timerProxy;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <IGEventViewerPhotoPlaybackControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)feedPhotoViewDidTap:(id)arg1;
- (void)feedPhotoDidDoubleTapToLike:(id)arg1;
- (void)feedPhotoViewDidLoadImage:(id)arg1;
- (BOOL)isCurrentlyPlayingPhoto;
- (void)stopCurrentlyPlayingPhoto;
- (void)playPhotoForItem:(id)arg1;
- (void)didFireTimer:(id)arg1;
- (void)stopTimer;
- (void)startTimer;
@property(readonly, nonatomic) float currentDuration;
@property(readonly, nonatomic) float currentProgress;
- (void)dealloc;
- (id)initWithLogger:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

