//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedItemVideoViewDelegate.h"
#import "IGFeedVideoPlayerPlaybackDelegate.h"

@class IGEventViewerAnalyticsLogger, IGEventViewerPlaybackItem, IGFeedVideoManager, IGFeedVideoPlayer, NSString;

@interface IGEventViewerVideoPlaybackController : NSObject <IGFeedVideoPlayerPlaybackDelegate, IGFeedItemVideoViewDelegate>
{
    BOOL _audioEnabled;
    BOOL _currentVideoDidPlayToEnd;
    id <IGEventViewerVideoPlaybackControllerDelegate> _delegate;
    IGFeedVideoManager *_feedVideoManager;
    IGEventViewerAnalyticsLogger *_logger;
    IGEventViewerPlaybackItem *_playbackItem;
    unsigned int _videoRetryCount;
    float _currentVideoStartTime;
}

@property(nonatomic) float currentVideoStartTime; // @synthesize currentVideoStartTime=_currentVideoStartTime;
@property(nonatomic) unsigned int videoRetryCount; // @synthesize videoRetryCount=_videoRetryCount;
@property(nonatomic) BOOL currentVideoDidPlayToEnd; // @synthesize currentVideoDidPlayToEnd=_currentVideoDidPlayToEnd;
@property(retain, nonatomic) IGEventViewerPlaybackItem *playbackItem; // @synthesize playbackItem=_playbackItem;
@property(readonly, nonatomic) IGEventViewerAnalyticsLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) IGFeedVideoManager *feedVideoManager; // @synthesize feedVideoManager=_feedVideoManager;
@property(nonatomic) BOOL audioEnabled; // @synthesize audioEnabled=_audioEnabled;
@property(nonatomic) __weak id <IGEventViewerVideoPlaybackControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)feedItemVideoView:(id)arg1 didToggleAudio:(BOOL)arg2;
- (void)feedItemVideoViewDidLongPress:(id)arg1;
- (void)feedItemVideoViewDidRequestVideoPlayback:(id)arg1;
- (void)feedItemVideoViewDidPlayToEnd:(id)arg1;
- (void)feedItemVideoView:(id)arg1 didFailToPlayWithError:(id)arg2;
- (void)feedItemVideoViewDidDoubleTap:(id)arg1;
- (void)feedItemVideoViewDidPauseWithEmptyBuffer:(id)arg1;
- (void)feedItemVideoViewDidPlay:(id)arg1;
- (void)feedItemVideoViewDidLoadImage:(id)arg1;
- (void)videoPlayer:(id)arg1 didFailWithError:(id)arg2;
- (void)videoPlayer:(id)arg1 isWaitingForBuffer:(BOOL)arg2;
- (void)videoPlayerDidPlayToEnd:(id)arg1;
- (void)videoPlayer:(id)arg1 didUpdateProgress:(float)arg2;
- (void)videoPlayerDidStartPlaying:(id)arg1;
- (BOOL)isCurrentlyPlayingVideo;
- (void)stopCurrentlyPlayingVideo;
- (void)playVideoForItem:(id)arg1 startTime:(float)arg2;
@property(readonly, nonatomic) IGFeedVideoPlayer *currentPlayer;
@property(readonly, nonatomic) float currentDuration;
@property(readonly, nonatomic) float currentProgress;
- (id)initWithFeedVideoManager:(id)arg1 logger:(id)arg2;
- (id)initWithLogger:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

