//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListAdapterDataSource.h"

@class IGSpinnerModel, NSMutableArray, NSString;

@interface IGEventViewerDataSource : NSObject <IGListAdapterDataSource>
{
    BOOL _isSpinnerHidden;
    id <IGEventViewerMediaCellDelegate> _mediaCellDelegate;
    id <IGEventViewerAttributionHeaderCellDelegate> _headerCellDelegate;
    NSMutableArray *_posts;
    IGSpinnerModel *_spinner;
}

@property(nonatomic, setter=setSpinnerHidden:) BOOL isSpinnerHidden; // @synthesize isSpinnerHidden=_isSpinnerHidden;
@property(readonly, nonatomic) IGSpinnerModel *spinner; // @synthesize spinner=_spinner;
@property(retain, nonatomic) NSMutableArray *posts; // @synthesize posts=_posts;
@property(nonatomic) __weak id <IGEventViewerAttributionHeaderCellDelegate> headerCellDelegate; // @synthesize headerCellDelegate=_headerCellDelegate;
@property(nonatomic) __weak id <IGEventViewerMediaCellDelegate> mediaCellDelegate; // @synthesize mediaCellDelegate=_mediaCellDelegate;
- (void).cxx_destruct;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 listItemControllerForItem:(id)arg2;
- (id)itemsForListAdapter:(id)arg1;
- (id)indexPathForPost:(id)arg1;
- (id)postAtIndexPath:(id)arg1;
- (void)deletePostAtIndexPath:(id)arg1;
- (void)replacePostsWithPosts:(id)arg1;
- (void)appendPosts:(id)arg1;
- (id)allPosts;
@property(readonly, nonatomic) unsigned int count;
- (id)init;
- (id)initWithPosts:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

