//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGEventViewerPhotoPlaybackControllerDelegate.h"
#import "IGEventViewerVideoPlaybackControllerDelegate.h"

@class IGEventViewerAnalyticsLogger, IGEventViewerPhotoPlaybackController, IGEventViewerVideoPlaybackController, NSString;

@interface IGEventViewerMediaPlaybackController : NSObject <IGEventViewerVideoPlaybackControllerDelegate, IGEventViewerPhotoPlaybackControllerDelegate>
{
    id <IGEventViewerMediaPlaybackDelegate> _playDelegate;
    id <IGEventViewerMediaProgressDelegate> _progressDelegate;
    IGEventViewerVideoPlaybackController *_videoPlaybackController;
    IGEventViewerPhotoPlaybackController *_photoPlaybackController;
    IGEventViewerAnalyticsLogger *_logger;
}

@property(readonly, nonatomic) IGEventViewerAnalyticsLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) IGEventViewerPhotoPlaybackController *photoPlaybackController; // @synthesize photoPlaybackController=_photoPlaybackController;
@property(readonly, nonatomic) IGEventViewerVideoPlaybackController *videoPlaybackController; // @synthesize videoPlaybackController=_videoPlaybackController;
@property(nonatomic) __weak id <IGEventViewerMediaProgressDelegate> progressDelegate; // @synthesize progressDelegate=_progressDelegate;
@property(nonatomic) __weak id <IGEventViewerMediaPlaybackDelegate> playDelegate; // @synthesize playDelegate=_playDelegate;
- (void).cxx_destruct;
- (void)photoPlaybackController:(id)arg1 didUpdatePhotoProgress:(float)arg2 forItem:(id)arg3;
- (void)photoPlaybackController:(id)arg1 didEndPlayingPhotoForItem:(id)arg2;
- (void)photoPlaybackController:(id)arg1 didBeginPlayingPhotoForItem:(id)arg2 withDuration:(double)arg3;
- (void)videoPlaybackController:(id)arg1 didUpdateVideoProgress:(float)arg2 forItem:(id)arg3;
- (void)videoPlaybackController:(id)arg1 didPlayVideoToEndForItem:(id)arg2;
- (void)videoPlaybackController:(id)arg1 didBeginPlayingItem:(id)arg2 withDuration:(double)arg3;
- (float)currentDurationForPost:(id)arg1;
- (float)currentProgressForPost:(id)arg1;
- (void)stopCurrentMedia;
- (BOOL)isPlayingMedia;
- (void)playMediaForItem:(id)arg1 startTime:(float)arg2;
@property(nonatomic) BOOL audioEnabled;
- (id)initWithLogger:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

