//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGExploreCarouselViewModel, IGExploreCarouselsView, NSIndexPath, NSString;

@protocol IGExploreCarouselsDataSource <NSObject>
- (IGExploreCarouselViewModel *)carouselsView:(IGExploreCarouselsView *)arg1 viewModelForCarouselItemAtIndexPath:(NSIndexPath *)arg2;
- (unsigned int)carouselsView:(IGExploreCarouselsView *)arg1 numberOfItemsForCarouselAtSection:(unsigned int)arg2;
- (NSString *)carouselsView:(IGExploreCarouselsView *)arg1 actionTitleForCarouselAtSection:(unsigned int)arg2;
- (BOOL)carouselsView:(IGExploreCarouselsView *)arg1 shouldShowButtonForCarouselAtSection:(unsigned int)arg2;
- (NSString *)carouselsView:(IGExploreCarouselsView *)arg1 titleForCarouselAtSection:(unsigned int)arg2;
- (unsigned int)numberOfCarouselsInCarouselsView:(IGExploreCarouselsView *)arg1;
@end

