//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFeedViewController_DEPRECATED.h"

#import "IGMarqueeAttributionViewDelegate.h"

@class IGExploreMarqueeItem, NSMutableSet, NSString;

@interface IGExploreEventViewController : IGFeedViewController_DEPRECATED <IGMarqueeAttributionViewDelegate>
{
    IGExploreMarqueeItem *_marqueeItem;
    NSMutableSet *_loggedImpressions;
}

@property(retain, nonatomic) NSMutableSet *loggedImpressions; // @synthesize loggedImpressions=_loggedImpressions;
@property(readonly, nonatomic) IGExploreMarqueeItem *marqueeItem; // @synthesize marqueeItem=_marqueeItem;
- (void).cxx_destruct;
- (void)logMediaImpression:(id)arg1 viewed:(BOOL)arg2 atIndex:(int)arg3;
- (void)logMediaClick:(id)arg1 atIndex:(int)arg2;
- (void)marqueeAttributionView:(id)arg1 didTapUsername:(id)arg2;
- (void)configureMarqueeAttributionView;
- (void)configureMarqueeContextView;
- (void)updateScrollFromContextualFeed;
- (void)handleLoadedContentDidChange;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithMarqueeItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

