//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface IGExploreSectionTextHeader : UIView
{
    UILabel *_titleLabel;
    UIButton *_actionButton;
    UIImageView *_iconView;
    unsigned int _titleLocation;
}

@property(nonatomic) unsigned int titleLocation; // @synthesize titleLocation=_titleLocation;
@property(readonly, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(readonly, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutTitle;
- (void)layoutActionButton;
- (void)layoutIcon;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

