//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGExploreMainFeedLayoutConfiguration : NSObject
{
    float _interItemSpacing;
    float _mediasPerRow;
}

@property(readonly, nonatomic) float mediasPerRow; // @synthesize mediasPerRow=_mediasPerRow;
@property(readonly, nonatomic) float interItemSpacing; // @synthesize interItemSpacing=_interItemSpacing;
- (id)initWithInterItemSpacing:(float)arg1 mediasPerRow:(float)arg2;
- (id)init;

@end

