//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGExplorePromptConfiguration : NSObject
{
}

+ (int)getIntegerValueForParam:(id)arg1;
+ (int)maxImpressionForPrompt;
+ (double)intervalBetweenImpressions;
+ (double)timeToFadeOut;
+ (int)numberOfPostBeforePrompt;
+ (BOOL)allowPrompt;
+ (int)timeToPrefetchExploreV3;
+ (int)timeToPrefetchExploreV2;

@end

