//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDKSharingDelegate.h"
#import "IGServiceHelperProtocol.h"

@class IGGraphQLService, IGNonCurrentUserDefaults, NSString;

@interface IGFacebookHelper : NSObject <FBSDKSharingDelegate, IGServiceHelperProtocol>
{
    BOOL _isAskingForAdditionalPermisons;
    BOOL _isInvalidated;
    IGGraphQLService *_graphQLService;
    NSString *_userSessionPK;
    IGNonCurrentUserDefaults *_sessionUserDefaults;
    unsigned int _debugIGFBAccessTokenSource;
}

+ (void)clearForUserPK:(id)arg1;
+ (id)shortServiceName;
+ (id)serviceName;
+ (id)loadAccessTokenWithPk:(id)arg1;
+ (void)clearAccessTokenForPk:(id)arg1;
+ (void)storeAccessToken:(id)arg1 forPk:(id)arg2;
+ (id)storedTokenKeyForPk:(id)arg1;
+ (id)sharedHelper;
@property(nonatomic) BOOL isInvalidated; // @synthesize isInvalidated=_isInvalidated;
@property(nonatomic) unsigned int debugIGFBAccessTokenSource; // @synthesize debugIGFBAccessTokenSource=_debugIGFBAccessTokenSource;
@property(nonatomic) BOOL isAskingForAdditionalPermisons; // @synthesize isAskingForAdditionalPermisons=_isAskingForAdditionalPermisons;
@property(retain, nonatomic) IGNonCurrentUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
@property(retain, nonatomic) NSString *userSessionPK; // @synthesize userSessionPK=_userSessionPK;
@property(readonly, nonatomic) IGGraphQLService *graphQLService; // @synthesize graphQLService=_graphQLService;
- (void).cxx_destruct;
- (void)refreshCurrentUserInfoIfExpired;
- (void)sharerDidCancel:(id)arg1;
- (void)sharer:(id)arg1 didFailWithError:(id)arg2;
- (void)sharer:(id)arg1 didCompleteWithResults:(id)arg2;
- (void)shareFeedItem:(id)arg1 fromViewController:(id)arg2;
- (BOOL)canShare;
- (void)fetchUserInfoWithFetchStrategy:(int)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)currentUserInfo;
- (void)restoreCurrentUserInfoFromIGDefaults;
- (void)storeCurrentUserInfoToIGUserDefaults;
- (void)setPageName:(id)arg1;
- (id)pageName;
- (void)setPageAccessToken:(id)arg1;
- (id)pageAccessToken;
- (BOOL)hasAuthorizedManagePages;
- (BOOL)hasAuthorizedWallPost;
- (void)restoreSession;
- (void)logoutAndUnlink;
- (void)logout;
- (id)sharingInfo;
- (BOOL)hasAdvancedOptions;
- (BOOL)isConfigured;
- (BOOL)supportsMediaType:(int)arg1;
- (BOOL)isAvailableInCurrentLocale;
- (BOOL)isConfigurable;
- (BOOL)needsToReauthorize;
- (void)reauthorizeIfNeeded;
- (BOOL)requiresLocationCoordinate;
- (id)viewControllerForAdvancedOptions;
- (void)invalidate;
- (void)clearActiveSession;
- (void)setIsAskingForAdditionalPermissions:(BOOL)arg1;
- (BOOL)takeIsAskingForAdditionalPermissions;
- (void)fbDidNotLogin;
- (BOOL)isLoggedIn;
- (id)currentAccessToken;
- (void)notifyAuthCompleted;
- (void)fbDidLoginSendCredentials:(BOOL)arg1;
- (void)sendCredentialsToServer:(id)arg1;
- (void)onLoginSuccessful:(id)arg1;
- (void)accessTokenChanged:(id)arg1 shouldSendCredentials:(BOOL)arg2 error:(id)arg3;
- (void)handleAccessTokenChange:(id)arg1 shouldSendCredentials:(BOOL)arg2 error:(id)arg3;
- (void)handleAccessTokenChange:(id)arg1 error:(id)arg2;
- (id)initWithUserSessionPK:(id)arg1 sessionUserDefaults:(id)arg2;
- (id)initWithSessionUserDefaults:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

