//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItemPageCell, IGPostItem;

@protocol IGFeedItemPageCellDelegate <NSObject>
- (void)feedItemPageCell:(IGFeedItemPageCell *)arg1 itemDidStartViewing:(IGPostItem *)arg2;
- (void)feedItemPageCell:(IGFeedItemPageCell *)arg1 didScrollToPageIndex:(int)arg2 fromIndex:(int)arg3;
- (void)feedItemPageCellDidDoubleTapToLike:(IGFeedItemPageCell *)arg1;
- (void)feedItemPageCellDidSingleTap:(IGFeedItemPageCell *)arg1 continueAction:(BOOL)arg2;
- (void)feedItemPageCellDidInitialSingleTap:(IGFeedItemPageCell *)arg1;
@end

