//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedVideoCellPlayerDelegate.h"

@class IGCollectionViewVisibility, IGFeedItemVideoView, IGFeedPrebufferingHelper, IGVideoPlaybackConfiguration, NSString, UICollectionView, UICollectionViewCell<IGFeedVideoCell>;

@interface IGFeedVideoCellManager : NSObject <IGFeedVideoCellPlayerDelegate>
{
    BOOL _disallowVideoStart;
    BOOL _supportsAutoplay;
    IGFeedItemVideoView *_currentlyPlayingVideoView;
    UICollectionViewCell<IGFeedVideoCell> *_currentlyPlayingVideoCell;
    UICollectionView *_collectionView;
    IGCollectionViewVisibility *_collectionViewVisibility;
    IGFeedPrebufferingHelper *_prebufferingHelper;
    IGVideoPlaybackConfiguration *_defaultPlaybackConfig;
}

@property(readonly, nonatomic) IGVideoPlaybackConfiguration *defaultPlaybackConfig; // @synthesize defaultPlaybackConfig=_defaultPlaybackConfig;
@property(readonly, nonatomic) IGFeedPrebufferingHelper *prebufferingHelper; // @synthesize prebufferingHelper=_prebufferingHelper;
@property(readonly, nonatomic) BOOL supportsAutoplay; // @synthesize supportsAutoplay=_supportsAutoplay;
@property(readonly, nonatomic) IGCollectionViewVisibility *collectionViewVisibility; // @synthesize collectionViewVisibility=_collectionViewVisibility;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UICollectionViewCell<IGFeedVideoCell> *currentlyPlayingVideoCell; // @synthesize currentlyPlayingVideoCell=_currentlyPlayingVideoCell;
@property(nonatomic) BOOL disallowVideoStart; // @synthesize disallowVideoStart=_disallowVideoStart;
@property(retain, nonatomic) IGFeedItemVideoView *currentlyPlayingVideoView; // @synthesize currentlyPlayingVideoView=_currentlyPlayingVideoView;
- (void).cxx_destruct;
- (void)feedVideoCellDidPlayToEnd:(id)arg1;
- (BOOL)isFirstPost:(id)arg1;
- (void)feedVideoCellDidLoadImage:(id)arg1;
- (void)feedVideoCellDidRequestCurrentVideoStopWithReason:(int)arg1;
- (void)feedVideoCellDidRequestVideoPlayback:(id)arg1 config:(id)arg2;
- (void)stopCurrentVideoCellIfNotVisible;
- (void)startVideoIfAutoplayCellExists;
- (id)videoCellForAutoPlay;
- (void)stopCurrentVideo;
- (void)stopCurrentVideoWithReason:(int)arg1;
- (void)startVideoForCell:(id)arg1 config:(id)arg2;
- (BOOL)startVideoForCellIfApplicable:(id)arg1;
- (id)preferredVideoURLForVideoView:(id)arg1;
- (void)cleanUpDisplayedCell:(id)arg1;
- (void)prepareCellToBeDisplayed:(id)arg1;
- (void)updatePlayingCellScrollViewIsScrolling:(BOOL)arg1;
- (id)initWithCollectionView:(id)arg1 collectionViewVisibility:(id)arg2 prebufferingHelper:(id)arg3 supportsAutoplay:(BOOL)arg4 defaultPlaybackConfiguration:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

