//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFullViewImpressionTracker, NSArray;

@interface IGFeedViewControllerTracker : NSObject
{
    NSArray *_impressionTrackers;
    IGFullViewImpressionTracker *_fullViewImpressionTracker;
}

@property(readonly, nonatomic) IGFullViewImpressionTracker *fullViewImpressionTracker; // @synthesize fullViewImpressionTracker=_fullViewImpressionTracker;
@property(readonly, nonatomic) NSArray *impressionTrackers; // @synthesize impressionTrackers=_impressionTrackers;
- (void).cxx_destruct;
- (void)updateTrackersForContentChangeWithCollectionView:(id)arg1 allItems:(id)arg2 visibleContentRect:(struct CGRect)arg3;
- (void)updateFullviewTrackerWithAllItems:(id)arg1;
- (id)initWithLoggingProviderDelegate:(id)arg1 raindropDelegate:(id)arg2 isMainFeed:(BOOL)arg3 feedNetworkSource:(id)arg4;

@end

