//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGToolPickerCell.h"

@class UILabel, UIView;

@interface IGFilterPickerCell : IGToolPickerCell
{
    BOOL _displayNewFilterNUX;
    UILabel *_nuxNewLabel;
    UIView *_nuxOverlay;
}

@property(retain, nonatomic) UIView *nuxOverlay; // @synthesize nuxOverlay=_nuxOverlay;
@property(retain, nonatomic) UILabel *nuxNewLabel; // @synthesize nuxNewLabel=_nuxNewLabel;
@property(nonatomic) BOOL displayNewFilterNUX; // @synthesize displayNewFilterNUX=_displayNewFilterNUX;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setDisplayNewFilterNUX:(BOOL)arg1 animated:(BOOL)arg2;

@end

