//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFoursquareAuthDelegate.h"
#import "IGServiceHelperProtocol.h"

@class IGNonCurrentUserDefaults, NSString;

@interface IGFoursquareHelper : NSObject <IGFoursquareAuthDelegate, IGServiceHelperProtocol>
{
    NSString *_accessToken;
    NSString *_username;
    IGNonCurrentUserDefaults *_sessionUserDefaults;
}

+ (id)accessTokenKey;
+ (void)logoutFromDefaults:(id)arg1;
+ (void)clearForUserPK:(id)arg1;
+ (id)serviceName;
+ (id)shortServiceName;
+ (id)sharedHelper;
@property(retain, nonatomic) IGNonCurrentUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void).cxx_destruct;
- (void)setAccessToken:(id)arg1 username:(id)arg2 save:(BOOL)arg3;
- (void)foursquareAuthControllerLoginFailed:(id)arg1;
- (void)foursquareAuthController:(id)arg1 didLoginWithAccessToken:(id)arg2 username:(id)arg3;
- (id)sharingInfo;
- (BOOL)needsToReauthorize;
- (void)reauthorizeIfNeeded;
- (BOOL)requiresLocationCoordinate;
- (BOOL)supportsMediaType:(int)arg1;
- (BOOL)hasEverBeenConfigured;
- (BOOL)isAvailableInCurrentLocale;
- (BOOL)isConfigurable;
- (BOOL)hasAdvancedOptions;
- (BOOL)isConfigured;
- (void)logout;
- (void)logoutAndUnlink;
- (id)viewControllerForAdvancedOptions;
- (id)currentUsername;
- (id)authURLString;
- (id)callbackURLString;
- (id)clientID;
- (id)initWithSessionUserDefaults:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

