//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIView;

@interface IGFullWidthCTAButton : UIButton
{
    NSString *_primaryText;
    NSString *_secondaryText;
    int _buttonState;
    UIView *_topHairline;
    UIView *_bottomHairline;
}

@property(readonly, nonatomic) UIView *bottomHairline; // @synthesize bottomHairline=_bottomHairline;
@property(readonly, nonatomic) UIView *topHairline; // @synthesize topHairline=_topHairline;
@property(nonatomic) int buttonState; // @synthesize buttonState=_buttonState;
@property(copy, nonatomic) NSString *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(copy, nonatomic) NSString *primaryText; // @synthesize primaryText=_primaryText;
- (void).cxx_destruct;
- (void)configureTextVisualsForFilledInState;
- (void)configureVisualsForFilledInState;
- (void)configureTextVisualsForDefaultState;
- (void)configureVisualsForDefaultState;
- (void)animateToButtonState:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

