//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGImageViewDelegate.h"

@class IGGenericMegaphone, IGImageView, NSString, UIButton, UIImage, UILabel;

@interface IGGenericMegaphoneViewV2 : UIView <IGImageViewDelegate>
{
    BOOL _megaphoneSeen;
    IGGenericMegaphone *_megaphone;
    UIImage *_megaphoneImage;
    id <IGGenericMegaphoneViewV2Delegate> _delegate;
    UILabel *_titleView;
    UILabel *_messageView;
    IGImageView *_imageView;
    UIButton *_dismissButton;
    UIView *_lineView;
    UIButton *_buttonOne;
    UIButton *_buttonTwo;
    NSString *_displaySource;
}

@property(copy, nonatomic) NSString *displaySource; // @synthesize displaySource=_displaySource;
@property(nonatomic) BOOL megaphoneSeen; // @synthesize megaphoneSeen=_megaphoneSeen;
@property(retain, nonatomic) UIButton *buttonTwo; // @synthesize buttonTwo=_buttonTwo;
@property(retain, nonatomic) UIButton *buttonOne; // @synthesize buttonOne=_buttonOne;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) IGImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *messageView; // @synthesize messageView=_messageView;
@property(retain, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(nonatomic) __weak id <IGGenericMegaphoneViewV2Delegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *megaphoneImage; // @synthesize megaphoneImage=_megaphoneImage;
@property(retain, nonatomic) IGGenericMegaphone *megaphone; // @synthesize megaphone=_megaphone;
- (void).cxx_destruct;
- (void)imageViewLoadedImage:(id)arg1;
- (void)didSelectButtonTwo;
- (void)didSelectButtonOne;
- (void)didDismiss;
- (id)createMegaphoneImageView;
- (id)createMessageView;
- (id)createTitleView;
- (id)createDismissButton;
- (id)createButtonTwo;
- (id)createButtonOne;
- (id)createButtonForMegaphoneButton:(id)arg1;
- (void)layoutTextView;
- (void)layoutButtons;
- (void)layoutDismissButton;
- (void)layoutImageView;
- (BOOL)megaphoneHasImage;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithMegaphone:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

