//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGHScrollAYMFCell;

@protocol IGHScrollAYMFCellDelegate <NSObject>
- (void)didTapFollowButtonInCell:(IGHScrollAYMFCell *)arg1 withAction:(int)arg2;
- (void)didTapAYMFCell:(IGHScrollAYMFCell *)arg1;
- (void)didDismissAYMFCell:(IGHScrollAYMFCell *)arg1;
@end

