//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGHScrollAYMFCellItemControllerDelegate.h"
#import "IGListAdapterDataSource.h"
#import "IGListAdapterDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class IGListAdapter, IGListCollectionView, IGUser, NSArray, NSString;

@interface IGHScrollSimilarAccountsControl : NSObject <IGListAdapterDataSource, IGHScrollAYMFCellItemControllerDelegate, IGListAdapterDelegate, UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_items;
    IGListAdapter *_listAdapter;
    IGListCollectionView *_collectionView;
    IGUser *_user;
}

@property(readonly, nonatomic) IGUser *user; // @synthesize user=_user;
@property(readonly, nonatomic) IGListCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)logDismissActionAtPosition:(unsigned int)arg1;
- (void)logTapActionAtPosition:(unsigned int)arg1;
- (void)logFollowActionAtPosition:(unsigned int)arg1;
- (void)logUserImpressionAtPosition:(unsigned int)arg1;
- (void)filterFollowedAccounts;
- (void)didTapFollowButtonInCell:(id)arg1 withAction:(int)arg2;
- (void)didTapAYMFCell:(id)arg1;
- (void)didDismissAYMFCell:(id)arg1;
- (void)listAdapter:(id)arg1 didEndDisplayingItem:(id)arg2 atIndex:(int)arg3;
- (void)listAdapter:(id)arg1 willDisplayItem:(id)arg2 atIndex:(int)arg3;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 listItemControllerForItem:(id)arg2;
- (id)itemsForListAdapter:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)configureWithUser:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

