//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UILabel;

@interface IGHScrollAYMFBannerCell : UICollectionViewCell
{
    id <IGHScrollAYMFBannerCellDelegate> _delegate;
    UILabel *_titleLabel;
    UIButton *_actionButton;
}

@property(readonly, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <IGHScrollAYMFBannerCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didTapActionButton;
- (void)configureWithTitle:(id)arg1 actionLabel:(id)arg2;
- (void)setUpViews;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

