//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIColor;

@interface IGHybridWebViewHeaderViewConfig : NSObject
{
    UIColor *_headerColor;
    NSString *_headerTitle;
    UIColor *_rightButtonActiveColor;
    UIColor *_rightButtonInactiveColor;
}

@property(readonly, nonatomic) UIColor *rightButtonInactiveColor; // @synthesize rightButtonInactiveColor=_rightButtonInactiveColor;
@property(readonly, nonatomic) UIColor *rightButtonActiveColor; // @synthesize rightButtonActiveColor=_rightButtonActiveColor;
@property(readonly, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(readonly, nonatomic) UIColor *headerColor; // @synthesize headerColor=_headerColor;
- (void).cxx_destruct;
- (id)initWithContext:(unsigned int)arg1;

@end

