//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGInsightsComponentAdapter.h"

@class IGInsightsCenteredParagraphPageView, IGInsightsLoggingHelper, IGInsightsParagraphComponent, NSString;

@interface IGInsightsCenteredParagraphComponentAdapter : NSObject <IGInsightsComponentAdapter>
{
    id <IGInsightsComponentNavigationDelegate> navigationDelegate;
    IGInsightsCenteredParagraphPageView *_componentView;
    IGInsightsParagraphComponent *_component;
    IGInsightsLoggingHelper *_loggingHelper;
    unsigned int _surface;
}

@property(nonatomic) unsigned int surface; // @synthesize surface=_surface;
@property(retain, nonatomic) IGInsightsLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(retain, nonatomic) IGInsightsParagraphComponent *component; // @synthesize component=_component;
@property(retain, nonatomic) IGInsightsCenteredParagraphPageView *componentView; // @synthesize componentView=_componentView;
@property(nonatomic) __weak id <IGInsightsComponentNavigationDelegate> navigationDelegate; // @synthesize navigationDelegate;
- (void).cxx_destruct;
- (BOOL)isComponentValid;
- (id)initWithComponent:(id)arg1 loggingHelper:(id)arg2 surface:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

