//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGInsightsDataProviderDelegate.h"

@class IGInsightsCollectionViewComponent, IGInsightsDataProvider, IGInsightsFilterUnit, IGInsightsQuery, NSArray, NSString;

@interface IGInsightsSeeAllPostsTabContentViewDataSource : NSObject <IGInsightsDataProviderDelegate>
{
    BOOL _dataFetchInProgress;
    BOOL _moreAvailable;
    NSString *_filterSummaryTitle;
    id <IGInsightsSeeAllPostsTabContentViewDataSourceDelegate> _delegate;
    NSArray *_allMediaBundles;
    IGInsightsQuery *_query;
    IGInsightsFilterUnit *_filterUnit;
    IGInsightsCollectionViewComponent *_collectionViewComponent;
    IGInsightsDataProvider *_insightsDataProvider;
    IGInsightsDataProvider *_mediaBundleDataProvider;
    NSArray *_educationUnits;
    NSString *_maxId;
}

@property(retain, nonatomic) NSString *maxId; // @synthesize maxId=_maxId;
@property(copy, nonatomic) NSArray *educationUnits; // @synthesize educationUnits=_educationUnits;
@property(retain, nonatomic) IGInsightsDataProvider *mediaBundleDataProvider; // @synthesize mediaBundleDataProvider=_mediaBundleDataProvider;
@property(retain, nonatomic) IGInsightsDataProvider *insightsDataProvider; // @synthesize insightsDataProvider=_insightsDataProvider;
@property(retain, nonatomic) IGInsightsCollectionViewComponent *collectionViewComponent; // @synthesize collectionViewComponent=_collectionViewComponent;
@property(retain, nonatomic) IGInsightsFilterUnit *filterUnit; // @synthesize filterUnit=_filterUnit;
@property(retain, nonatomic) IGInsightsQuery *query; // @synthesize query=_query;
@property(retain, nonatomic) NSArray *allMediaBundles; // @synthesize allMediaBundles=_allMediaBundles;
@property(nonatomic) BOOL moreAvailable; // @synthesize moreAvailable=_moreAvailable;
@property(nonatomic) __weak id <IGInsightsSeeAllPostsTabContentViewDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *filterSummaryTitle; // @synthesize filterSummaryTitle=_filterSummaryTitle;
@property(nonatomic) BOOL dataFetchInProgress; // @synthesize dataFetchInProgress=_dataFetchInProgress;
- (void).cxx_destruct;
- (void)didGetResponseFromMediaBundleDataProvider:(id)arg1;
- (void)didGetResponseFromInsightsDataProvider:(id)arg1;
- (void)requestFailureForDataProvider:(id)arg1 errorMessage:(id)arg2;
- (void)didGetResponseForDataProvider:(id)arg1;
- (BOOL)loadedOnce;
- (void)requestInsightsDataForCurrentQueryItems;
- (void)fetchInsightsDataForQuery:(id)arg1;
- (void)fetchFeedItemsFromMediaIDs:(id)arg1;
- (void)fetchMoreMediaBundles;
- (void)fetchMediaBundles;
- (void)cleanupQueryHistory;
- (id)getEducationUnits;
- (id)getFilterUnit;
- (id)getAllMediaBundles;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

