//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "IGInsightsDataProviderDelegate.h"

@class IGImageView, IGInsightsCollectionViewMediaCell, IGInsightsDataProvider, NSString, UILabel;

@interface IGInsightsSeeAllPostsSwitchPostTypeCell : UITableViewCell <IGInsightsDataProviderDelegate>
{
    IGImageView *_sampleImageView;
    UILabel *_titleLabel;
    IGInsightsDataProvider *_mediaBundleDataProvider;
    IGInsightsCollectionViewMediaCell *_cell;
}

@property(retain, nonatomic) IGInsightsCollectionViewMediaCell *cell; // @synthesize cell=_cell;
@property(retain, nonatomic) IGInsightsDataProvider *mediaBundleDataProvider; // @synthesize mediaBundleDataProvider=_mediaBundleDataProvider;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) IGImageView *sampleImageView; // @synthesize sampleImageView=_sampleImageView;
- (void).cxx_destruct;
- (void)updateViewWithMediaBundle:(id)arg1;
- (void)requestFailureForDataProvider:(id)arg1 errorMessage:(id)arg2;
- (void)didGetResponseForDataProvider:(id)arg1;
- (void)fetchFeedItemsFromMediaIDs:(id)arg1;
- (void)layoutSubviews;
- (id)initWithSampleImageMediaID:(id)arg1 title:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

