//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSDictionary, NSMutableDictionary;

@interface IGInsightsInsightsDataOrderingSelectorView : UIView
{
    NSArray *_buttonTitles;
    id <IGInsightsInsightsDataOrderingSelectorViewDelegate> _delegate;
    NSArray *_buttons;
    unsigned int _activeIndex;
    NSDictionary *_buttonTitleToImageNameMapping;
    NSMutableDictionary *_buttonIndexToTintedImageMapping;
}

@property(copy, nonatomic) NSMutableDictionary *buttonIndexToTintedImageMapping; // @synthesize buttonIndexToTintedImageMapping=_buttonIndexToTintedImageMapping;
@property(copy, nonatomic) NSDictionary *buttonTitleToImageNameMapping; // @synthesize buttonTitleToImageNameMapping=_buttonTitleToImageNameMapping;
@property(nonatomic) unsigned int activeIndex; // @synthesize activeIndex=_activeIndex;
@property(readonly, copy, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(nonatomic) __weak id <IGInsightsInsightsDataOrderingSelectorViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *buttonTitles; // @synthesize buttonTitles=_buttonTitles;
- (void).cxx_destruct;
- (void)activateButtonAtIndex:(unsigned int)arg1;
- (void)deactivateButtonAtIndex:(unsigned int)arg1;
- (void)buttonClick:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initializeButtonTitleToImageNameMapping;
- (id)init;

@end

