//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGInlineGalleryDataSource.h"

@class ALAssetsGroup, ALAssetsLibrary, NSArray, NSObject<OS_dispatch_queue>;

@interface IGInlineGalleryALDataSource : NSObject <IGInlineGalleryDataSource>
{
    id <IGInlineGalleryDataSourceDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    int _maxItems;
    ALAssetsLibrary *_assetsLibrary;
    ALAssetsGroup *_savedPhotosGroup;
    NSArray *_assets;
}

@property(retain, nonatomic) NSArray *assets; // @synthesize assets=_assets;
@property(retain, nonatomic) ALAssetsGroup *savedPhotosGroup; // @synthesize savedPhotosGroup=_savedPhotosGroup;
@property(retain, nonatomic) ALAssetsLibrary *assetsLibrary; // @synthesize assetsLibrary=_assetsLibrary;
@property(nonatomic) int maxItems; // @synthesize maxItems=_maxItems;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <IGInlineGalleryDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)errorMessageIfInvalidAssetAtIndexPath:(id)arg1;
- (id)metadataForAssetAtIndexPath:(id)arg1;
- (void)decorateGridCell:(id)arg1 forAssetAtIndexPath:(id)arg2;
- (int)numberOfItems;
- (int)numMediaSince:(double)arg1;
- (void)setThumbnailSize:(struct CGSize)arg1;
- (id)extractAssetsForGroup:(id)arg1;
- (void)assignDefaultPhotoGroupWithCompletion:(CDUnknownBlockType)arg1;
- (id)assetForIndexPath:(id)arg1;
- (void)filterAssetsGroup:(id)arg1;
- (void)refreshAssetGroup:(id)arg1;
- (void)assetsLibraryDidChange:(id)arg1;
- (void)pauseDataFetch;
- (void)startDataFetchWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)hasCameraRollAccess;
- (id)initWithMaxItems:(int)arg1;
- (void)dealloc;

@end

