//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGListAdapter, IGListItemController<IGListItemType>, UICollectionViewCell;

@protocol IGListDisplayDelegate <NSObject>
- (void)listAdapter:(IGListAdapter *)arg1 didScrollListItemController:(IGListItemController<IGListItemType> *)arg2;
- (void)listAdapter:(IGListAdapter *)arg1 didEndDisplayingListItemController:(IGListItemController<IGListItemType> *)arg2 cell:(UICollectionViewCell *)arg3 atIndex:(int)arg4;
- (void)listAdapter:(IGListAdapter *)arg1 willDisplayListItemController:(IGListItemController<IGListItemType> *)arg2 cell:(UICollectionViewCell *)arg3 atIndex:(int)arg4;
- (void)listAdapter:(IGListAdapter *)arg1 didEndDisplayingListItemController:(IGListItemController<IGListItemType> *)arg2;
- (void)listAdapter:(IGListAdapter *)arg1 willDisplayListItemController:(IGListItemController<IGListItemType> *)arg2;
@end

