//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayoutAttributes.h"

@interface IGListVerticalLayoutAttributes : UICollectionViewLayoutAttributes
{
    BOOL _isOriginEstimated;
    BOOL _isSizeEstimated;
    BOOL _isSticky;
}

+ (id)layoutAttributesForHeaderViewWithIndexPath:(id)arg1;
@property(nonatomic) BOOL isSticky; // @synthesize isSticky=_isSticky;
@property(nonatomic) BOOL isSizeEstimated; // @synthesize isSizeEstimated=_isSizeEstimated;
@property(nonatomic) BOOL isOriginEstimated; // @synthesize isOriginEstimated=_isOriginEstimated;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic) struct CGPoint origin;
@property(readonly, nonatomic) BOOL isHeader;
@property(readonly, nonatomic) BOOL isEstimated;

@end

