//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGLabel, UIButton;

@interface IGLibraryAccessPromptView : UIView
{
    UIView *_contentView;
    UIButton *_instructionButton;
    IGLabel *_titleLabel;
    IGLabel *_explanationLabel;
    IGLabel *_instructionLabel;
}

+ (void)showLibraryDeniedAlertView;
@property(retain, nonatomic) IGLabel *instructionLabel; // @synthesize instructionLabel=_instructionLabel;
@property(retain, nonatomic) IGLabel *explanationLabel; // @synthesize explanationLabel=_explanationLabel;
@property(retain, nonatomic) IGLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *instructionButton; // @synthesize instructionButton=_instructionButton;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)instructionButtonDidTap:(id)arg1;
- (void)attachViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

