//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGStorableObject.h"

#import "IGRelatedItemType.h"

@class CLLocation, NSNumber, NSString;

@interface IGLocation : IGStorableObject <IGRelatedItemType>
{
    CLLocation *_locationCoord;
    NSString *_name;
    NSString *_streetAddress;
    NSNumber *_externalID;
    NSString *_externalIDSource;
    NSString *_externalSource;
    NSString *_foursquareV2ID;
    NSString *_facebookPlacesID;
    NSString *_facebookEventsID;
}

+ (id)unmanagedLocationWithDictionary:(id)arg1;
+ (id)centralizedStore;
+ (id)getRaindropPlacesFromLocations:(id)arg1;
@property(copy) NSString *facebookEventsID; // @synthesize facebookEventsID=_facebookEventsID;
@property(copy) NSString *facebookPlacesID; // @synthesize facebookPlacesID=_facebookPlacesID;
@property(copy) NSString *foursquareV2ID; // @synthesize foursquareV2ID=_foursquareV2ID;
@property(copy) NSString *externalSource; // @synthesize externalSource=_externalSource;
@property(retain) NSString *externalIDSource; // @synthesize externalIDSource=_externalIDSource;
@property(retain) NSNumber *externalID; // @synthesize externalID=_externalID;
@property(copy) NSString *streetAddress; // @synthesize streetAddress=_streetAddress;
@property(copy) NSString *name; // @synthesize name=_name;
@property(retain) CLLocation *locationCoord; // @synthesize locationCoord=_locationCoord;
- (void).cxx_destruct;
- (id)relatedItemType;
- (id)relatedItemURL;
- (id)relatedItemId;
- (id)relatedItemDisplayName;
@property(readonly) unsigned int hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)updateWithDictionary:(id)arg1;
- (void)openInMaps;
- (void)fetchAdditionalInfo;
- (id)dictionaryRepresentation;
@property(readonly) int locationType;
@property(readonly, copy) NSString *detailsString;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) int loggingPlaceSource;
@property(readonly, nonatomic) NSString *loggingId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

