//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFeedNetworkSource.h"

@class IGPostItem, NSArray;

@interface IGMainFeedNetworkSource : IGFeedNetworkSource
{
    NSArray *_followAccountList;
    IGPostItem *_firstPostBeforeFeedReload;
}

@property(retain, nonatomic) IGPostItem *firstPostBeforeFeedReload; // @synthesize firstPostBeforeFeedReload=_firstPostBeforeFeedReload;
@property(readonly, nonatomic) NSArray *followAccountList; // @synthesize followAccountList=_followAccountList;
- (void).cxx_destruct;
- (void)deserializeData;
- (void)onAppNeedsStateSave;
- (void)loadEntriesFromResponse:(id)arg1 clearOut:(BOOL)arg2 rankToken:(id)arg3 secure:(BOOL)arg4;
- (void)loadPromotionBannerInfoFromResponse:(id)arg1;
- (void)onNewItemAvailable:(id)arg1;
- (BOOL)fetchDataWithParameters:(id)arg1;
- (BOOL)fetchData;
- (id)init;
- (void)dealloc;

@end

