//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGMediaManager : NSObject
{
}

+ (void)deleteFeedItem:(id)arg1;
+ (void)fetchPermalinkForFeedItem:(id)arg1 withSuccessHandler:(CDUnknownBlockType)arg2 errorHandler:(CDUnknownBlockType)arg3;
+ (void)showCantEditPostIfFeedItemHasBeenPromoted;
+ (void)fetchPivotsFor:(id)arg1 onController:(id)arg2;
+ (void)showBoostPostForFeedItem:(id)arg1 fromViewController:(id)arg2;
+ (void)unexpireFeedItem:(id)arg1;
+ (void)moreActionSheetForFeedItem:(id)arg1 dismissedWithButtonTitled:(id)arg2 navigationController:(id)arg3;
+ (void)prepareMoreActionSheetForFeedItem:(id)arg1 allowHidingPost:(BOOL)arg2 showTimestamp:(BOOL)arg3;

@end

