//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSInputStream;

@interface IGMultipartComponent : NSObject
{
    NSData *_data;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned int length;
@property(readonly, nonatomic) NSInputStream *inputStream;
- (id)initWithData:(id)arg1;
- (id)initWithString:(id)arg1;

@end

