//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UITableView, UITableViewCell;

@protocol IGNewsDataSourceSection <NSObject>
@property(readonly) unsigned int *numberOfRows;
@property(readonly) NSString *title;
@property(nonatomic) __weak id <IGNewsDataSourceSectionDelegate> delegate;
- (void)setUpTableView:(UITableView *)arg1;
- (void)tableView:(UITableView *)arg1 didSelectRowAtIndex:(unsigned int)arg2;
- (float)tableView:(UITableView *)arg1 heightForRowAtIndex:(unsigned int)arg2;
- (UITableViewCell *)tableView:(UITableView *)arg1 cellForRowAtIndex:(unsigned int)arg2;
@end

