//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGNewsTableViewController.h"

@interface IGNewsFollowingTableViewController : IGNewsTableViewController
{
}

- (id)analyticsModule;
- (void)findFriendsButtonTapped;
- (id)newEmptyFeedView;
- (int)segment;
- (void)onFetchFailed:(id)arg1;
- (void)onStoriesReceived:(id)arg1;
- (void)fetchData;

@end

