//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGPanAnimationView;

@protocol IGPanAnimationViewDelegate
- (void)panAnimationViewDidUpdateCenterImage:(IGPanAnimationView *)arg1;
- (void)panAnimationView:(IGPanAnimationView *)arg1 didPanToLeftBy:(float)arg2;
- (void)panAnimationView:(IGPanAnimationView *)arg1 didPanToRightBy:(float)arg2;
- (void)panAnimationViewDidFinishPanToLeft:(IGPanAnimationView *)arg1;
- (void)panAnimationViewDidFinishPanToRight:(IGPanAnimationView *)arg1;
- (void)panAnimationView:(IGPanAnimationView *)arg1 willCancelPanAnimationWithDuration:(float)arg2;
- (void)panAnimationView:(IGPanAnimationView *)arg1 willFinishPanAnimationWithDuration:(float)arg2;
@end

