//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGImageURLProvider.h"
#import "NSCoding.h"

@class NSArray, NSString;

@interface IGPhoto : NSObject <NSCoding, IGImageURLProvider>
{
    NSString *_mediaID;
    NSArray *_imageVersions;
    struct CGSize _aspectRatio;
}

+ (struct CGSize)imageSizeForImageVersion:(id)arg1;
+ (struct CGSize)aspectRatioForImageVersions:(id)arg1;
+ (id)arrayForImageVersions:(id)arg1;
@property(retain, nonatomic) NSArray *imageVersions; // @synthesize imageVersions=_imageVersions;
@property(nonatomic) struct CGSize aspectRatio; // @synthesize aspectRatio=_aspectRatio;
@property(readonly, copy, nonatomic) NSString *mediaID; // @synthesize mediaID=_mediaID;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)imageIndicesOfAtLeastSize:(struct CGSize)arg1 scale:(float)arg2;
- (int)imageIndexOfAtLeastWidth:(float)arg1 scale:(float)arg2;
- (int)originalAspectRatioImageIndexNearestToRequestedDimension:(float)arg1 imageInfoKey:(id)arg2;
- (int)originalAspectRatioImageIndexNearestToHeight:(float)arg1 scale:(float)arg2;
- (int)originalAspectRatioImageIndexNearestToWidth:(float)arg1 scale:(float)arg2;
- (id)imageURLForImageIndex:(int)arg1;
- (id)thumbnailURLForAspectFillSize:(struct CGSize)arg1 option:(int)arg2;
- (id)imageURLOfAtLeastWidth:(float)arg1 scale:(float)arg2;
- (id)imageURLForHeight:(float)arg1 option:(int)arg2 scale:(float)arg3;
- (id)imageURLForWidth:(float)arg1 option:(int)arg2 scale:(float)arg3;
- (id)imageURLForWidth:(float)arg1 option:(int)arg2;
- (id)imageURLForWidth:(float)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly) unsigned int hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithImageVersions:(id)arg1 mediaID:(id)arg2 originalMediaSize:(struct CGSize)arg3;
- (id)initWithImageVersions:(id)arg1;
- (id)initWithFeedItemDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

