//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBSDKAccessToken, IGProfilePictureHelper, UIImage;

@protocol IGProfilePictureHelperDelegate <NSObject>

@optional
- (void)profilePictureHelperDidGetNewFacebookAccessToken:(FBSDKAccessToken *)arg1;
- (void)profilePictureHelperDidFailDownloadingProfilePicture:(IGProfilePictureHelper *)arg1;
- (void)profilePictureHelperWillStartDownloadingProfilePicture:(IGProfilePictureHelper *)arg1;
- (void)profilePictureHelperRemovePictureButtonTapped:(IGProfilePictureHelper *)arg1;
- (void)profilePictureHelper:(IGProfilePictureHelper *)arg1 willPerformAction:(int)arg2;
- (BOOL)profilePictureHelperShouldShowRemovePicture:(IGProfilePictureHelper *)arg1;
- (void)profilePictureHelper:(IGProfilePictureHelper *)arg1 didFinishDownloadingProfilePicture:(UIImage *)arg2 fromOption:(int)arg3;
@end

