//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGCustomViewController.h"
#import "UIViewControllerTransitioningDelegate.h"

@class FXBlurView, IGActionGroupView, NSArray, NSString, UIImageView, UIView;

@interface IGPreviewViewController : UIViewController <UIViewControllerTransitioningDelegate, IGCustomViewController>
{
    BOOL _isShowingArrowView;
    BOOL _isShowingActionView;
    BOOL _isActionViewShownBeforePanning;
    BOOL _stopProcessingPanEvents;
    BOOL _pendingDismiss;
    BOOL _viewDidAppearObserved;
    UIViewController *_contentViewControler;
    FXBlurView *_blurView;
    UIView *_movableView;
    UIView *_maskedView;
    IGActionGroupView *_actionView;
    UIImageView *_arrowView;
    float _panToHideOffset;
    NSArray *_actionItems;
    struct CGPoint _panningOrigin;
    struct CGPoint _panningViewOrigin;
}

@property(nonatomic) BOOL viewDidAppearObserved; // @synthesize viewDidAppearObserved=_viewDidAppearObserved;
@property(nonatomic) BOOL pendingDismiss; // @synthesize pendingDismiss=_pendingDismiss;
@property(nonatomic) BOOL stopProcessingPanEvents; // @synthesize stopProcessingPanEvents=_stopProcessingPanEvents;
@property(retain, nonatomic) NSArray *actionItems; // @synthesize actionItems=_actionItems;
@property(nonatomic) BOOL isActionViewShownBeforePanning; // @synthesize isActionViewShownBeforePanning=_isActionViewShownBeforePanning;
@property(nonatomic) BOOL isShowingActionView; // @synthesize isShowingActionView=_isShowingActionView;
@property(nonatomic) BOOL isShowingArrowView; // @synthesize isShowingArrowView=_isShowingArrowView;
@property(nonatomic) float panToHideOffset; // @synthesize panToHideOffset=_panToHideOffset;
@property(nonatomic) struct CGPoint panningViewOrigin; // @synthesize panningViewOrigin=_panningViewOrigin;
@property(nonatomic) struct CGPoint panningOrigin; // @synthesize panningOrigin=_panningOrigin;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) IGActionGroupView *actionView; // @synthesize actionView=_actionView;
@property(retain, nonatomic) UIView *maskedView; // @synthesize maskedView=_maskedView;
@property(retain, nonatomic) UIView *movableView; // @synthesize movableView=_movableView;
@property(retain, nonatomic) FXBlurView *blurView; // @synthesize blurView=_blurView;
@property(readonly, nonatomic) UIViewController *contentViewControler; // @synthesize contentViewControler=_contentViewControler;
- (void).cxx_destruct;
- (id)analyticsModule;
- (id)ig_keyViewControllers;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (struct CGPoint)inertialTranslationForTranslation:(struct CGPoint)arg1;
- (void)showActionView;
- (void)hideActionView;
- (void)restoreViewsToRestingPositionAnimatedCompletion:(CDUnknownBlockType)arg1;
- (void)panViewsWithMovableViewOrigin:(struct CGPoint)arg1 translation:(struct CGPoint)arg2;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (void)didTakeAction:(id)arg1;
- (float)restingMovableViewY;
- (float)restingActionViewY;
- (void)didTap:(id)arg1;
- (void)didPan:(id)arg1;
- (void)didCancelPanFromExternalGestureRecognizer:(id)arg1;
- (void)didEndPanFromExternalGestureRecognizer:(id)arg1;
- (void)didPanFromExternalGestureRecognizer:(id)arg1;
- (void)didStartPanFromExternalGestureRecognizer:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithContentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

