//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class IGDirectContent, IGDirectThreadLayoutInvalidationContext, NSArray, NSDictionary, NSIndexPath;

@interface IGPublicThreadLayout : UICollectionViewLayout
{
    NSArray *_allContent;
    NSArray *_nextThreadAllContent;
    NSIndexPath *_nextThreadTransitionViewIndexPath;
    NSArray *_seenUsers;
    IGDirectThreadLayoutInvalidationContext *_igInvalidationContext;
    NSDictionary *_itemAttributes;
    NSDictionary *_headerAttributes;
    NSDictionary *_footerAttributes;
    IGDirectContent *_currentlyExpandedContent;
    float _collectionViewWidth;
    NSDictionary *_nextThreadItemAttributes;
    NSDictionary *_nextThreadTransitionViewAttributes;
    struct CGSize _calculatedCollectionViewContentSize;
}

+ (Class)invalidationContextClass;
@property(retain, nonatomic) NSDictionary *nextThreadTransitionViewAttributes; // @synthesize nextThreadTransitionViewAttributes=_nextThreadTransitionViewAttributes;
@property(retain, nonatomic) NSDictionary *nextThreadItemAttributes; // @synthesize nextThreadItemAttributes=_nextThreadItemAttributes;
@property(nonatomic) float collectionViewWidth; // @synthesize collectionViewWidth=_collectionViewWidth;
@property(retain, nonatomic) IGDirectContent *currentlyExpandedContent; // @synthesize currentlyExpandedContent=_currentlyExpandedContent;
@property(nonatomic) struct CGSize calculatedCollectionViewContentSize; // @synthesize calculatedCollectionViewContentSize=_calculatedCollectionViewContentSize;
@property(retain, nonatomic) NSDictionary *footerAttributes; // @synthesize footerAttributes=_footerAttributes;
@property(retain, nonatomic) NSDictionary *headerAttributes; // @synthesize headerAttributes=_headerAttributes;
@property(retain, nonatomic) NSDictionary *itemAttributes; // @synthesize itemAttributes=_itemAttributes;
@property(retain, nonatomic) IGDirectThreadLayoutInvalidationContext *igInvalidationContext; // @synthesize igInvalidationContext=_igInvalidationContext;
@property(retain, nonatomic) NSArray *seenUsers; // @synthesize seenUsers=_seenUsers;
@property(retain, nonatomic) NSIndexPath *nextThreadTransitionViewIndexPath; // @synthesize nextThreadTransitionViewIndexPath=_nextThreadTransitionViewIndexPath;
@property(retain, nonatomic) NSArray *nextThreadAllContent; // @synthesize nextThreadAllContent=_nextThreadAllContent;
@property(nonatomic) __weak NSArray *allContent; // @synthesize allContent=_allContent;
- (void).cxx_destruct;
- (BOOL)updateSeenUsers:(id)arg1;
- (id)currentThreadAndNextThreadTransitionAttributes;
- (id)sortIndexPath:(id)arg1;
- (struct CGSize)sizeForContent:(id)arg1 prevContent:(id)arg2 withViewWidth:(float)arg3;
- (float)calculateNextThreadTransitionViewAttributesWithYOffset:(float)arg1 width:(float)arg2;
- (float)calculateItemAttributes:(float)arg1 currentHeight:(float)arg2 contents:(id)arg3 map:(id *)arg4 section:(int)arg5;
- (float)calculateContentSize:(id)arg1 updateAttributes:(id)arg2 withBaseTopToBottom:(float)arg3;
- (void)calculateAndCacheAttributes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (void)invalidateLayoutWithContext:(id)arg1;
- (void)prepareLayout;

@end

