//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface IGPushHelper : NSObject
{
    NSMutableArray *_cachedFeedItems;
    BOOL _needToUpdatePushToken;
    BOOL _freshAppInstall;
}

+ (unsigned int)switchUsersIfNecessary:(id)arg1;
+ (id)sharedPushHelper;
@property(nonatomic, getter=isFreshAppInstall) BOOL freshAppInstall; // @synthesize freshAppInstall=_freshAppInstall;
- (void).cxx_destruct;
- (void)performNavigationTaskForAction:(id)arg1 userInfo:(id)arg2;
- (void)handleActionWithIdentifier:(id)arg1 forRemoteNotification:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)clearFeedItemCache;
- (void)showNotificationBarWithUserInfo:(id)arg1 actionBlock:(CDUnknownBlockType)arg2;
- (void)handleForegroundPushNotification:(id)arg1;
- (void)handleBackgroundPushNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handlePushNotification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)registerForPushWithToken:(id)arg1;
- (BOOL)shouldAllowBackgroundFetchFeed;
- (BOOL)eligibleForPushMegaphone;
- (BOOL)shouldShowInboxPushMegaphone;
- (BOOL)shouldShowActivityPushMegaphone;
- (id)convertTokenToDeviceID:(id)arg1;
- (BOOL)isTimeToPromptForPushPermissions;
- (void)onBackground:(id)arg1;
- (void)markAsNeedToUpdatePushToken;
- (id)stringForAppState:(int)arg1;
- (void)logPushNogification:(id)arg1 applicationState:(int)arg2;
- (BOOL)appHasPushPermissions;
- (BOOL)appHasAskedSystemForPushPermissions;
- (void)startPushRegistrationWithForce:(BOOL)arg1;
- (id)categoriesForPushNotifications;
- (id)init;
- (void)dealloc;

@end

