//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGDirectKeyboardTextViewControllerDelegate.h"
#import "IGQuickCamViewControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class IGAlertBar, IGDirectKeyboardTextViewController, IGDirectThread, IGKeyboardInputManager, IGPublicThreadCellFactory, IGPublicThreadLayout, IGPublicThreadNextThreadCell, IGQuickCamViewController2, IGUser, NSArray, NSNumber, NSString, UICollectionView;

@interface IGPublicThreadViewController : IGViewController <IGDirectKeyboardTextViewControllerDelegate, UICollectionViewDelegate, UICollectionViewDataSource, IGQuickCamViewControllerDelegate>
{
    BOOL _nextThreadIsLoadedOnScreen;
    BOOL _isLoadingForFirstTime;
    BOOL _shouldScrollToBottomAfterContentSizeChange;
    BOOL _shouldAnimateScrollingToBottom;
    BOOL _loadingPreviousMessages;
    int _state;
    id <IGPublicThreadViewControllerDelegate> _delegate;
    IGUser *_threadViewer;
    IGDirectThread *_thread;
    NSString *_threadID;
    NSArray *_allContent;
    IGDirectThread *_nextThread;
    IGPublicThreadNextThreadCell *_nextThreadViewCell;
    UICollectionView *_collectionView;
    IGPublicThreadCellFactory *_cellFactory;
    IGPublicThreadLayout *_layout;
    IGKeyboardInputManager *_keyboardInputManager;
    IGDirectKeyboardTextViewController *_textViewController;
    IGAlertBar *_loadingAlertBar;
    NSNumber *_distanceToBottomToKeep;
    IGQuickCamViewController2 *_quickCamViewController;
}

@property(retain, nonatomic) IGQuickCamViewController2 *quickCamViewController; // @synthesize quickCamViewController=_quickCamViewController;
@property(nonatomic) BOOL loadingPreviousMessages; // @synthesize loadingPreviousMessages=_loadingPreviousMessages;
@property(nonatomic) BOOL shouldAnimateScrollingToBottom; // @synthesize shouldAnimateScrollingToBottom=_shouldAnimateScrollingToBottom;
@property(nonatomic) BOOL shouldScrollToBottomAfterContentSizeChange; // @synthesize shouldScrollToBottomAfterContentSizeChange=_shouldScrollToBottomAfterContentSizeChange;
@property(retain, nonatomic) NSNumber *distanceToBottomToKeep; // @synthesize distanceToBottomToKeep=_distanceToBottomToKeep;
@property(nonatomic) BOOL isLoadingForFirstTime; // @synthesize isLoadingForFirstTime=_isLoadingForFirstTime;
@property(retain, nonatomic) IGAlertBar *loadingAlertBar; // @synthesize loadingAlertBar=_loadingAlertBar;
@property(retain, nonatomic) IGDirectKeyboardTextViewController *textViewController; // @synthesize textViewController=_textViewController;
@property(retain, nonatomic) IGKeyboardInputManager *keyboardInputManager; // @synthesize keyboardInputManager=_keyboardInputManager;
@property(retain, nonatomic) IGPublicThreadLayout *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) IGPublicThreadCellFactory *cellFactory; // @synthesize cellFactory=_cellFactory;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) BOOL nextThreadIsLoadedOnScreen; // @synthesize nextThreadIsLoadedOnScreen=_nextThreadIsLoadedOnScreen;
@property(retain, nonatomic) IGPublicThreadNextThreadCell *nextThreadViewCell; // @synthesize nextThreadViewCell=_nextThreadViewCell;
@property(retain, nonatomic) IGDirectThread *nextThread; // @synthesize nextThread=_nextThread;
@property(retain, nonatomic) NSArray *allContent; // @synthesize allContent=_allContent;
@property(retain, nonatomic) NSString *threadID; // @synthesize threadID=_threadID;
@property(retain, nonatomic) IGDirectThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) IGUser *threadViewer; // @synthesize threadViewer=_threadViewer;
@property(nonatomic) __weak id <IGPublicThreadViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int state; // @synthesize state=_state;
- (void).cxx_destruct;
- (id)analyticsModule;
- (void)showQuickCam:(BOOL)arg1;
- (void)quickCamViewController:(id)arg1 didPickAsset:(id)arg2;
- (void)quickCamViewController:(id)arg1 didEnterState:(int)arg2;
- (void)quickCamViewController:(id)arg1 didClickDisabledAsset:(id)arg2;
- (void)quickCamViewControllerLibraryDidLoad:(id)arg1;
- (void)directContentUploadCell:(id)arg1 wantsRetryForContent:(id)arg2;
- (void)directContentUploadCell:(id)arg1 wantsDeleteForContent:(id)arg2;
- (void)keyboardTextViewControllerDidTapCamera:(id)arg1;
- (void)keyboardTextViewController:(id)arg1 didTapSendWithText:(id)arg2;
- (void)keyboardTextViewController:(id)arg1 textViewDidBeginEditing:(id)arg2;
- (void)keyboardTextViewControllerDidTapCameraBackButton:(id)arg1;
- (void)keyboardTextViewControllerDidTapLike:(id)arg1;
- (void)keyboardTextViewController:(id)arg1 didChangeContentHeightToHeight:(float)arg2;
- (void)keyboardTextViewControllerDidDismissCamera:(id)arg1;
- (void)keyboardTextViewController:(id)arg1 textViewDidEndEditing:(id)arg2;
- (void)keyboardTextViewController:(id)arg1 textViewWillBeginEditing:(id)arg2;
- (void)loadPreviousMessages;
- (void)collectionViewDidScrollFromYPosition:(float)arg1 toYPosition:(float)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)currentThreadTitle;
- (void)updateTitle;
- (void)updateThreadAndTitleWithThreadID:(id)arg1;
- (void)renderThreadWithThreadID:(id)arg1 andCompletionHandler:(CDUnknownBlockType)arg2 keepVisiblePosition:(BOOL)arg3 forceUpdate:(BOOL)arg4;
- (void)loadThreadWithID:(id)arg1 performNetworkRefresh:(BOOL)arg2 shouldAnimateScrollingToBottom:(BOOL)arg3 showLoadingIndicator:(BOOL)arg4;
- (void)updateFromSend;
- (void)hideLoadingIndicator;
- (void)showLoadingIndicator;
- (BOOL)prefersTabBarHidden;
- (void)handleSendWithSuccess:(BOOL)arg1 andResponse:(id)arg2;
- (void)updateCollectionViewInsets:(struct UIEdgeInsets)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (float)offSetYWhenScrolledToBottom;
- (void)scrollToBottomAnimated:(BOOL)arg1;
- (float)nextThreadViewHeight;
- (void)updateCollectionViewLayoutWithNextThread;
- (void)replaceThreadContentWithNextThread;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (id)createLayout;
- (void)setupTextViewController;
- (void)setupCollectionView;
- (void)setNextThreadID:(id)arg1;
- (BOOL)shouldShowKeyboard;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)initializeThreadComponents;
- (id)initWithThreadID:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

