//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGAssetPlayerViewDelegate.h"
#import "IGAudioSampleBufferDelegate.h"
#import "IGCaptureManagerDelegate.h"
#import "IGCropViewUserInteractionDelegate.h"
#import "IGGridViewControllerDelegate.h"
#import "IGQuickCamCaptureButtonDelegate.h"
#import "IGSelectAlbumDelegate.h"
#import "IGVideoSampleBufferDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class IGAssetPlayerView, IGCameraAccessPromptView, IGCameraGuideView, IGCaptureManager, IGCircularProgressView, IGCropView, IGEmptyLibraryView, IGGridViewController, IGLabel, IGLibraryAccessPromptView, IGQuickCamCaptureButton, IGQuickCamLibraryButton, IGSampleBuffer, IGSelectAlbumController, IGStabilizationSampler, IGTapButton, IGVideoRecorder, NSObject<OS_dispatch_queue>, NSString, UIImageView, UILabel, UIView;

@interface IGQuickCamViewController : UIViewController <UIGestureRecognizerDelegate, UINavigationControllerDelegate, IGQuickCamCaptureButtonDelegate, IGAssetPlayerViewDelegate, IGCropViewUserInteractionDelegate, IGGridViewControllerDelegate, IGSelectAlbumDelegate, IGCaptureManagerDelegate, IGVideoSampleBufferDelegate, IGAudioSampleBufferDelegate>
{
    BOOL _visible;
    BOOL _gridViewIsLoaded;
    BOOL _isBackgrounded;
    BOOL _hasStartedCapture;
    BOOL _hasReceivedAudioFrames;
    BOOL _hasShownAudioPermissionsDeniedAlertView;
    BOOL _hasCaptureButtonConfirmed;
    int _state;
    id <IGSelectAlbumDelegate> _albumControllerDelegate;
    id <IGQuickCamViewControllerDelegate> _delegate;
    id <IGQuickCamOutputAsset> _outputAsset;
    UIView *_contentView;
    IGGridViewController *_gridViewController;
    IGQuickCamLibraryButton *_libraryButton;
    IGQuickCamCaptureButton *_captureButton;
    IGTapButton *_switchCameraButton;
    IGCropView *_cropView;
    IGCameraGuideView *_guideView;
    UIImageView *_videoCoverFrameImageView;
    IGCircularProgressView *_progressView;
    UIView *_loadingOverlayView;
    UIImageView *_loadingThumbnailView;
    id <IGQuickCamInputAsset> _previewAsset;
    IGLabel *_unsupportedVideoLabel;
    IGEmptyLibraryView *_noMediaView;
    IGAssetPlayerView *_playerView;
    int _fullSizeRequestID;
    unsigned int _contentEditingInputRequestID;
    id <IGQuickCamInputAsset> _inputAsset;
    IGSelectAlbumController *_selectAlbumVC;
    id _selectedAsset;
    UIView *_previewView;
    UIImageView *_focusRing;
    IGCaptureManager *_captureManager;
    IGVideoRecorder *_videoRecorder;
    NSObject<OS_dispatch_queue> *_imageBufferQueue;
    IGStabilizationSampler *_stabilizer;
    IGSampleBuffer *_imageBufferData;
    IGCameraAccessPromptView *_cameraPermissionDeniedView;
    IGLibraryAccessPromptView *_libraryAccessDeniedView;
    UILabel *_tapToRecordLabel;
    int _videoTakenCount;
    float _maxVideoDuration;
}

@property(nonatomic) BOOL hasCaptureButtonConfirmed; // @synthesize hasCaptureButtonConfirmed=_hasCaptureButtonConfirmed;
@property(nonatomic) float maxVideoDuration; // @synthesize maxVideoDuration=_maxVideoDuration;
@property(nonatomic) int videoTakenCount; // @synthesize videoTakenCount=_videoTakenCount;
@property(retain, nonatomic) UILabel *tapToRecordLabel; // @synthesize tapToRecordLabel=_tapToRecordLabel;
@property(nonatomic) BOOL hasShownAudioPermissionsDeniedAlertView; // @synthesize hasShownAudioPermissionsDeniedAlertView=_hasShownAudioPermissionsDeniedAlertView;
@property BOOL hasReceivedAudioFrames; // @synthesize hasReceivedAudioFrames=_hasReceivedAudioFrames;
@property(nonatomic) BOOL hasStartedCapture; // @synthesize hasStartedCapture=_hasStartedCapture;
@property(retain, nonatomic) IGLibraryAccessPromptView *libraryAccessDeniedView; // @synthesize libraryAccessDeniedView=_libraryAccessDeniedView;
@property(retain, nonatomic) IGCameraAccessPromptView *cameraPermissionDeniedView; // @synthesize cameraPermissionDeniedView=_cameraPermissionDeniedView;
@property(retain) IGSampleBuffer *imageBufferData; // @synthesize imageBufferData=_imageBufferData;
@property(retain, nonatomic) IGStabilizationSampler *stabilizer; // @synthesize stabilizer=_stabilizer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *imageBufferQueue; // @synthesize imageBufferQueue=_imageBufferQueue;
@property(retain, nonatomic) IGVideoRecorder *videoRecorder; // @synthesize videoRecorder=_videoRecorder;
@property(retain, nonatomic) IGCaptureManager *captureManager; // @synthesize captureManager=_captureManager;
@property(retain, nonatomic) UIImageView *focusRing; // @synthesize focusRing=_focusRing;
@property(retain, nonatomic) UIView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) id selectedAsset; // @synthesize selectedAsset=_selectedAsset;
@property(retain, nonatomic) IGSelectAlbumController *selectAlbumVC; // @synthesize selectAlbumVC=_selectAlbumVC;
@property(nonatomic) BOOL isBackgrounded; // @synthesize isBackgrounded=_isBackgrounded;
@property(retain, nonatomic) id <IGQuickCamInputAsset> inputAsset; // @synthesize inputAsset=_inputAsset;
@property(nonatomic) unsigned int contentEditingInputRequestID; // @synthesize contentEditingInputRequestID=_contentEditingInputRequestID;
@property(nonatomic) int fullSizeRequestID; // @synthesize fullSizeRequestID=_fullSizeRequestID;
@property(retain, nonatomic) IGAssetPlayerView *playerView; // @synthesize playerView=_playerView;
@property(retain, nonatomic) IGEmptyLibraryView *noMediaView; // @synthesize noMediaView=_noMediaView;
@property(retain, nonatomic) IGLabel *unsupportedVideoLabel; // @synthesize unsupportedVideoLabel=_unsupportedVideoLabel;
@property(retain, nonatomic) id <IGQuickCamInputAsset> previewAsset; // @synthesize previewAsset=_previewAsset;
@property(retain, nonatomic) UIImageView *loadingThumbnailView; // @synthesize loadingThumbnailView=_loadingThumbnailView;
@property(retain, nonatomic) UIView *loadingOverlayView; // @synthesize loadingOverlayView=_loadingOverlayView;
@property(retain, nonatomic) IGCircularProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIImageView *videoCoverFrameImageView; // @synthesize videoCoverFrameImageView=_videoCoverFrameImageView;
@property(retain, nonatomic) IGCameraGuideView *guideView; // @synthesize guideView=_guideView;
@property(retain, nonatomic) IGCropView *cropView; // @synthesize cropView=_cropView;
@property(retain, nonatomic) IGTapButton *switchCameraButton; // @synthesize switchCameraButton=_switchCameraButton;
@property(retain, nonatomic) IGQuickCamCaptureButton *captureButton; // @synthesize captureButton=_captureButton;
@property(retain, nonatomic) IGQuickCamLibraryButton *libraryButton; // @synthesize libraryButton=_libraryButton;
@property(retain, nonatomic) IGGridViewController *gridViewController; // @synthesize gridViewController=_gridViewController;
@property(nonatomic) BOOL gridViewIsLoaded; // @synthesize gridViewIsLoaded=_gridViewIsLoaded;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) id <IGQuickCamOutputAsset> outputAsset; // @synthesize outputAsset=_outputAsset;
@property(nonatomic) __weak id <IGQuickCamViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <IGSelectAlbumDelegate> albumControllerDelegate; // @synthesize albumControllerDelegate=_albumControllerDelegate;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic, getter=isVisible) BOOL visible; // @synthesize visible=_visible;
- (void).cxx_destruct;
- (void)stopRecording;
- (void)cancelRecording;
- (void)stopRecordingOnCaptureQueue:(BOOL)arg1;
- (void)startRecording;
- (void)updateStabilizationSampler;
- (void)captureSessionWillTakePhoto;
- (void)captureSessionNeedsResume:(BOOL)arg1;
- (void)captureSessionDidCaptureAudioBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)captureSessionDidDropAudioBuffer;
- (void)captureSessionDidCaptureVideoBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)captureSessionDidDropVideoBuffer;
- (BOOL)cameraIsReady;
- (void)captureDeviceDidSatisfyFocusRequest;
- (void)focusTap:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)setViewColorToDefault;
- (void)stopVideoPlayer;
- (void)hideLoadingViews;
- (void)confirmInputAsset:(id)arg1;
- (void)updateVideoSize;
- (void)onSwitchCamerasButtonTapped;
- (void)captureButtonDidEndRecording;
- (void)captureButtonDidBeginRecording;
- (void)captureButtonDidTakePicture;
- (struct CGRect)cropRectForOutputAsset;
- (void)finalizeOutputAsset;
- (void)confirmAssetIfPossible;
- (void)captureButtonDidConfirm;
- (id)finalizeImage:(id)arg1 cropRect:(struct CGRect)arg2;
- (void)assetPlayerView:(id)arg1 didPlayToTime:(CDStruct_1b6d18a9)arg2;
- (void)assetPlayerViewPlayStateDidChange:(id)arg1;
- (void)assetPlayerViewAssetLoaded:(id)arg1;
- (void)cropViewUserInteractionDidEnd:(id)arg1;
- (void)cropViewUserInteractionDidBegin:(id)arg1;
- (id)currentAlbumTitle;
- (void)setAlbum:(id)arg1 fromCollectionFetchResult:(id)arg2;
- (void)setCropAsset:(id)arg1;
- (void)selectFirstAsset;
- (void)showSelectAlbumController:(BOOL)arg1;
- (void)selectAlbumControllerDidSelectAlbum:(id)arg1 fetchResult:(id)arg2;
- (void)gridViewController:(id)arg1 firstAssetDidChange:(id)arg2;
- (void)gridViewControllerLibraryDidLoad:(id)arg1;
- (void)gridViewController:(id)arg1 didChangeAlbumTitle:(id)arg2;
- (void)gridViewController:(id)arg1 selectedAssetWasRemoved:(id)arg2;
- (void)gridViewControllerSelectedAlbumWasRemoved:(id)arg1;
- (void)gridViewController:(id)arg1 didSelectAsset:(id)arg2 atIndexPath:(id)arg3;
- (void)gridViewController:(id)arg1 didClickDisabledAsset:(id)arg2;
- (id)inputLibraryAssetForFrameworkAsset:(id)arg1;
- (void)internalSetState:(int)arg1;
- (void)showLibraryAccessDeniedView;
- (void)showCameraPermissionDeniedView;
- (void)showAudioPermissionsDeniedAlertView;
- (void)attemptChangeToLibraryState;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)startCapture;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)startLibrary;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

