//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGQuickCamMediaHelper : NSObject
{
}

+ (BOOL)shouldDisplayFilterNux;
+ (void)layoutNuxWithLabel:(id)arg1 parentView:(id)arg2;
+ (id)imageWithImage:(id)arg1 scaledToSize:(struct CGSize)arg2;
+ (void)stateAnimationBlock:(CDUnknownBlockType)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
+ (void)rotateAnimationOnView:(id)arg1;
+ (void)addShadowForView:(id)arg1;
+ (void)addShadowRect:(struct CGRect)arg1 toView:(id)arg2;
+ (BOOL)CGFloat:(float)arg1 equalToCGFloat:(float)arg2 withEpsilon:(float)arg3;
+ (BOOL)CGRect:(struct CGRect)arg1 equalToCGRect:(struct CGRect)arg2 withEpsilon:(float)arg3;
+ (struct CGRect)cropRectForOutputAsset:(id)arg1 withInputAsset:(id)arg2 fromCropView:(id)arg3;
+ (void)setupOutputAsset:(id)arg1 withInputAsset:(id)arg2 cropRect:(struct CGRect)arg3;
+ (id)cropImage:(id)arg1 withRect:(struct CGRect)arg2;

@end

