//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBaseStruct.h"

@class NSNumber, NSString;

@interface IGRaindropSearchAbandonEvent : TBaseStruct
{
    NSNumber *__thrift_isTypeahead;
    NSNumber *__thrift_nullState;
    NSString *__thrift_searchQueryText;
}

- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)toDict;
- (id)description;
- (void)write:(id)arg1;
- (id)initWithIsTypeahead:(id)arg1 nullState:(id)arg2 searchQueryText:(id)arg3;
- (id)init;

@end

