//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGConfirmPhoneManagerDelegate.h"
#import "IGCoreTextLinkHandler.h"
#import "UIGestureRecognizerDelegate.h"

@class FBSDKAccessToken, IGConfirmPhoneManager, IGRetroRegistrationSMSVerificationView, NSString, UITapGestureRecognizer;

@interface IGRetroRegistrationSMSVerificationViewController : UIViewController <IGCoreTextLinkHandler, UIGestureRecognizerDelegate, IGConfirmPhoneManagerDelegate>
{
    BOOL _submitting;
    id <IGRetroRegistrationSMSVerificationViewControllerDelegate> _delegate;
    IGRetroRegistrationSMSVerificationView *_smsVerificationView;
    NSString *_username;
    NSString *_obfuscatedPhoneNumber;
    int _smsResendDelay;
    NSString *_twoFactorIdentifier;
    IGConfirmPhoneManager *_confirmPhoneManager;
    UITapGestureRecognizer *_tapGesture;
    FBSDKAccessToken *_facebookAccessToken;
}

@property(nonatomic) BOOL submitting; // @synthesize submitting=_submitting;
@property(retain, nonatomic) FBSDKAccessToken *facebookAccessToken; // @synthesize facebookAccessToken=_facebookAccessToken;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(readonly, nonatomic) IGConfirmPhoneManager *confirmPhoneManager; // @synthesize confirmPhoneManager=_confirmPhoneManager;
@property(copy, nonatomic) NSString *twoFactorIdentifier; // @synthesize twoFactorIdentifier=_twoFactorIdentifier;
@property(readonly, nonatomic) int smsResendDelay; // @synthesize smsResendDelay=_smsResendDelay;
@property(readonly, copy, nonatomic) NSString *obfuscatedPhoneNumber; // @synthesize obfuscatedPhoneNumber=_obfuscatedPhoneNumber;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) IGRetroRegistrationSMSVerificationView *smsVerificationView; // @synthesize smsVerificationView=_smsVerificationView;
@property(nonatomic) __weak id <IGRetroRegistrationSMSVerificationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)confirmPhoneManager:(id)arg1 didFireWithSecondsLeft:(int)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)removeIndicatorViewFromLoginButton:(id)arg1;
- (id)createIndicatorViewAndAddToLoginButton;
- (void)loginCompletionHandlerForUser:(id)arg1 error:(id)arg2 statusCode:(int)arg3;
- (void)loginWithTwoFactorIdentifier;
- (void)updateRobocallFooterWithSecondsLeft:(int)arg1;
- (void)handleLoginErrors:(id)arg1;
- (void)backButtonTapped;
- (void)confirmCodeButtonPressed;
- (void)robocallTwoFactorCode;
- (void)resendTwoFactorSMS;
- (void)keyboardWillDisappear;
- (void)keyboardWillShow:(id)arg1;
- (BOOL)prefersStatusBarHidden;
- (BOOL)prefersNavigationBarHidden;
- (void)setUsername:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithTwoFactorInfo:(id)arg1 facebookAccessToken:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

