//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class UILabel;

@interface IGRelatedItemCollectionViewHeader : UICollectionReusableView
{
    UILabel *_textLabel;
}

+ (id)headerIdentifier;
@property(readonly, nonatomic) __weak UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)configureWithTitle:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

