//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGRegistrationWaterfall : NSObject
{
}

+ (id)flowNameForRetroRegistrationStep:(int)arg1;
+ (id)stepNameForRetroRegistrationStep:(int)arg1;
+ (id)logPhoneRegistrationEvent:(id)arg1 forPhoneNumber:(id)arg2;
+ (id)logRetroRegistrationStepEvent:(id)arg1 forStep:(int)arg2;
+ (id)logEndLoggedOutSessionEvent:(id)arg1 isFBLinkFlow:(BOOL)arg2;
+ (id)logLogInEvent:(id)arg1 logInToken:(id)arg2;
+ (id)logUsernameSuggestionEvent:(id)arg1 username:(id)arg2 index:(unsigned int)arg3;
+ (id)logUsernameEvent:(id)arg1 username:(id)arg2;
+ (id)logLandingScreenEvent:(id)arg1;
+ (id)logEvent:(id)arg1;

@end

