//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGShareModeDropdownView, NSString;

@protocol IGShareModeDropdownViewDataSource <NSObject>
- (NSString *)dropdownView:(IGShareModeDropdownView *)arg1 titleForItemForIndex:(int)arg2;
- (int)numberOfItemsInDropdownView:(IGShareModeDropdownView *)arg1;
@end

