//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

#import "IGRageShakeViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class IGShakeWindowEventLogger, NSString;

@interface IGShakeWindow : UIWindow <IGRageShakeViewControllerDelegate, UIAlertViewDelegate>
{
    BOOL _isReporting;
    IGShakeWindowEventLogger *_logger;
    double _motionStart;
}

- (void).cxx_destruct;
- (void)didDismissRageShakeViewController:(id)arg1 didSendReport:(BOOL)arg2;
- (void)showTestSettings;
- (void)showRaindropEvents;
- (void)showAnalyticsEvents;
- (void)presentReportThankYouAlert;
- (void)reportBug;
- (void)reportCrash;
- (id)windowDescriptionData;
- (id)screenshotData;
- (void)showBugReporterForType:(int)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)promptBugReporter;
- (void)onFlexTapGesture:(id)arg1;
- (void)motionBegan:(int)arg1 withEvent:(id)arg2;
- (void)motionEnded:(int)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

