//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView;

@interface IGShareModeDropdownCell : UITableViewCell
{
    BOOL _checked;
    UIImageView *_checkmarkImageView;
}

+ (id)reuseIdentifier;
@property(readonly, nonatomic) UIImageView *checkmarkImageView; // @synthesize checkmarkImageView=_checkmarkImageView;
@property(nonatomic, getter=isChecked) BOOL checked; // @synthesize checked=_checked;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

