//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGSimilarAccountsLogger : NSObject
{
}

+ (void)logSimilarAccountsEvent:(id)arg1 chainedUserPK:(id)arg2 targetUserPK:(id)arg3 source:(unsigned int)arg4 position:(unsigned int)arg5;

@end

