//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGConfirmPhoneManagerDelegate.h"
#import "IGCoreTextLinkHandler.h"

@class IGConfirmPhoneManager, IGCoreTextView, IGStringStyle, NSString, UIView;

@interface IGSMSConfirmationController : NSObject <IGCoreTextLinkHandler, IGConfirmPhoneManagerDelegate>
{
    id <IGSMSConfirmationControllerDelegate> _delegate;
    NSString *_phoneNumber;
    int _smsResendDelay;
    IGConfirmPhoneManager *_confirmPhoneManager;
    UIView *_coreTextViewContainer;
    IGCoreTextView *_resendCodeCoreTextView;
    IGCoreTextView *_changePhoneNumberCoreTextView;
    IGStringStyle *_stringStyle;
    float _coreTextViewWidth;
    float _coreTextViewHeight;
}

@property(nonatomic) float coreTextViewHeight; // @synthesize coreTextViewHeight=_coreTextViewHeight;
@property(nonatomic) float coreTextViewWidth; // @synthesize coreTextViewWidth=_coreTextViewWidth;
@property(retain, nonatomic) IGStringStyle *stringStyle; // @synthesize stringStyle=_stringStyle;
@property(retain, nonatomic) IGCoreTextView *changePhoneNumberCoreTextView; // @synthesize changePhoneNumberCoreTextView=_changePhoneNumberCoreTextView;
@property(retain, nonatomic) IGCoreTextView *resendCodeCoreTextView; // @synthesize resendCodeCoreTextView=_resendCodeCoreTextView;
@property(retain, nonatomic) UIView *coreTextViewContainer; // @synthesize coreTextViewContainer=_coreTextViewContainer;
@property(retain, nonatomic) IGConfirmPhoneManager *confirmPhoneManager; // @synthesize confirmPhoneManager=_confirmPhoneManager;
@property(readonly, nonatomic) int smsResendDelay; // @synthesize smsResendDelay=_smsResendDelay;
@property(readonly, copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(nonatomic) __weak id <IGSMSConfirmationControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)confirmPhoneManager:(id)arg1 didFireWithSecondsLeft:(int)arg2;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (id)getResendFooterWithFontSize:(float)arg1;
- (id)getRobocallStyledStringForSecondsRemaining:(int)arg1 withFontSize:(float)arg2;
- (void)updateRobocallFooterWithSecondsLeft:(int)arg1;
- (void)setupIGCoreTextViewsWithFontSize:(float)arg1;
- (void)setupIGCoreTextViewsWithMaximumFontSize:(float)arg1;
- (void)continueTimer;
- (void)invalidateTimer;
- (void)sizeCoreTextViewContainerToFit;
- (void)configureWithSize:(struct CGSize)arg1;
- (id)initWithPhoneNumber:(id)arg1 confirmPhoneSettings:(id)arg2 stringStyle:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

