//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIImage, UIImageView, UILabel;

@interface IGSwitchUsersBaseCell : UITableViewCell
{
    UIImageView *_cellImageView;
    NSString *_text;
    UILabel *_cellLabel;
    UIImage *_image;
}

+ (id)labelFont;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UILabel *cellLabel; // @synthesize cellLabel=_cellLabel;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImageView *cellImageView; // @synthesize cellImageView=_cellImageView;
- (void).cxx_destruct;
- (struct CGSize)labelSizeForLabel:(id)arg1 cellWidth:(float)arg2;
- (struct CGRect)labelFrameForLabel:(id)arg1;
- (struct CGRect)imageViewFrame;
- (void)layoutSubviews;
- (id)initWithImage:(id)arg1 text:(id)arg2 reuseIdentifier:(id)arg3;

@end

