//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUIPerfLogResult;

@protocol IGUIPerfLoggable <NSObject>
- (void)allEventsLoggedWithResult:(IGUIPerfLogResult *)arg1;
- (unsigned int)lastLogEvent;
- (BOOL)shouldLogEvent:(unsigned int)arg1;
@end

