//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "FBWebViewDelegate.h"
#import "IGUnifiedWebViewToolbarDelegate.h"

@class IGTableViewInsetInfoView, IGUnifiedWebViewScrollViewToolbarCoordinator, IGUnifiedWebViewToolbar, IGViewControllerTitleDetailTitleView, NSString, NSURLRequest, UIBarButtonItem, UIProgressView, UIView<FBWebView>;

@interface IGUnifiedWebViewController : IGViewController <IGUnifiedWebViewToolbarDelegate, FBWebViewDelegate>
{
    BOOL _shareButtonVisible;
    BOOL _navigationToolBarEnabled;
    id <IGUnifiedWebViewControllerBrowsingLifeCycleDelegate> _browsingDelegate;
    id <IGUnifiedWebViewControllerShareDelegate> _shareDelegate;
    id <IGUnifiedWebViewControllerWebViewLoggingDelegate> _webViewLoggingDelegate;
    id <IGUnifiedWebViewControllerSharingLoggingDelegate> _sharingLoggingDelegate;
    unsigned int _titleViewType;
    unsigned int _titleTextType;
    NSURLRequest *_urlRequest;
    IGViewControllerTitleDetailTitleView *_titleView;
    UIView<FBWebView> *_webView;
    UIProgressView *_progressView;
    IGUnifiedWebViewToolbar *_navigationToolBar;
    IGUnifiedWebViewScrollViewToolbarCoordinator *_scrollViewToolbarCoordinator;
    UIBarButtonItem *_shareBarButtonItem;
    IGTableViewInsetInfoView *_infoView;
}

@property(retain, nonatomic) IGTableViewInsetInfoView *infoView; // @synthesize infoView=_infoView;
@property(retain, nonatomic) UIBarButtonItem *shareBarButtonItem; // @synthesize shareBarButtonItem=_shareBarButtonItem;
@property(retain, nonatomic) IGUnifiedWebViewScrollViewToolbarCoordinator *scrollViewToolbarCoordinator; // @synthesize scrollViewToolbarCoordinator=_scrollViewToolbarCoordinator;
@property(retain, nonatomic) IGUnifiedWebViewToolbar *navigationToolBar; // @synthesize navigationToolBar=_navigationToolBar;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIView<FBWebView> *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) IGViewControllerTitleDetailTitleView *titleView; // @synthesize titleView=_titleView;
@property(readonly, copy, nonatomic) NSURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(readonly, nonatomic) BOOL navigationToolBarEnabled; // @synthesize navigationToolBarEnabled=_navigationToolBarEnabled;
@property(readonly, nonatomic) BOOL shareButtonVisible; // @synthesize shareButtonVisible=_shareButtonVisible;
@property(readonly, nonatomic) unsigned int titleTextType; // @synthesize titleTextType=_titleTextType;
@property(readonly, nonatomic) unsigned int titleViewType; // @synthesize titleViewType=_titleViewType;
@property(nonatomic) __weak id <IGUnifiedWebViewControllerSharingLoggingDelegate> sharingLoggingDelegate; // @synthesize sharingLoggingDelegate=_sharingLoggingDelegate;
@property(nonatomic) __weak id <IGUnifiedWebViewControllerWebViewLoggingDelegate> webViewLoggingDelegate; // @synthesize webViewLoggingDelegate=_webViewLoggingDelegate;
@property(nonatomic) __weak id <IGUnifiedWebViewControllerShareDelegate> shareDelegate; // @synthesize shareDelegate=_shareDelegate;
@property(nonatomic) __weak id <IGUnifiedWebViewControllerBrowsingLifeCycleDelegate> browsingDelegate; // @synthesize browsingDelegate=_browsingDelegate;
- (void).cxx_destruct;
- (void)setNavigationBarTitle:(id)arg1 forURL:(id)arg2;
- (void)webViewToolbarForwardButtonTapped:(id)arg1;
- (void)webViewToolbarBackButtonTapped:(id)arg1;
- (void)webView:(id)arg1 progressChanged:(double)arg2;
- (void)webView:(id)arg1 didFailNavigationRequest:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigationRequest:(id)arg2;
- (void)webView:(id)arg1 didStartNavigationRequest:(id)arg2;
- (BOOL)webView:(id)arg1 shouldStartNavigationRequest:(id)arg2 navigationType:(int)arg3 sourceFrame:(id)arg4 targetFrame:(id)arg5;
- (int)preferredStatusBarStyle;
- (BOOL)automaticallyAdjustsScrollViewInsets;
- (void)setTitle:(id)arg1;
- (void)networkErrorInfoViewRefreshButtonWasTapped:(id)arg1;
- (void)shareBarButtonTapped:(id)arg1;
- (void)presentNetworkErrorInfoView;
- (void)presentToolbar;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithURLRequest:(id)arg1 titleViewType:(unsigned int)arg2 titleTextType:(unsigned int)arg3 shareButtonVisible:(BOOL)arg4 navigationToolBarEnabled:(BOOL)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

