//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"

@class IGNonCurrentUserDefaults, IGUser, NSString;

@interface IGUserSession : NSObject <IGUserSessionClearableObject>
{
    struct unordered_map<Class<IGUserSessionObject>, std::__1::shared_future<Value>, std::__1::hash<Class<IGUserSessionObject>>, std::__1::equal_to<Class<IGUserSessionObject>>, std::__1::allocator<std::__1::pair<const Class<IGUserSessionObject>, std::__1::shared_future<Value>>>> _objectMap;
    struct Mutex _objectsLock;
    IGUser *_user;
    IGNonCurrentUserDefaults *_nonCurrentUserDefaults;
    unsigned int _backgroundTask;
}

+ (void)clearForUserPK:(id)arg1;
+ (id)classesWhereWillSwitchUsersShouldRunInForeground;
+ (id)inMemoryStoresThatCacheUserData;
+ (id)storesThatCacheUserData;
@property(nonatomic) unsigned int backgroundTask; // @synthesize backgroundTask=_backgroundTask;
@property(retain, nonatomic) IGNonCurrentUserDefaults *nonCurrentUserDefaults; // @synthesize nonCurrentUserDefaults=_nonCurrentUserDefaults;
@property(retain, nonatomic) IGUser *user; // @synthesize user=_user;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initForTesting;
- (void)archiveInBackground;
- (void)willLogOutPrivate:(id)arg1;
- (void)willLogOut;
- (void)willSwitchUsers;
- (id)valueForClass:(Class)arg1 withInitializer:(CDUnknownBlockType)arg2;
- (id)initWithUser:(id)arg1;
- (void)dealloc;
- (id)albumCreationManager;
- (id)albumSeenStateStore;
- (id)autocompleteHashtagsStore;
- (id)autocompletePlacesStore;
- (id)autocompleteUsersStore;
- (id)blendedSearchRecentItemsOrderStore;
- (id)directRecipientManager;
- (id)directThreadStore;
- (id)flaggedCommentLedger;
- (id)frequentHiddenSearchItemStore;
- (id)inAppBadgeManager;
- (id)mediaUploadManager;
- (id)publicThreadStore;
- (id)realtimeClient;
- (id)recentHiddenSearchItemStore;
- (id)serviceManager;
- (id)userExperimentSet;
- (id)videoRenderQueue;
- (id)webViewProcessPoolContainer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

