//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserInTagDisplayView, IGUsertagView;

@protocol IGUserInTagDisplayDelegate <NSObject>
- (void)userInTagView:(IGUserInTagDisplayView *)arg1 didTapOnTagView:(IGUsertagView *)arg2;
@end

