//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGPlainTableViewCell.h"

@class NSString, UIImageView, UILabel, UIView;

@interface IGUserListLikersHeaderCell : IGPlainTableViewCell
{
    NSString *_likesString;
    UILabel *_likeCountLabel;
    UIView *_likeTitleView;
    UIImageView *_heartImageView;
    UILabel *_likeTitleLabel;
}

+ (float)cellHeight;
@property(readonly, nonatomic) UILabel *likeTitleLabel; // @synthesize likeTitleLabel=_likeTitleLabel;
@property(readonly, nonatomic) UIImageView *heartImageView; // @synthesize heartImageView=_heartImageView;
@property(readonly, nonatomic) UIView *likeTitleView; // @synthesize likeTitleView=_likeTitleView;
@property(readonly, nonatomic) UILabel *likeCountLabel; // @synthesize likeCountLabel=_likeCountLabel;
@property(retain, nonatomic) NSString *likesString; // @synthesize likesString=_likesString;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1;

@end

