//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGMediaMetadataProtocol.h"

@class IGVideoComposition, NSArray, NSString;

@interface IGVideoMetadata : NSObject <IGMediaMetadataProtocol>
{
    BOOL _isAudioMuted;
    NSString *_rawVideoLocationString;
    IGVideoComposition *_videoComposition;
    int _posterFrameIndex;
    float _videoTimeLength;
    int _videoSourceType;
    NSArray *_clipsMetadata;
}

@property(nonatomic) BOOL isAudioMuted; // @synthesize isAudioMuted=_isAudioMuted;
@property(retain, nonatomic) NSArray *clipsMetadata; // @synthesize clipsMetadata=_clipsMetadata;
@property(nonatomic) int videoSourceType; // @synthesize videoSourceType=_videoSourceType;
@property(nonatomic) float videoTimeLength; // @synthesize videoTimeLength=_videoTimeLength;
@property(nonatomic) int posterFrameIndex; // @synthesize posterFrameIndex=_posterFrameIndex;
@property(readonly, copy, nonatomic) IGVideoComposition *videoComposition; // @synthesize videoComposition=_videoComposition;
@property(copy, nonatomic) NSString *rawVideoLocationString; // @synthesize rawVideoLocationString=_rawVideoLocationString;
- (void).cxx_destruct;
- (id)sharingInfo;
- (void)prepareToShare;
- (unsigned int)calculateTrimType;
- (void)updateVideoTimeLengthWithVideo:(id)arg1;
- (void)updateClipsMetadataWithVideo:(id)arg1;
- (BOOL)isBoomerang;
- (BOOL)isFastVideo;
- (void)updateWithVideo:(id)arg1;
- (void)updateIsAudioMuted:(BOOL)arg1;
- (void)updateKeyPosition:(float)arg1;
- (id)initWithVideo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

