//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString;

@interface IGViewControllerBlockBasedAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    CDUnknownBlockType _animation;
    float _duration;
}

@property(readonly, nonatomic) float duration; // @synthesize duration=_duration;
@property(readonly, copy, nonatomic) CDUnknownBlockType animation; // @synthesize animation=_animation;
- (void).cxx_destruct;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)initWithDuration:(float)arg1 animation:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

