//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@protocol IGVideoProxyProtocol <NSObject>
+ (id)sharedProxy;
@property(nonatomic) __weak id <IGVideoProxyDelegate> delegate;
- (void)removeWhiteListedURL:(NSURL *)arg1;
- (void)addWhiteListedURL:(NSURL *)arg1;
- (void)handlePlaybackErrorForURL:(NSURL *)arg1;
- (void)cancelVideoRequestForURL:(NSURL *)arg1;
- (void)startVideoRequestForURL:(NSURL *)arg1;
- (NSURL *)proxyURLForURL:(NSURL *)arg1;
@end

