//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"
#import "IGVideoRendererDelegate.h"

@class NSMutableArray, NSString;

@interface IGVideoRenderQueue : NSObject <IGVideoRendererDelegate, IGUserSessionClearableObject>
{
    NSMutableArray *_renderQueue;
    NSMutableArray *_hibernaculum;
}

+ (void)clearForUserPK:(id)arg1;
+ (id)sharedRenderQueue;
@property(retain, nonatomic) NSMutableArray *hibernaculum; // @synthesize hibernaculum=_hibernaculum;
@property(retain, nonatomic) NSMutableArray *renderQueue; // @synthesize renderQueue=_renderQueue;
- (void).cxx_destruct;
- (void)willLogOut;
- (void)willSwitchUsers;
- (void)cancelAllRenderings;
- (void)onAppForeground;
- (void)onAppBackground;
- (id)rendererWithMetadata:(id)arg1;
- (void)saveRenderWithMetadataWhenDone:(id)arg1;
- (void)saveRenderToPhotoLibrary:(id)arg1;
- (void)cancelRenderWithMetadata:(id)arg1;
- (void)videoRenderer:(id)arg1 didFailWithError:(id)arg2;
- (void)videoRenderer:(id)arg1 didFinishRenderingVideoToURL:(id)arg2 videoSize:(struct CGSize)arg3 metadata:(id)arg4 canceled:(BOOL)arg5;
- (void)removeRendererFromRenderQueue:(id)arg1;
- (id)createRendererWithVideo:(id)arg1;
- (void)renderVideo:(id)arg1 withMetadata:(id)arg2 retryCount:(unsigned int)arg3;
- (void)renderVideo:(id)arg1 withMetadata:(id)arg2;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

