//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (Truncation)
- (int)lengthOfCollapsedStringWithWidth:(float)arg1 maximumUntruncatedNumberOfLines:(int)arg2 truncatedToNumberOfLines:(int)arg3 truncationToken:(id)arg4 trimmingCharacterSet:(id)arg5;
@end

