//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface RCTImageSource : NSObject
{
    BOOL _packagerAsset;
    NSURL *_imageURL;
    float _scale;
    struct CGSize _size;
}

@property(nonatomic) BOOL packagerAsset; // @synthesize packagerAsset=_packagerAsset;
@property(readonly, nonatomic) float scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)imageSourceWithSize:(struct CGSize)arg1 scale:(float)arg2;
- (id)initWithURL:(id)arg1 size:(struct CGSize)arg2 scale:(float)arg3;

@end

