//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RCTMethodArgument : NSObject
{
    BOOL _unused;
    NSString *_type;
    unsigned int _nullability;
}

@property(readonly, nonatomic) BOOL unused; // @synthesize unused=_unused;
@property(readonly, nonatomic) unsigned int nullability; // @synthesize nullability=_nullability;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(id)arg1 nullability:(unsigned int)arg2 unused:(BOOL)arg3;

@end

