//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPTAnimationPeriod.h"

@interface _CPTAnimationNSDecimalPeriod : CPTAnimationPeriod
{
}

- (id)tweenedValueForProgress:(float)arg1;
- (BOOL)canStartWithValueFromObject:(id)arg1 propertyGetter:(SEL)arg2;
- (void)setStartValueFromObject:(id)arg1 propertyGetter:(SEL)arg2;

@end

