//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPTConstraints.h"

@interface _CPTConstraintsFixed : CPTConstraints
{
    BOOL isFixedToLower;
    float offset;
}

@property(nonatomic) BOOL isFixedToLower; // @synthesize isFixedToLower;
@property(nonatomic) float offset; // @synthesize offset;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (Class)classForCoder;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (float)positionForLowerBound:(float)arg1 upperBound:(float)arg2;
- (BOOL)isEqualToConstraint:(id)arg1;
- (id)initWithUpperOffset:(float)arg1;
- (id)initWithLowerOffset:(float)arg1;

@end

