//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface CPTConstraints : NSObject <NSCoding, NSCopying>
{
}

+ (id)constraintWithRelativeOffset:(float)arg1;
+ (id)constraintWithUpperOffset:(float)arg1;
+ (id)constraintWithLowerOffset:(float)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithRelativeOffset:(float)arg1;
- (id)initWithUpperOffset:(float)arg1;
- (id)initWithLowerOffset:(float)arg1;
- (float)positionForLowerBound:(float)arg1 upperBound:(float)arg2;
- (BOOL)isEqualToConstraint:(id)arg1;

@end

