//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class CPTFill, CPTPlotRange;

@interface CPTLimitBand : NSObject <NSCoding, NSCopying>
{
    CPTPlotRange *range;
    CPTFill *fill;
}

+ (id)limitBandWithRange:(id)arg1 fill:(id)arg2;
@property(retain, nonatomic) CPTFill *fill; // @synthesize fill;
@property(retain, nonatomic) CPTPlotRange *range; // @synthesize range;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithRange:(id)arg1 fill:(id)arg2;

@end

