//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class CPTPlot, CPTTextStyle, NSAttributedString, NSString;

@interface CPTLegendEntry : NSObject <NSCoding>
{
    CPTPlot *plot;
    unsigned int index;
    unsigned int row;
    unsigned int column;
    CPTTextStyle *textStyle;
}

@property(retain, nonatomic) CPTTextStyle *textStyle; // @synthesize textStyle;
@property(nonatomic) unsigned int column; // @synthesize column;
@property(nonatomic) unsigned int row; // @synthesize row;
@property(nonatomic) unsigned int index; // @synthesize index;
@property(nonatomic) __weak CPTPlot *plot; // @synthesize plot;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGSize titleSize; // @dynamic titleSize;
@property(readonly, nonatomic) NSAttributedString *attributedTitle;
@property(readonly, nonatomic) NSString *title; // @dynamic title;
- (void)drawTitleInRect:(struct CGRect)arg1 inContext:(struct CGContext *)arg2 scale:(float)arg3;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

