//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CPTResponder.h"
#import "NSCoding.h"

@class CPTGraph, NSMutableDictionary, NSString;

@interface CPTPlotSpace : NSObject <CPTResponder, NSCoding>
{
    BOOL allowsUserInteraction;
    BOOL isDragging;
    id <NSCopying><NSCoding><NSObject> identifier;
    CPTGraph *graph;
    id <CPTPlotSpaceDelegate> delegate;
    NSMutableDictionary *categoryNames;
}

@property(retain, nonatomic) NSMutableDictionary *categoryNames; // @synthesize categoryNames;
@property(nonatomic) __weak id <CPTPlotSpaceDelegate> delegate; // @synthesize delegate;
@property(nonatomic) __weak CPTGraph *graph; // @synthesize graph;
@property(nonatomic) BOOL isDragging; // @synthesize isDragging;
@property(nonatomic) BOOL allowsUserInteraction; // @synthesize allowsUserInteraction;
@property(copy, nonatomic) id <NSCopying><NSCoding><NSObject> identifier; // @synthesize identifier;
- (void).cxx_destruct;
- (BOOL)pointingDeviceCancelledEvent:(struct UIEvent *)arg1;
- (BOOL)pointingDeviceDraggedEvent:(struct UIEvent *)arg1 atPoint:(struct CGPoint)arg2;
- (BOOL)pointingDeviceUpEvent:(struct UIEvent *)arg1 atPoint:(struct CGPoint)arg2;
- (BOOL)pointingDeviceDownEvent:(struct UIEvent *)arg1 atPoint:(struct CGPoint)arg2;
- (unsigned int)indexOfCategory:(id)arg1 forCoordinate:(int)arg2;
- (id)categoryForCoordinate:(int)arg1 atIndex:(unsigned int)arg2;
- (id)categoriesForCoordinate:(int)arg1;
- (void)removeAllCategories;
- (void)setCategories:(id)arg1 forCoordinate:(int)arg2;
- (void)insertCategory:(id)arg1 forCoordinate:(int)arg2 atIndex:(unsigned int)arg3;
- (void)removeCategory:(id)arg1 forCoordinate:(int)arg2;
- (void)addCategory:(id)arg1 forCoordinate:(int)arg2;
- (id)orderedSetForCoordinate:(int)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)debugQuickLookObject;
- (void)scaleBy:(float)arg1 aboutPoint:(struct CGPoint)arg2;
- (void)scaleToFitPlots:(id)arg1 forCoordinate:(int)arg2;
- (void)scaleToFitPlots:(id)arg1;
- (int)scaleTypeForCoordinate:(int)arg1;
- (void)setScaleType:(int)arg1 forCoordinate:(int)arg2;
- (id)plotRangeForCoordinate:(int)arg1;
- (void)setPlotRange:(id)arg1 forCoordinate:(int)arg2;
- (void)doublePrecisionPlotPoint:(double *)arg1 numberOfCoordinates:(unsigned int)arg2 forEvent:(struct UIEvent *)arg3;
- (void)plotPoint:(CDStruct_6ece915e *)arg1 numberOfCoordinates:(unsigned int)arg2 forEvent:(struct UIEvent *)arg3;
- (id)plotPointForEvent:(struct UIEvent *)arg1;
- (struct CGPoint)plotAreaViewPointForEvent:(struct UIEvent *)arg1;
- (void)doublePrecisionPlotPoint:(double *)arg1 numberOfCoordinates:(unsigned int)arg2 forPlotAreaViewPoint:(struct CGPoint)arg3;
- (void)plotPoint:(CDStruct_6ece915e *)arg1 numberOfCoordinates:(unsigned int)arg2 forPlotAreaViewPoint:(struct CGPoint)arg3;
- (id)plotPointForPlotAreaViewPoint:(struct CGPoint)arg1;
- (struct CGPoint)plotAreaViewPointForDoublePrecisionPlotPoint:(double *)arg1 numberOfCoordinates:(unsigned int)arg2;
- (struct CGPoint)plotAreaViewPointForPlotPoint:(CDStruct_6ece915e *)arg1 numberOfCoordinates:(unsigned int)arg2;
- (struct CGPoint)plotAreaViewPointForPlotPoint:(id)arg1;
@property(readonly, nonatomic) unsigned int numberOfCoordinates; // @dynamic numberOfCoordinates;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

