//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString, NSURL, NSURLRequest, UIView<FBWebView>;

@protocol FBWebViewDelegate <NSObject>

@optional
- (void)webView:(UIView<FBWebView> *)arg1 loadingStateChanged:(BOOL)arg2;
- (void)webView:(UIView<FBWebView> *)arg1 progressChanged:(double)arg2;
- (void)webViewSelectionChanged:(NSString *)arg1;
- (void)webViewWillPopNavigationState:(UIView<FBWebView> *)arg1;
- (void)webViewWillPushNavigationState:(UIView<FBWebView> *)arg1;
- (void)webViewBlockingResourcesLoaded:(UIView<FBWebView> *)arg1;
- (void)webView:(UIView<FBWebView> *)arg1 didFinishNavigationRequest:(NSURLRequest *)arg2;
- (void)webView:(UIView<FBWebView> *)arg1 didFailNavigationRequest:(NSURLRequest *)arg2 withError:(NSError *)arg3;
- (void)webView:(UIView<FBWebView> *)arg1 didStartNavigationRequest:(NSURLRequest *)arg2;
- (BOOL)webView:(UIView<FBWebView> *)arg1 shouldStartNavigationRequest:(NSURLRequest *)arg2 navigationType:(int)arg3 sourceFrame:(id <FBWebViewFrame>)arg4 targetFrame:(id <FBWebViewFrame>)arg5;
- (void)webView:(UIView<FBWebView> *)arg1 navigationHistoryChangedCanGoBack:(BOOL)arg2 canGoForward:(BOOL)arg3;
- (void)webView:(UIView<FBWebView> *)arg1 URLChanged:(NSURL *)arg2;
- (void)webView:(UIView<FBWebView> *)arg1 titleChanged:(NSString *)arg2;
@end

