//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFeedViewController_DEPRECATED.h"

#import "IGAdRatingWebViewCellContinuationDelegate.h"

@interface IGAdRatingFeedViewController : IGFeedViewController_DEPRECATED <IGAdRatingWebViewCellContinuationDelegate>
{
}

- (BOOL)webViewCell:(id)arg1 shouldStartLoadWithURL:(id)arg2;
- (id)analyticsModule;
- (BOOL)useNewVisibilityTracking;
- (id)collectionViewController:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)addFooterView:(id)arg1 withRank:(int)arg2 animated:(BOOL)arg3;
- (id)collectionViewController:(id)arg1 viewForSupplementaryViewOfKind:(id)arg2 forItemAtIndexPath:(id)arg3;
- (BOOL)feedViewLayout:(id)arg1 shouldHideHeaderForSection:(unsigned int)arg2 withObjects:(id)arg3;
- (id)init;

@end

