//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIView;

@interface IGAlbumTabBarEntryCell : UITableViewCell
{
    UIView *_ig_imageView;
}

+ (id)reuseIdentifier;
+ (struct CGSize)defaultImageSize;
@property(retain, nonatomic) UIView *ig_imageView; // @synthesize ig_imageView=_ig_imageView;
- (void).cxx_destruct;
- (void)configureWithItem:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

