//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGAlertViewButton : NSObject
{
    int _type;
    NSString *_text;
}

+ (id)buttonTypes;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) int type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithButtonType:(int)arg1 text:(id)arg2;

@end

