//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGMediaRequestDelegate.h"
#import "UISearchDisplayDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDictionary, NSString, UIImage, UISearchDisplayController, UITableView;

@interface IGAnalyticsViewController : IGViewController <UITableViewDelegate, UITableViewDataSource, IGMediaRequestDelegate, UISearchDisplayDelegate>
{
    UITableView *_tableView;
    UISearchDisplayController *_searchController;
    NSArray *_logLines;
    NSArray *_filteredLogLines;
    NSDictionary *_displayedEvent;
    UIImage *_solidGreenImage;
    UIImage *_solidGreenImageRounded;
    id <IGAnalyticsViewControllerDelegate> _delegate;
    unsigned int _type;
}

@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) __weak id <IGAnalyticsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onTableViewLongPress:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)configureForAnalyticsEventWithDict:(id)arg1 cell:(id)arg2;
- (void)_linkToMediaCell:(id)arg1 withEventDict:(id)arg2;
- (void)_linkToUserCell:(id)arg1 withEventDict:(id)arg2 pk:(id)arg3;
- (void)_updateCell:(id)arg1 withEventDict:(id)arg2;
- (void)configureForRaindropWithDict:(id)arg1 cell:(id)arg2;
- (void)mediaRequest:(id)arg1 didLoadMediaWithData:(id)arg2 forURL:(id)arg3;
- (void)doneButtonTapped:(id)arg1;
- (void)clearAnalyticsEventsTapped:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithLogDicts:(id)arg1 type:(unsigned int)arg2;
- (id)initWithLogDicts:(id)arg1;
- (id)_imageWithColor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

