//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class IGUser;

@interface IGAuthUserData : NSObject <NSCoding>
{
    IGUser *_user;
    double _timeLastAccessed;
}

@property(retain, nonatomic) IGUser *user; // @synthesize user=_user;
@property(nonatomic) double timeLastAccessed; // @synthesize timeLastAccessed=_timeLastAccessed;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUser:(id)arg1 timeLastAccessed:(double)arg2;

@end

