//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPMusicPlayerController;

@interface IGAudioSession : NSObject
{
    BOOL _overrideMuteSwitch;
    MPMusicPlayerController *_musicPlayerController;
    float _previousVolume;
}

+ (id)sharedInstance;
@property(nonatomic) float previousVolume; // @synthesize previousVolume=_previousVolume;
@property(readonly, nonatomic) MPMusicPlayerController *musicPlayerController; // @synthesize musicPlayerController=_musicPlayerController;
@property(nonatomic) BOOL overrideMuteSwitch; // @synthesize overrideMuteSwitch=_overrideMuteSwitch;
- (void).cxx_destruct;
- (void)audioSessionRouteChange:(id)arg1;
- (void)volumeChanged:(id)arg1;
- (void)willResignActive;
- (void)didBecomeActive;
- (void)activateRecordingSession:(BOOL)arg1;
- (void)activateRecordingSession;
- (void)activatePlaybackSession;
- (id)init;
- (void)dealloc;

@end

