//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGBusinessConversionHelper : NSObject
{
}

+ (void)showBusinessConversionCompletionAlert;
+ (id)headerViewWithTitle:(id)arg1 subtitle:(id)arg2 width:(float)arg3;
+ (BOOL)phoneNumberIsValid:(id)arg1;
+ (BOOL)validatePageInfo:(id)arg1 withError:(id *)arg2;
+ (id)textButtonWithTitle:(id)arg1;
+ (void)switchBackToPersonalAccountFromViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (id)backStyleButton;
+ (id)refreshButton;
+ (id)dismissStyleButton;
+ (id)conversionBaseInputParams;
+ (void)sendRequestWithQueryID:(id)arg1 pageInfo:(id)arg2 includeAllFields:(BOOL)arg3 includePageID:(BOOL)arg4 parser:(id)arg5 completion:(CDUnknownBlockType)arg6;
+ (void)finishConversionWithPageInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)updateProfileWithPageInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (unsigned int)contactPreferenceForString:(id)arg1;
+ (id)stringForContactPreference:(unsigned int)arg1;
+ (id)needContactMethodErrorString;
+ (id)invalidPhoneErrorString;
+ (id)invalidEmailErrorString;
+ (id)cityPlaceholderText;
+ (id)addressPlaceholderText;
+ (id)directMessageField;
+ (id)addressField;
+ (id)emailField;
+ (id)phoneNumberFieldWithCountrySelector;
+ (id)basicPhoneNumberField;

@end

