//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGAutocompleteControllerTextInput.h"
#import "UITextViewDelegate.h"

@class IGGradientView, IGProfilePictureImageView, IGSimpleFrameButton, NSString, UIImageView, UITextView, UIView;

@interface IGCaptionCell : UICollectionViewCell <UITextViewDelegate, IGAutocompleteControllerTextInput>
{
    BOOL _shouldShowProfileInCaption;
    UIImageView *_thumbnailView;
    id <IGCaptionCellDelegate> _delegate;
    IGProfilePictureImageView *_profilePictureImageView;
    IGSimpleFrameButton *_photoFrameView;
    UITextView *_textView;
    UIView *_bottomLine;
    IGGradientView *_topGradientView;
    IGGradientView *_bottomGradientView;
    float _offsetY;
}

+ (float)height;
@property(nonatomic) float offsetY; // @synthesize offsetY=_offsetY;
@property(nonatomic) BOOL shouldShowProfileInCaption; // @synthesize shouldShowProfileInCaption=_shouldShowProfileInCaption;
@property(retain, nonatomic) IGGradientView *bottomGradientView; // @synthesize bottomGradientView=_bottomGradientView;
@property(retain, nonatomic) IGGradientView *topGradientView; // @synthesize topGradientView=_topGradientView;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) IGSimpleFrameButton *photoFrameView; // @synthesize photoFrameView=_photoFrameView;
@property(retain, nonatomic) IGProfilePictureImageView *profilePictureImageView; // @synthesize profilePictureImageView=_profilePictureImageView;
@property(nonatomic) __weak id <IGCaptionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void).cxx_destruct;
- (int)offsetFromPosition:(id)arg1 toPosition:(id)arg2;
- (void)setSelectedTextRange:(id)arg1;
- (id)closestPositionToPoint:(struct CGPoint)arg1;
- (id)textRangeFromPosition:(id)arg1 toPosition:(id)arg2;
- (id)positionFromPosition:(id)arg1 offset:(int)arg2;
- (id)beginningOfDocument;
- (struct _NSRange)selectedRange;
- (void)layoutSubviews;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)onMediaTap;
- (void)setMediaThumbnailView:(id)arg1 aspectRatio:(float)arg2;
- (struct CGRect)textViewRectWithPhotoFrame:(struct CGRect)arg1;
- (struct CGRect)photoFrameRectForAspectRatio:(float)arg1;
- (struct CGRect)profilePictureRect;
- (void)selectAll;
@property(nonatomic) int keyboardType;
- (void)setThumbnailViewHidden:(BOOL)arg1;
@property(retain, nonatomic) NSString *text;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)isFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(nonatomic) int autocapitalizationType;
@property(nonatomic) int autocorrectionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(readonly) unsigned int hash;
@property(nonatomic) int keyboardAppearance;
@property(nonatomic) int returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(nonatomic) int spellCheckingType;
@property(readonly) Class superclass;

@end

