//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFeedItemVideoCell.h"

@class CALayer, IGChannelOverlayView;

@interface IGChannelVideoCell : IGFeedItemVideoCell
{
    IGChannelOverlayView *_overlayView;
    CALayer *_touchDownLayer;
}

@property(readonly, nonatomic) CALayer *touchDownLayer; // @synthesize touchDownLayer=_touchDownLayer;
@property(readonly, nonatomic) IGChannelOverlayView *overlayView; // @synthesize overlayView=_overlayView;
- (void).cxx_destruct;
- (void)configureWithChannel:(id)arg1 playerDelegate:(id)arg2;
- (void)prepareForReuse;
- (void)feedItemVideoViewDidPauseWithEmptyBuffer:(id)arg1;
- (void)feedItemVideoViewDidPlay:(id)arg1;
- (void)feedItemVideoViewDidLoadImage:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)layoutSubviews;
- (void)configureVideoView;
- (void)setupTouchDownLayer;
- (void)setupOverlayViewWithFrame:(struct CGRect)arg1;
- (void)setupSubviewsWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

