//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGTapButton.h"

@class NSString;

@interface IGChevronTitleButton : IGTapButton
{
    BOOL _isOpen;
}

+ (id)button;
@property(nonatomic) BOOL isOpen; // @synthesize isOpen=_isOpen;
@property(retain, nonatomic) NSString *title;
- (void)setIsOpen:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;

@end

