//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray, NSString;

@interface IGChangeLanguageViewController : UITableViewController
{
    NSArray *_locales;
    NSString *_currentLanguage;
}

@property(readonly, nonatomic) NSString *currentLanguage; // @synthesize currentLanguage=_currentLanguage;
@property(readonly, nonatomic) NSArray *locales; // @synthesize locales=_locales;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)isCurrentLocale:(id)arg1;
- (id)localeNameForIndexPath:(id)arg1;
- (id)localeForIndexPath:(id)arg1;
- (void)relaunchApp;
- (void)changeLocale:(id)arg1;
- (void)viewDidLoad;
- (id)init;

@end

