//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGCountdownTimerDelegate.h"

@class IGConfirmPhoneSettings, IGCountdownTimer, NSTimer;

@interface IGConfirmPhoneManager : NSObject <IGCountdownTimerDelegate>
{
    BOOL _resendSMSDelayPassed;
    IGConfirmPhoneSettings *_confirmPhoneSettings;
    id <IGConfirmPhoneManagerDelegate> _delegate;
    NSTimer *_resendSMSTimer;
    IGCountdownTimer *_robocallTimer;
    int _numSMSResends;
}

@property(nonatomic) BOOL resendSMSDelayPassed; // @synthesize resendSMSDelayPassed=_resendSMSDelayPassed;
@property(nonatomic) int numSMSResends; // @synthesize numSMSResends=_numSMSResends;
@property(retain, nonatomic) IGCountdownTimer *robocallTimer; // @synthesize robocallTimer=_robocallTimer;
@property(retain, nonatomic) NSTimer *resendSMSTimer; // @synthesize resendSMSTimer=_resendSMSTimer;
@property(nonatomic) __weak id <IGConfirmPhoneManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGConfirmPhoneSettings *confirmPhoneSettings; // @synthesize confirmPhoneSettings=_confirmPhoneSettings;
- (void).cxx_destruct;
- (void)timer:(id)arg1 didFireWithSecondsLeft:(int)arg2;
- (void)resendTimerFired:(id)arg1;
- (void)resetResendTimer;
- (void)invalidateResendTimer;
- (BOOL)canResendSMS;
- (void)updateManagerAfterResendingCode;
- (void)continueActiveTimer;
- (void)invalidateActiveTimer;
- (id)initWithConfirmPhoneSettings:(id)arg1;

@end

