//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGCommentItemController, IGCommentModel, IGUser, NSURL;

@protocol IGCommentItemDelegate <NSObject>
- (void)commentController:(IGCommentItemController *)arg1 didReportComment:(IGCommentModel *)arg2;
- (void)commentController:(IGCommentItemController *)arg1 didDeleteComment:(IGCommentModel *)arg2;
- (void)commentController:(IGCommentItemController *)arg1 didTapURL:(NSURL *)arg2;
- (void)commentController:(IGCommentItemController *)arg1 didTapReplyForUser:(IGUser *)arg2;
@end

