//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGCommentReshareBannerDelegate.h"

@class IGCommentReshareBanner, NSSet, NSString, UIImageView, UIView, UIView<IGCommentTextViewWithReshareProtocol>;

@interface IGCommentReshareUIManager : NSObject <IGCommentReshareBannerDelegate>
{
    id <IGCommentReshareUIManagerDelegate> _delegate;
    UIView *_view;
    UIView *_commentView;
    UIView *_autoCompletionView;
    UIView<IGCommentTextViewWithReshareProtocol> *_textView;
    IGCommentReshareBanner *_reshareBanner;
    UIImageView *_carrot;
    UIView *_commentsOverlay;
}

@property(readonly, nonatomic) UIView *commentsOverlay; // @synthesize commentsOverlay=_commentsOverlay;
@property(readonly, nonatomic) UIImageView *carrot; // @synthesize carrot=_carrot;
@property(readonly, nonatomic) IGCommentReshareBanner *reshareBanner; // @synthesize reshareBanner=_reshareBanner;
@property(readonly, nonatomic) UIView<IGCommentTextViewWithReshareProtocol> *textView; // @synthesize textView=_textView;
@property(readonly, nonatomic) UIView *autoCompletionView; // @synthesize autoCompletionView=_autoCompletionView;
@property(readonly, nonatomic) UIView *commentView; // @synthesize commentView=_commentView;
@property(readonly, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) __weak id <IGCommentReshareUIManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didDismissCommentReshareBanner:(id)arg1;
- (void)setFramesForReshareStatus:(int)arg1;
- (void)updateUIForReshareStatus:(int)arg1 inTransition:(BOOL)arg2;
@property(readonly, nonatomic) NSSet *viewsToMoveWithKeyboard;
- (id)initWithContainerView:(id)arg1 commentView:(id)arg2 autoCompletionView:(id)arg3 textView:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

