//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGGenericMegaphoneLogger.h"

@interface IGDefaultGenericMegaphoneLogger : NSObject <IGGenericMegaphoneLogger>
{
    BOOL _seen;
    unsigned int _displaySource;
}

@property(nonatomic) BOOL seen; // @synthesize seen=_seen;
@property(readonly, nonatomic) unsigned int displaySource; // @synthesize displaySource=_displaySource;
- (void)logMegaphone:(id)arg1 tappingButton:(id)arg2;
- (void)logMegaphoneButtonTapped:(id)arg1 withReason:(id)arg2;
- (void)logMegaphoneButtonTapped:(id)arg1;
- (void)logMegaphoneDismissed:(id)arg1;
- (void)logMegaphoneWasSeen:(id)arg1;
- (void)logForMegaphone:(id)arg1 action:(id)arg2 displaySourceString:(id)arg3 reason:(id)arg4;
- (void)logForAction:(id)arg1 megaphone:(id)arg2;
- (id)initWithDisplaySource:(unsigned int)arg1;

@end

