//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectSaveMediaDelegate.h"

@class IGDirectContent, IGDirectThreadViewController, IGUser, NSMutableArray;

@interface IGDirectMenuController : NSObject <IGDirectSaveMediaDelegate>
{
    IGDirectContent *_item;
    IGUser *_threadViewer;
    NSMutableArray *_directSaveMediaObservers;
    IGDirectThreadViewController *_viewController;
}

@property(nonatomic) __weak IGDirectThreadViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSMutableArray *directSaveMediaObservers; // @synthesize directSaveMediaObservers=_directSaveMediaObservers;
@property(retain, nonatomic) IGUser *threadViewer; // @synthesize threadViewer=_threadViewer;
@property(retain, nonatomic) IGDirectContent *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)saveMediaObserverDidFinishSaving:(id)arg1;
- (void)copy:(id)arg1;
- (void)unsend:(id)arg1;
- (void)save:(id)arg1;
- (void)unlike:(id)arg1;
- (void)flag:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)reportContent:(id)arg1;
- (void)performDeleteForContent:(id)arg1;
- (void)performRetyForContent:(id)arg1 onCell:(id)arg2;
- (void)didHideMenu:(id)arg1;
- (void)setOrUnsetMenuForContent:(id)arg1 cell:(id)arg2;
- (void)dealloc;
- (id)initWithViewController:(id)arg1 threadViewer:(id)arg2;

@end

