//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGDate, IGDirectContent, IGUser, NSArray, NSDictionary, NSOrderedSet, NSString;

@interface IGDirectThread : NSObject <NSCopying, NSCoding>
{
    BOOL _moreHistoryAvailable;
    BOOL _isNamed;
    BOOL _isPending;
    BOOL _isMuted;
    BOOL _isCanonical;
    BOOL _isLocal;
    BOOL _isPendingDeletion;
    NSString *_threadId;
    NSOrderedSet *_publishedContent;
    NSArray *_users;
    NSString *_nextMinId;
    NSString *_nextMaxId;
    NSString *_name;
    IGUser *_inviter;
    id <IGImageURLProvider> _lastMediaImageURLProvider;
    NSDictionary *_lastSeenAtForUserIds;
    NSDictionary *_lastSeenAtForItemIds;
    IGDate *_lastActivityDate;
    NSArray *_leftUsers;
}

+ (id)lastMediaItemFromDictionary:(id)arg1;
+ (id)contentArrayFromDictionary:(id)arg1;
+ (id)contentFromDictionary:(id)arg1;
+ (id)threadFromDictionary:(id)arg1;
+ (id)usersFromDictionary:(id)arg1 addSelf:(BOOL)arg2;
+ (void)lastSeenAtsFromDictionary:(id)arg1 userIdsToDates:(id *)arg2 itemIdsToDates:(id *)arg3;
+ (id)threadIdFromDictionary:(id)arg1;
+ (void)mergePublicContentFromThread:(id)arg1 intoThread:(id)arg2;
+ (id)mergeDataFromThread:(id)arg1 intoThread:(id)arg2 alwaysMerge:(BOOL)arg3;
+ (id)usernameStringForUsernames:(id)arg1 maxUsers:(int)arg2;
+ (id)usernameStringForUsers:(id)arg1 maxUsers:(int)arg2;
+ (id)shortUsernameStringForUsers:(id)arg1;
+ (id)usernameStringForUsers:(id)arg1;
@property(retain, nonatomic) NSArray *leftUsers; // @synthesize leftUsers=_leftUsers;
@property(retain, nonatomic) IGDate *lastActivityDate; // @synthesize lastActivityDate=_lastActivityDate;
@property(retain, nonatomic) NSDictionary *lastSeenAtForItemIds; // @synthesize lastSeenAtForItemIds=_lastSeenAtForItemIds;
@property(retain, nonatomic) NSDictionary *lastSeenAtForUserIds; // @synthesize lastSeenAtForUserIds=_lastSeenAtForUserIds;
@property(nonatomic) BOOL isPendingDeletion; // @synthesize isPendingDeletion=_isPendingDeletion;
@property(nonatomic) BOOL isLocal; // @synthesize isLocal=_isLocal;
@property(retain, nonatomic) id <IGImageURLProvider> lastMediaImageURLProvider; // @synthesize lastMediaImageURLProvider=_lastMediaImageURLProvider;
@property(retain, nonatomic) IGUser *inviter; // @synthesize inviter=_inviter;
@property(nonatomic) BOOL isCanonical; // @synthesize isCanonical=_isCanonical;
@property(nonatomic) BOOL isMuted; // @synthesize isMuted=_isMuted;
@property(nonatomic) BOOL isPending; // @synthesize isPending=_isPending;
@property(nonatomic) BOOL isNamed; // @synthesize isNamed=_isNamed;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) BOOL moreHistoryAvailable; // @synthesize moreHistoryAvailable=_moreHistoryAvailable;
@property(copy, nonatomic) NSString *nextMaxId; // @synthesize nextMaxId=_nextMaxId;
@property(copy, nonatomic) NSString *nextMinId; // @synthesize nextMinId=_nextMinId;
@property(retain, nonatomic) NSArray *users; // @synthesize users=_users;
@property(retain, nonatomic) NSOrderedSet *publishedContent; // @synthesize publishedContent=_publishedContent;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyBySettingLastMediaURLProviderTo:(id)arg1;
- (id)copyByReplacingReactableContent:(id)arg1 hasReactionsChanged:(char *)arg2;
- (id)copyByRenamingTo:(id)arg1;
- (id)copyBySettingMuteStatusTo:(BOOL)arg1;
- (id)copyBySettingLastSeenForUserWithId:(id)arg1 toTimestamp:(id)arg2 withSeenItemId:(id)arg3;
- (id)copyByRemovingContentWithId:(id)arg1;
- (id)copyByAddingContentFromArray:(id)arg1;
- (id)allContentsWithUploads:(id)arg1;
@property(readonly, nonatomic) BOOL disabled;
@property(readonly, nonatomic) IGDirectContent *lastVisibleContent;
@property(readonly, nonatomic) NSArray *allVisibleContent;
@property(readonly, nonatomic) NSArray *allContent;
@property(readonly, copy, nonatomic) NSString *uploadIndexKey;
- (BOOL)allowsNameChanges;
@property(readonly, nonatomic) IGDate *mostRecentActivityDate;
@property(readonly, nonatomic) IGDate *lastSeenAt;
- (id)seenAtForItemsWithId:(id)arg1;
- (id)lastSeenAtForUserWithId:(id)arg1;
@property(readonly, copy, nonatomic) NSString *defaultNameString;
- (id)copyForcingLastSeenToDate:(id)arg1;
- (id)copyByTrimmingContentToCount:(unsigned int)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSArray *activeUsers;
- (id)initLocalThreadWithUsers:(id)arg1 lastActivityDate:(id)arg2;
- (id)initWithDictionary:(id)arg1;
- (id)orderedArrayOfUsersHideCurrentUser:(BOOL)arg1;

@end

