//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGDirectContentUploader : NSObject
{
}

+ (BOOL)realtimeIsReadyForReceiving;
+ (BOOL)realtimeIsReadyForSending;
+ (void)handleLike:(BOOL)arg1 toContent:(id)arg2 inThread:(id)arg3 withFailureHandler:(CDUnknownBlockType)arg4;
+ (void)sendLikeToContent:(id)arg1 inThread:(id)arg2 withFailureHandler:(CDUnknownBlockType)arg3 like:(BOOL)arg4;
+ (void)logMessageWaterfall:(id)arg1 withContentType:(id)arg2 withClientContextID:(id)arg3 isRealtime:(BOOL)arg4 isSilent:(BOOL)arg5 networkDuration:(double)arg6 error:(id)arg7;
+ (void)logMessageWaterfall:(id)arg1 withContentType:(id)arg2 withClientContextID:(id)arg3 isRealtime:(BOOL)arg4 isSilent:(BOOL)arg5 networkDuration:(double)arg6;
+ (void)cancelUpload:(id)arg1;
+ (id)findRedundantUploads:(id)arg1 forThread:(id)arg2;
+ (void)removeRedundantUploadsForThread:(id)arg1;
+ (void)removeAllUnfinishedUploads;
+ (void)uploadDidFailForUploadModel:(id)arg1;
+ (void)retryVideoUploadsIfNeeded:(id)arg1;
+ (void)retryAllUploadsIfNeeded;
+ (void)wipeInMemoryUploads;
+ (void)completeMediaUploadableIfNeeded:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)retryUpload:(id)arg1 isSilent:(BOOL)arg2 progress:(CDUnknownBlockType)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uncacheUploadsForThreadsWithID:(id)arg1;
+ (id)internalUploadsForThreadWithID:(id)arg1 includeNonThreadUploadForUserKey:(id)arg2;
+ (void)clearUploadsForThreadWithID:(id)arg1;
+ (id)uploadsForThread:(id)arg1;
+ (void)finishMediaUploadForUpload:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (id)uploadVideo:(id)arg1 withText:(id)arg2 toRecipient:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uploadVideo:(id)arg1 toRecipient:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
+ (id)uploadPhotoWithUploadModel:(id)arg1 withText:(id)arg2 toRecipient:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uploadImage:(id)arg1 toRecipient:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
+ (id)uploadLocation:(id)arg1 withText:(id)arg2 toRecipient:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uploadProfile:(id)arg1 withText:(id)arg2 toRecipient:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uploadHashtag:(id)arg1 withText:(id)arg2 toRecipient:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uploadMediaReshare:(id)arg1 withText:(id)arg2 toRecipient:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)uploadLikeToRecipient:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (id)uploadText:(id)arg1 toRecipient:(id)arg2 progress:(CDUnknownBlockType)arg3 withCompletion:(CDUnknownBlockType)arg4;
+ (id)firstThreadIDFromResponse:(id)arg1;
+ (void)precacheUploadImagesIfNeeded:(id)arg1 response:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)fetchThreadIfRealtimeNotReceivingAndUploadIsVideo:(id)arg1;
+ (void)failUpload:(id)arg1 isSilent:(BOOL)arg2 networkDuration:(double)arg3 error:(id)arg4;
+ (void)sendUpload:(id)arg1 isSilent:(BOOL)arg2 withProgress:(CDUnknownBlockType)arg3 andCompletion:(CDUnknownBlockType)arg4;
+ (void)sendHttpUpload:(id)arg1 withProgress:(CDUnknownBlockType)arg2 andCompletion:(CDUnknownBlockType)arg3;
+ (id)requestForUpload:(id)arg1 withProgress:(CDUnknownBlockType)arg2 andCompletion:(CDUnknownBlockType)arg3;
+ (void)sendUpload:(id)arg1 withProgress:(CDUnknownBlockType)arg2 andCompletion:(CDUnknownBlockType)arg3;
+ (void)sendRealtimeUpload:(id)arg1 withProgress:(CDUnknownBlockType)arg2 andCompletion:(CDUnknownBlockType)arg3;
+ (id)paramsFromDict:(id)arg1 forUpload:(id)arg2;
+ (void)removeUploadFromMediaUploadManager:(id)arg1;
+ (void)clearUpload:(id)arg1;
+ (void)removeUploadFromDisk:(id)arg1;
+ (void)saveUpload:(id)arg1;
+ (id)uploadsBaseDirectoryForThreadId:(id)arg1;
+ (id)uploadsBaseDirectory;
+ (id)allUploadsByThreadId;
+ (id)inflightUploads;

@end

