//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGDirectSharingHelper : NSObject
{
}

+ (void)handleReshareFailureWithRecipient:(id)arg1;
+ (void)handleReshareSuccessfulResponse:(id)arg1 recipient:(id)arg2 threadID:(id *)arg3;
+ (id)getThreadFromResponse:(id)arg1 threadID:(id *)arg2;
+ (void)getOrFetchThreadFromResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)suppressedContentAfterContent:(id)arg1 allContent:(id)arg2;
+ (id)postsInContentArray:(id)arg1;
+ (id)igSequence2Date:(id)arg1;
+ (BOOL)isReactable:(id)arg1;
+ (id)firstEligibleDateForLikes;
+ (BOOL)isContentDateEligibleForLikes:(id)arg1;
+ (BOOL)showDoubleTapToLikeNuxForContent:(id)arg1;
+ (id)likedItemKeyForContent:(id)arg1;
+ (BOOL)hasShownDoubleTapNuxForContent:(id)arg1;
+ (void)updateUserDefaultsAfterLikeForContent:(id)arg1;
+ (BOOL)reactableIsLikedByCurrentUser:(id)arg1;
+ (BOOL)isDirectMediaUpload:(id)arg1;
+ (id)keyboardWindow;
+ (id)bfsFindSubviewOfClass:(Class)arg1 root:(id)arg2 maxLevel:(unsigned int)arg3;
+ (id)findKeyboardViewForTextView:(id)arg1;
+ (id)userKeyForUsers:(id)arg1;
+ (id)keysForUsers:(id)arg1;
+ (id)serializedStringFromDictionary:(id)arg1;
+ (int)lastVisibleContentIdx:(id)arg1;
+ (BOOL)showSeenstampFooterForIndexPath:(id)arg1 withContents:(id)arg2;
+ (BOOL)showTimestampHeaderForIndexPath:(id)arg1 withContents:(id)arg2;
+ (BOOL)showUsernameForIndexPath:(id)arg1 withContents:(id)arg2;
+ (BOOL)isThreadNameValid:(id)arg1;
+ (BOOL)isThreadNameTooLong:(id)arg1;
+ (BOOL)isBlankString:(id)arg1;
+ (id)seenUsersForContent:(id)arg1 thread:(id)arg2 pendingMode:(BOOL)arg3;

@end

