//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGGenericMegaphoneViewDelegate.h"
#import "IGMegaphonePresenterProtocol.h"

@class IGGenericMegaphoneView, NSString;

@interface IGDogfoodMegaphonePresenter : NSObject <IGGenericMegaphoneViewDelegate, IGMegaphonePresenterProtocol>
{
    BOOL _megaphoneSeen;
    IGGenericMegaphoneView *_megaphoneView;
    unsigned int _displaySource;
    id <IGMegaphonePresenterDelegate> _delegate;
}

+ (id)dogfoodMegaphoneMessageForUpdate;
+ (double)buildAgeInSeconds;
+ (id)newDogfoodMegaphone;
+ (BOOL)shouldShowDogfooderSoftNagMegaphone;
@property(nonatomic) BOOL megaphoneSeen; // @synthesize megaphoneSeen=_megaphoneSeen;
@property(readonly, nonatomic) __weak id <IGMegaphonePresenterDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) unsigned int displaySource; // @synthesize displaySource=_displaySource;
@property(readonly, nonatomic) IGGenericMegaphoneView *megaphoneView; // @synthesize megaphoneView=_megaphoneView;
- (void).cxx_destruct;
- (void)logWasSeen;
- (void)logEvent:(id)arg1;
- (void)legacyMegaphoneView:(id)arg1 didTapButton:(id)arg2;
- (void)legacyMegaphoneView:(id)arg1 didOpenURL:(id)arg2;
- (void)legacyMegaphoneViewDidDismiss:(id)arg1;
- (void)logMegaphoneSeen;
- (id)viewForMegaphone;
- (id)initWithMegaphone:(id)arg1 displaySource:(unsigned int)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

