//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

#import "IGBusinessConversionAddressViewControllerDelegate.h"
#import "IGBusinessConversionEditableProfileCellDelegate.h"
#import "IGChangePhoneNumberViewControllerDelegate.h"

@class IGFacebookPageInfo, NSString;

@interface IGEditBusinessProfileViewController : IGGroupedTableViewController <IGBusinessConversionAddressViewControllerDelegate, IGBusinessConversionEditableProfileCellDelegate, IGChangePhoneNumberViewControllerDelegate>
{
    BOOL _needsSave;
    IGFacebookPageInfo *_pageInfo;
}

@property(nonatomic) BOOL needsSave; // @synthesize needsSave=_needsSave;
@property(retain, nonatomic) IGFacebookPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
- (void).cxx_destruct;
- (BOOL)editableProfileCellWantsReturn:(id)arg1 withValue:(id)arg2 forKey:(id)arg3;
- (void)editableProfileCellDidBeginEditing:(id)arg1;
- (void)editableProfileCell:(id)arg1 didUpdateValue:(id)arg2 forDataKey:(id)arg3;
- (void)changePhoneNumberViewController:(id)arg1 doneEditingWithCountryNumber:(id)arg2 phoneNumber:(id)arg3 contactPreference:(unsigned int)arg4;
- (void)addressViewController:(id)arg1 didUpdateInfo:(id)arg2;
- (void)save;
- (void)updateRightButton;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (id)initWithUser:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

