//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGMediaRequestDelegate.h"
#import "IGVideoProxyDelegate.h"

@class IGMediaLoader, NSMutableDictionary, NSString;

@interface IGEventViewerMediaPreloader : NSObject <IGMediaRequestDelegate, IGVideoProxyDelegate>
{
    id <IGEventViewerMediaPreloaderCompletionDelegate> _completionDelegate;
    id <IGEventViewerMediaPreloaderPhotoProgressDelegate> _photoProgressDelegate;
    id <IGEventViewerMediaPreloaderVideoProgressDelegate> _videoProgressDelegate;
    float _photoWidth;
    IGMediaLoader *_mediaLoader;
    id <IGVideoProxyProtocol> _videoProxy;
    NSMutableDictionary *_postsToURLs;
}

@property(readonly, nonatomic) NSMutableDictionary *postsToURLs; // @synthesize postsToURLs=_postsToURLs;
@property(readonly, nonatomic) id <IGVideoProxyProtocol> videoProxy; // @synthesize videoProxy=_videoProxy;
@property(readonly, nonatomic) IGMediaLoader *mediaLoader; // @synthesize mediaLoader=_mediaLoader;
@property(nonatomic) float photoWidth; // @synthesize photoWidth=_photoWidth;
@property(nonatomic) __weak id <IGEventViewerMediaPreloaderVideoProgressDelegate> videoProgressDelegate; // @synthesize videoProgressDelegate=_videoProgressDelegate;
@property(nonatomic) __weak id <IGEventViewerMediaPreloaderPhotoProgressDelegate> photoProgressDelegate; // @synthesize photoProgressDelegate=_photoProgressDelegate;
@property(nonatomic) __weak id <IGEventViewerMediaPreloaderCompletionDelegate> completionDelegate; // @synthesize completionDelegate=_completionDelegate;
- (void).cxx_destruct;
- (void)notifyCompletionDelegateIfNeeded;
- (void)videoProxy:(id)arg1 didEndRequest:(id)arg2 forURL:(id)arg3 error:(id)arg4;
- (void)mediaRequest:(id)arg1 didFailWithError:(id)arg2 forURL:(id)arg3;
- (void)mediaRequest:(id)arg1 didLoadMediaWithData:(id)arg2 forURL:(id)arg3;
- (void)cancelAllRequestsExcludingPosts:(id)arg1;
- (void)cancelAllRequests;
- (void)preloadBlurredCoverImageForPosts:(id)arg1;
- (void)preloadMediaForPosts:(id)arg1;
- (id)initWithPhotoWidth:(float)arg1 mediaLoader:(id)arg2 videoProxy:(id)arg3;
- (id)initWithPhotoWidth:(float)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

