//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGExploreComposedPeopleYouFollowView;

@protocol IGExploreComposedPeopleYouFollowViewDelegate <NSObject>
- (void)composedPeopleYouFollowView:(IGExploreComposedPeopleYouFollowView *)arg1 didTapSocialItemAtIndex:(unsigned int)arg2;
@end

