//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGTimerProxyObjectType.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class CALayer, IGMarqueeCollectionView, IGMarqueeLayout, IGMarqueeViewLayoutSpec, IGTimerProxy, NSString, NSTimer;

@interface IGExploreJumbotronView : UIView <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, IGTimerProxyObjectType>
{
    id <IGExploreJumbotronDataSource> _dataSource;
    id <IGExploreJumbotronDelegate> _delegate;
    IGMarqueeCollectionView *_marqueeCollectionView;
    IGMarqueeLayout *_marqueeLayout;
    IGMarqueeViewLayoutSpec *_marqueeLayoutSpec;
    CALayer *_marqueeSeparatorLayer;
    NSTimer *_marqueeTimer;
    IGTimerProxy *_timerProxy;
}

@property(retain, nonatomic) IGTimerProxy *timerProxy; // @synthesize timerProxy=_timerProxy;
@property(retain, nonatomic) NSTimer *marqueeTimer; // @synthesize marqueeTimer=_marqueeTimer;
@property(retain, nonatomic) CALayer *marqueeSeparatorLayer; // @synthesize marqueeSeparatorLayer=_marqueeSeparatorLayer;
@property(retain, nonatomic) IGMarqueeViewLayoutSpec *marqueeLayoutSpec; // @synthesize marqueeLayoutSpec=_marqueeLayoutSpec;
@property(retain, nonatomic) IGMarqueeLayout *marqueeLayout; // @synthesize marqueeLayout=_marqueeLayout;
@property(retain, nonatomic) IGMarqueeCollectionView *marqueeCollectionView; // @synthesize marqueeCollectionView=_marqueeCollectionView;
@property(nonatomic) __weak id <IGExploreJumbotronDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <IGExploreJumbotronDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)correctedIndexPathForMarqueeAtIndexPath:(id)arg1;
- (unsigned int)numberOfMarqueeItems;
- (void)didFireTimer:(id)arg1;
- (void)startMarqueePaging;
- (void)cancelMarqueePaging;
- (struct CGPoint)marqueeViewCenter;
- (float)marqueeHeightForWidth:(float)arg1;
- (void)reloadMarquee;
- (void)reloadData;
- (BOOL)isMarqueePaging;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)didMoveToSuperview;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 marqueeLayoutSpec:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

