//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGLocation, IGUser, NSArray, NSString;

@interface IGExploreClusterItem : NSObject <NSCopying, NSCoding>
{
    NSString *_pk;
    unsigned int _type;
    IGUser *_user;
    IGLocation *_location;
    NSArray *_mediaBundles;
    NSString *_title;
    NSString *_subtitle;
    NSString *_byline;
}

@property(readonly, copy, nonatomic) NSString *byline; // @synthesize byline=_byline;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSArray *mediaBundles; // @synthesize mediaBundles=_mediaBundles;
@property(readonly, nonatomic) IGLocation *location; // @synthesize location=_location;
@property(readonly, nonatomic) IGUser *user; // @synthesize user=_user;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *pk; // @synthesize pk=_pk;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)parsedUserFromDictionary:(id)arg1;
- (id)parsedLocationFromDictionary:(id)arg1;
- (id)parsedMediaBundlesFromDictionary:(id)arg1;
- (unsigned int)parsedTypeFromDictionary:(id)arg1;
- (id)description;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPk:(id)arg1 type:(unsigned int)arg2 location:(id)arg3 user:(id)arg4 mediaBundles:(id)arg5 title:(id)arg6 subtitle:(id)arg7 byline:(id)arg8;
- (id)init;

@end

