//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGExplorePromptMediaViewDelegate.h"

@class IGExplorePromptMediaView, IGExplorePromptTooltipLogger, IGExplorePromptTooltipView, NSArray, NSDate, NSObject<OS_dispatch_source>, NSString;

@interface IGExplorePromptTooltipController : NSObject <IGExplorePromptMediaViewDelegate>
{
    NSObject<OS_dispatch_source> *_timer;
    BOOL _isTooltipVisible;
    id <IGExplorePromptTooltipDelegate> _delegate;
    IGExplorePromptMediaView *_exploreView;
    IGExplorePromptTooltipView *_tooltipView;
    NSArray *_imageURLs;
    NSDate *_lastImpressionTime;
    int _impressionCount;
    IGExplorePromptTooltipLogger *_logger;
    int _latestFeedPosition;
}

@property(nonatomic) int latestFeedPosition; // @synthesize latestFeedPosition=_latestFeedPosition;
@property(retain, nonatomic) IGExplorePromptTooltipLogger *logger; // @synthesize logger=_logger;
@property(nonatomic) BOOL isTooltipVisible; // @synthesize isTooltipVisible=_isTooltipVisible;
@property(nonatomic) int impressionCount; // @synthesize impressionCount=_impressionCount;
@property(retain, nonatomic) NSDate *lastImpressionTime; // @synthesize lastImpressionTime=_lastImpressionTime;
@property(retain, nonatomic) NSArray *imageURLs; // @synthesize imageURLs=_imageURLs;
@property(retain, nonatomic) IGExplorePromptTooltipView *tooltipView; // @synthesize tooltipView=_tooltipView;
@property(retain, nonatomic) IGExplorePromptMediaView *exploreView; // @synthesize exploreView=_exploreView;
@property(nonatomic) __weak id <IGExplorePromptTooltipDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)displayExploreTooltip;
- (void)dismissPrompt;
- (void)scheduleTimer;
- (void)explorePromptMediaViewDidTapOnCloseButton;
- (void)explorePromptMediaViewDidTapOnPromptView;
- (void)userDidInteractWithExplore;
- (void)mainFeedDidScrollToOldPost:(id)arg1;
- (void)mainFeedScrollTriggered:(id)arg1;
- (void)explorePreloadDidFinish:(id)arg1;
- (BOOL)shouldShowPrompt;
- (id)configureTooltipViewForViewWidth:(float)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

