//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGExplorePromptTooltipView;

@protocol IGExplorePromptTooltipDelegate <NSObject>
- (void)didTapExplorePromptTooltip:(IGExplorePromptTooltipView *)arg1;
- (void)dismissExplorePromptTooltip:(IGExplorePromptTooltipView *)arg1 withAnimation:(BOOL)arg2;
- (void)presentExplorePromptTooltipWithAnimation:(BOOL)arg1;
@end

