//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGRelatedItemDisplayType.h"
#import "NSCoding.h"

@class IGLocation, IGPostItem, NSArray, NSString;

@interface IGExploreTrendingItem : NSObject <NSCoding, IGRelatedItemDisplayType>
{
    IGPostItem *_topPostItem;
    NSArray *_postItems;
    NSString *_title;
    NSString *_subtitle;
    NSString *_key;
    unsigned int _type;
    IGLocation *_location;
}

@property(readonly, nonatomic) IGLocation *location; // @synthesize location=_location;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSArray *postItems; // @synthesize postItems=_postItems;
@property(readonly, nonatomic) IGPostItem *topPostItem; // @synthesize topPostItem=_topPostItem;
- (void).cxx_destruct;
- (id)relatedItemDisplayName;
@property(readonly) unsigned int hash;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)videoIconsVisible;
- (id)imageURLsWithWidth:(float)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPostItems:(id)arg1 title:(id)arg2 subtitle:(id)arg3 key:(id)arg4 type:(unsigned int)arg5 location:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

