//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

#import "UIAlertViewDelegate.h"

@class NSString;

@interface IGFacebookEndPointViewController : IGGroupedTableViewController <UIAlertViewDelegate>
{
}

- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
@property(readonly, nonatomic) unsigned int currentSelection;
- (void)showCustomAlertView;
- (void)setUpFacebookURL:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)textForCellAtEndPoint:(unsigned int)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)subtitleForHeaderInSection:(int)arg1;
- (id)titleForHeaderInSection:(int)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

