//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIColor, UIFont, UIImageView, UILabel, UIView;

@interface IGFancyTextSegment : UIControl
{
    BOOL _showFallbackIcon;
    UILabel *_titleLabel;
    UIImageView *_fallbackIconView;
    UIColor *_activeColor;
    UIColor *_inactiveColor;
    UIColor *_activeFallbackIconColor;
    UIColor *_inactiveFallbackIconColor;
    UIFont *_font;
    UIView *_leftBorder;
    UIView *_rightBorder;
}

@property(retain, nonatomic) UIView *rightBorder; // @synthesize rightBorder=_rightBorder;
@property(retain, nonatomic) UIView *leftBorder; // @synthesize leftBorder=_leftBorder;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIColor *inactiveFallbackIconColor; // @synthesize inactiveFallbackIconColor=_inactiveFallbackIconColor;
@property(retain, nonatomic) UIColor *activeFallbackIconColor; // @synthesize activeFallbackIconColor=_activeFallbackIconColor;
@property(retain, nonatomic) UIColor *inactiveColor; // @synthesize inactiveColor=_inactiveColor;
@property(retain, nonatomic) UIColor *activeColor; // @synthesize activeColor=_activeColor;
@property(nonatomic) BOOL showFallbackIcon; // @synthesize showFallbackIcon=_showFallbackIcon;
- (void).cxx_destruct;
- (void)updateHighlightedColor;
- (void)setHighlighted:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
@property(readonly, nonatomic) UIImageView *fallbackIconView; // @synthesize fallbackIconView=_fallbackIconView;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (BOOL)titleTooWideToFit;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1 font:(id)arg2 fallbackIcon:(id)arg3 showLeftBorder:(BOOL)arg4 showRightBorder:(BOOL)arg5;
- (id)initWithTitle:(id)arg1 font:(id)arg2 fallbackIcon:(id)arg3;

@end

