//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGHeartAnimatable.h"

@class IGPost, NSString, UINavigationController;

@interface IGFeedItemMediaCell : UICollectionViewCell <IGHeartAnimatable>
{
    IGPost *_post;
    UINavigationController *_navigationController;
}

+ (id)cellIdentifier;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(retain, nonatomic) IGPost *post; // @synthesize post=_post;
- (void).cxx_destruct;
- (id)contentViewForHeartAnimation;
- (id)accessibilityIdentifier;
- (void)layoutSubviews;
- (void)prepareForReuse;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

