//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGTombstoneView;

@interface IGFeedItemHiddenWithReasonCell : UICollectionViewCell
{
    IGTombstoneView *_tombstoneView;
}

@property(readonly, nonatomic) IGTombstoneView *tombstoneView; // @synthesize tombstoneView=_tombstoneView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

