//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGFeedItemPivotGridCellFactory : NSObject
{
}

+ (void)configureCell:(id)arg1 feedItem:(id)arg2 controller:(id)arg3 cellDelegate:(id)arg4 attributes:(id)arg5;
+ (id)cellFromCollectionView:(id)arg1 indexPath:(id)arg2;
+ (void)registerCellWithCollectionView:(id)arg1;

@end

