//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGCollectionViewLayoutDataSource.h"

@class IGCollectionViewController, NSString;

@interface IGFeedCollectionViewLayoutDataSource : NSObject <IGCollectionViewLayoutDataSource>
{
    id <IGCollectionViewControllerDataSource> _dataSource;
    IGCollectionViewController *_collectionViewController;
}

@property(readonly, nonatomic) __weak IGCollectionViewController *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
@property(readonly, nonatomic) __weak id <IGCollectionViewControllerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (struct CGPoint)targetContentOffsetForProposedContentOffset:(struct CGPoint)arg1 withScrollingVelocity:(struct CGPoint)arg2;
- (id)collectionViewLayout:(id)arg1 changeSetFromObjects:(id)arg2 fromContext:(id)arg3 toObjects:(id)arg4 toContext:(id)arg5;
- (struct CGSize)collectionViewLayout:(id)arg1 sizeForItemAtIndexPath:(id)arg2 withViewWidth:(float)arg3 withObjects:(id)arg4 context:(id)arg5;
- (int)collectionViewLayout:(id)arg1 numberOfItemsInSection:(int)arg2 withObjects:(id)arg3 context:(id)arg4;
- (int)numberOfSectionsForCollectionViewLayout:(id)arg1 withObjects:(id)arg2 context:(id)arg3;
- (void)collectionViewLayout:(id)arg1 prepareContext:(id)arg2 forObjects:(id)arg3;
- (id)initWithDataSource:(id)arg1 collectionViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

