//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGFeedItemAlbumCellFactory : NSObject
{
}

+ (struct CGSize)sizeForContainerWidth:(float)arg1;
+ (void)configureCell:(id)arg1 forFocusCoordinator:(id)arg2 delegate:(id)arg3 playerDelegate:(id)arg4;
+ (id)cellFromCollectionView:(id)arg1 indexPath:(id)arg2;
+ (void)registerCellWithCollectionView:(id)arg1;

@end

