//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedItemDirectResponseLoggingProviderDelegate.h"
#import "IGFeedItemLoggingProviderDelegate.h"

@class IGListAdapter, NSString;

@interface IGFeedItemLogger : NSObject <IGFeedItemLoggingProviderDelegate, IGFeedItemDirectResponseLoggingProviderDelegate>
{
    IGListAdapter *_listAdapter;
    unsigned int _mediaCellIndex;
}

@property(readonly, nonatomic) unsigned int mediaCellIndex; // @synthesize mediaCellIndex=_mediaCellIndex;
@property(readonly, nonatomic) IGListAdapter *listAdapter; // @synthesize listAdapter=_listAdapter;
- (void).cxx_destruct;
- (id)extraDictionaryForFeedItem:(id)arg1 directResponseInfo:(id)arg2;
- (id)extraDictionaryForFeedItem:(id)arg1;
- (unsigned int)offsetSectionForFeedItem:(id)arg1 inList:(id)arg2 atSection:(unsigned int)arg3;
- (id)initWithListAdapter:(id)arg1 mediaCellIndex:(unsigned int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

