//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class IGCollectionViewController<IGCollectionViewControllerDataSource><UICollectionViewDelegate>, NSArray, NSString;

@interface IGFeedDataSource : NSObject <UICollectionViewDataSource, UICollectionViewDelegate>
{
    NSArray *_objects;
    id _context;
    IGCollectionViewController<IGCollectionViewControllerDataSource><UICollectionViewDelegate> *_collectionViewController;
    float _headerHeight;
}

@property(readonly, nonatomic) float headerHeight; // @synthesize headerHeight=_headerHeight;
@property(readonly, nonatomic) __weak IGCollectionViewController<IGCollectionViewControllerDataSource><UICollectionViewDelegate> *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
@property(retain, nonatomic) id context; // @synthesize context=_context;
@property(retain, nonatomic) NSArray *objects; // @synthesize objects=_objects;
- (void).cxx_destruct;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)isScrollViewDelegateMethod:(SEL)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (int)numberOfSectionsInCollectionView:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 sizeForHeaderInSection:(int)arg2;
- (struct CGSize)collectionView:(id)arg1 sizeForItemAtIndexPath:(id)arg2;
- (id)initWithCollectionViewController:(id)arg1 headerHeight:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

