//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedItemVisibilityTracking.h"
#import "IGItemDiffingDelegate.h"

@class IGItemDiffing, NSString;

@interface IGFeedItemImpressionTracker : NSObject <IGItemDiffingDelegate, IGFeedItemVisibilityTracking>
{
    IGItemDiffing *_tracker;
    id <IGFeedItemLoggingProviderDelegate> _loggingDelegate;
    id <IGAnalyticsRaindropProtocol> _raindropDelegate;
}

@property(readonly, nonatomic) __weak id <IGAnalyticsRaindropProtocol> raindropDelegate; // @synthesize raindropDelegate=_raindropDelegate;
@property(readonly, nonatomic) __weak id <IGFeedItemLoggingProviderDelegate> loggingDelegate; // @synthesize loggingDelegate=_loggingDelegate;
@property(readonly, nonatomic) IGItemDiffing *tracker; // @synthesize tracker=_tracker;
- (void).cxx_destruct;
- (void)itemDiffing:(id)arg1 didChangeWithItemRemoved:(id)arg2;
- (void)itemDiffing:(id)arg1 didChangeWithItemAdded:(id)arg2;
- (void)updateWithVisibleElementLayoutAttributeFeedItemMap:(id)arg1 visibleContentRect:(struct CGRect)arg2;
- (id)initWithLoggingProviderDelegate:(id)arg1 raindropDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

