//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListItemController.h"

#import "IGFollowAllUsersCellDelegate.h"
#import "IGListItemType.h"

@class IGFollowAllHeaderItem, NSString;

@interface IGFollowAllHeaderItemController : IGListItemController <IGFollowAllUsersCellDelegate, IGListItemType>
{
    BOOL _followAllButtonEnabled;
    IGFollowAllHeaderItem *_followAllHeaderItem;
}

@property(nonatomic) BOOL followAllButtonEnabled; // @synthesize followAllButtonEnabled=_followAllButtonEnabled;
@property(readonly, nonatomic) IGFollowAllHeaderItem *followAllHeaderItem; // @synthesize followAllHeaderItem=_followAllHeaderItem;
- (void).cxx_destruct;
- (void)followAllUsersOnServer;
- (void)followAllUsersCellDidTapFollowAll:(id)arg1;
- (id)displayDelegate;
- (id)supplementaryViewSource;
- (void)didSelectItemAtIndex:(int)arg1;
- (id)cellForItemAtIndex:(int)arg1;
- (struct CGSize)estimatedSizeForItemAtIndex:(int)arg1;
- (struct CGSize)sizeForItemAtIndex:(int)arg1;
- (unsigned int)numberOfItems;
- (Class)cellClass;
- (id)cellClasses;
- (id)initWithFollowAllHeaderItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

