//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSArray, NSString, PHCachingImageManager, PHImageRequestOptions, UICollectionView, UIView;

@interface IGGalleryCollectionViewController : UIViewController <UICollectionViewDelegateFlowLayout, UICollectionViewDelegate, UICollectionViewDataSource>
{
    BOOL _canShowSelectedOverlay;
    NSArray *_assets;
    id <IGGalleryCollectionViewControllerDelegate> _delegate;
    UIView *_galleryCollectionViewOverlay;
    UICollectionView *_galleryCollectionView;
    PHCachingImageManager *_imageManager;
    PHImageRequestOptions *_imageRequestOptions;
    struct IGAssetSelectionMechanic _assetSelectionMechanic;
}

@property(retain, nonatomic) PHImageRequestOptions *imageRequestOptions; // @synthesize imageRequestOptions=_imageRequestOptions;
@property(retain, nonatomic) PHCachingImageManager *imageManager; // @synthesize imageManager=_imageManager;
@property(retain, nonatomic) UICollectionView *galleryCollectionView; // @synthesize galleryCollectionView=_galleryCollectionView;
@property(retain, nonatomic) UIView *galleryCollectionViewOverlay; // @synthesize galleryCollectionViewOverlay=_galleryCollectionViewOverlay;
@property(nonatomic) struct IGAssetSelectionMechanic assetSelectionMechanic; // @synthesize assetSelectionMechanic=_assetSelectionMechanic;
@property(nonatomic) BOOL canShowSelectedOverlay; // @synthesize canShowSelectedOverlay=_canShowSelectedOverlay;
@property(nonatomic) __weak id <IGGalleryCollectionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)setupImageManagerAndOptions;
- (id)assetAtIndexPath:(id)arg1;
- (BOOL)indexPathIsSeeAll:(id)arg1;
- (void)deselectCells;
- (void)setDisabled:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

