//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGGradientView, NSNumber, NSString, PHImageManager, PHImageRequestOptions, UIColor, UIImageView, UILabel, UIView;

@interface IGGridViewCell : UICollectionViewCell
{
    BOOL _disabled;
    BOOL _canShowSelectedOverlay;
    BOOL _showAssetNumber;
    BOOL _inICloud;
    id _asset;
    UIColor *_defaultBackgroundColor;
    UIColor *_selectedOverlayColor;
    int _position;
    PHImageManager *_imageManager;
    PHImageRequestOptions *_imageRequestOptions;
    unsigned int _assetNumber;
    UIImageView *_imageView;
    UIView *_selectedOverlay;
    UIView *_selectedOverlayBorderExtension;
    UIView *_disabledOverlay;
    int _requestID;
    UIImageView *_inICloudView;
    UIImageView *_slomoView;
    IGGradientView *_gradientView;
    UILabel *_durationLabel;
    UILabel *_assetNumberLabel;
    UILabel *_overlayTextLabel;
    struct CGSize _thumbnailSize;
}

@property(retain, nonatomic) UILabel *overlayTextLabel; // @synthesize overlayTextLabel=_overlayTextLabel;
@property(retain, nonatomic) UILabel *assetNumberLabel; // @synthesize assetNumberLabel=_assetNumberLabel;
@property(retain, nonatomic) UILabel *durationLabel; // @synthesize durationLabel=_durationLabel;
@property(retain, nonatomic) IGGradientView *gradientView; // @synthesize gradientView=_gradientView;
@property(retain, nonatomic) UIImageView *slomoView; // @synthesize slomoView=_slomoView;
@property(retain, nonatomic) UIImageView *inICloudView; // @synthesize inICloudView=_inICloudView;
@property(nonatomic) BOOL inICloud; // @synthesize inICloud=_inICloud;
@property(nonatomic) int requestID; // @synthesize requestID=_requestID;
@property(retain, nonatomic) UIView *disabledOverlay; // @synthesize disabledOverlay=_disabledOverlay;
@property(retain, nonatomic) UIView *selectedOverlayBorderExtension; // @synthesize selectedOverlayBorderExtension=_selectedOverlayBorderExtension;
@property(retain, nonatomic) UIView *selectedOverlay; // @synthesize selectedOverlay=_selectedOverlay;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) unsigned int assetNumber; // @synthesize assetNumber=_assetNumber;
@property(nonatomic) BOOL showAssetNumber; // @synthesize showAssetNumber=_showAssetNumber;
@property(nonatomic) BOOL canShowSelectedOverlay; // @synthesize canShowSelectedOverlay=_canShowSelectedOverlay;
@property(nonatomic) struct CGSize thumbnailSize; // @synthesize thumbnailSize=_thumbnailSize;
@property(retain, nonatomic) PHImageRequestOptions *imageRequestOptions; // @synthesize imageRequestOptions=_imageRequestOptions;
@property(retain, nonatomic) PHImageManager *imageManager; // @synthesize imageManager=_imageManager;
@property(nonatomic) int position; // @synthesize position=_position;
@property(retain, nonatomic) UIColor *selectedOverlayColor; // @synthesize selectedOverlayColor=_selectedOverlayColor;
@property(retain, nonatomic) UIColor *defaultBackgroundColor; // @synthesize defaultBackgroundColor=_defaultBackgroundColor;
@property(nonatomic, getter=isDisabled) BOOL disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) id asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (id)dateFormatter;
- (id)accessibilityLabel;
- (id)creationDate;
@property(readonly, nonatomic, getter=isHighFrameRate) BOOL highFrameRate;
@property(readonly, nonatomic) NSNumber *duration;
- (BOOL)isAssetPhotoOrVideo;
@property(readonly, nonatomic) BOOL isAssetPhoto;
- (void)updateLabelVisibility;
@property(copy, nonatomic) NSString *overlayText;
- (void)setSelected:(BOOL)arg1;
- (void)cancelImageRequest;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

