//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSObject.h"

@class NSURL;

@protocol IGImageURLProvider <NSObject, NSCoding>
- (NSURL *)thumbnailURLForAspectFillSize:(struct CGSize)arg1 option:(int)arg2;
- (NSURL *)imageURLOfAtLeastWidth:(float)arg1 scale:(float)arg2;
- (NSURL *)imageURLForWidth:(float)arg1 option:(int)arg2 scale:(float)arg3;
- (NSURL *)imageURLForWidth:(float)arg1 option:(int)arg2;
- (NSURL *)imageURLForWidth:(float)arg1;
@end

