//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGInsightsQuery : NSObject
{
    NSString *_pageType;
    NSString *_timeframe;
    NSString *_dataOrdering;
    NSString *_after;
    NSString *_first;
    NSString *_timezoneName;
}

@property(copy, nonatomic) NSString *timezoneName; // @synthesize timezoneName=_timezoneName;
@property(copy, nonatomic) NSString *first; // @synthesize first=_first;
@property(copy, nonatomic) NSString *after; // @synthesize after=_after;
@property(readonly, copy, nonatomic) NSString *dataOrdering; // @synthesize dataOrdering=_dataOrdering;
@property(readonly, copy, nonatomic) NSString *timeframe; // @synthesize timeframe=_timeframe;
@property(readonly, copy, nonatomic) NSString *pageType; // @synthesize pageType=_pageType;
- (void).cxx_destruct;
- (void)copyDataOrderingFromQuery:(id)arg1;
- (void)copyTimeframeFromQuery:(id)arg1;
- (void)copyPageTypeFromQuery:(id)arg1;
- (id)toDict;
- (id)initWithDictionary:(id)arg1;

@end

