//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGInsightsComponentListViewControllerDelegate.h"

@class IGInsightsComponentListViewController, IGInsightsLoggingHelper, NSString;

@interface IGInsightsViewController : IGViewController <IGInsightsComponentListViewControllerDelegate>
{
    IGInsightsComponentListViewController *_componentListViewController;
    IGInsightsLoggingHelper *_loggingHelper;
}

@property(retain, nonatomic) IGInsightsLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(retain, nonatomic) IGInsightsComponentListViewController *componentListViewController; // @synthesize componentListViewController=_componentListViewController;
- (void).cxx_destruct;
- (void)didSelectComponentListViewController:(id)arg1 toViewController:(id)arg2 animated:(BOOL)arg3;
- (id)generateQuery;
- (id)timezoneName;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithEntryPoint:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

