//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGInlineInsightsViewDelegate.h"
#import "IGInsightsContentRowListViewDelegate.h"
#import "UIViewControllerTransitioningDelegate.h"

@class IGInlineInsightsDataProvider, IGInlineInsightsView, IGInsightsLoggingHelper, IGPost, NSString, UIView;

@interface IGInlineInsightsViewController : UIViewController <UIViewControllerTransitioningDelegate, IGInsightsContentRowListViewDelegate, IGInlineInsightsViewDelegate>
{
    IGPost *_post;
    UIView *_overlayView;
    IGInlineInsightsView *_inlineInsightsView;
    IGInsightsLoggingHelper *_loggingHelper;
    IGInlineInsightsDataProvider *_dataProvider;
}

@property(retain, nonatomic) IGInlineInsightsDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(retain, nonatomic) IGInsightsLoggingHelper *loggingHelper; // @synthesize loggingHelper=_loggingHelper;
@property(retain, nonatomic) IGInlineInsightsView *inlineInsightsView; // @synthesize inlineInsightsView=_inlineInsightsView;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) IGPost *post; // @synthesize post=_post;
- (void).cxx_destruct;
- (void)needAnimateContentRowListView:(id)arg1 upForDistance:(float)arg2;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)failedToFetchDataForIGInlineInsightsView:(id)arg1;
- (void)onOverlayTapped;
- (id)contentContainerView;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

