//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSNumber, NSString, NSURL;

@interface IGIOSLink : NSObject <NSCoding>
{
    NSURL *_deeplinkUri;
    NSURL *_webUri;
    NSNumber *_contentId;
    NSString *_callToActionTitle;
    int _linkType;
}

@property(readonly, nonatomic) int linkType; // @synthesize linkType=_linkType;
@property(readonly, nonatomic) NSString *callToActionTitle; // @synthesize callToActionTitle=_callToActionTitle;
@property(readonly, nonatomic) NSNumber *contentId; // @synthesize contentId=_contentId;
@property(readonly, nonatomic) NSURL *webUri; // @synthesize webUri=_webUri;
@property(readonly, nonatomic) NSURL *deeplinkUri; // @synthesize deeplinkUri=_deeplinkUri;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqualToIOSLink:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

