//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, UICollectionReusableView;

@protocol IGListSupplementaryViewSource <NSObject>
- (struct CGSize)estimatedSizeForSupplementaryViewOfKind:(NSString *)arg1 atIndex:(int)arg2;
- (struct CGSize)sizeForSupplementaryViewOfKind:(NSString *)arg1 atIndex:(int)arg2;
- (UICollectionReusableView *)viewForSupplementaryElementOfKind:(NSString *)arg1 atIndex:(int)arg2;
- (NSDictionary *)supplementaryViewKindClasses;
@end

