//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayoutInvalidationContext.h"

@class NSSet;

@interface IGListVerticalLayoutInvalidationContext : UICollectionViewLayoutInvalidationContext
{
    BOOL _invalidateEstimatedAttributes;
    NSSet *_invalidatedIndexPaths;
}

@property(copy, nonatomic) NSSet *invalidatedIndexPaths; // @synthesize invalidatedIndexPaths=_invalidatedIndexPaths;
@property(nonatomic) BOOL invalidateEstimatedAttributes; // @synthesize invalidateEstimatedAttributes=_invalidateEstimatedAttributes;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

