//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSMapTable;

@interface IGListItemMap : NSObject <NSCopying>
{
    NSArray *_items;
    NSMapTable *_itemListMap;
    NSMapTable *_listIndexMap;
}

@property(readonly, nonatomic) NSMapTable *listIndexMap; // @synthesize listIndexMap=_listIndexMap;
@property(readonly, nonatomic) NSMapTable *itemListMap; // @synthesize itemListMap=_itemListMap;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)enumerateItemsAndItemControllersUsingBlock:(CDUnknownBlockType)arg1;
- (void)reset;
- (unsigned int)sectionForItem:(id)arg1;
- (id)itemForSection:(unsigned int)arg1;
- (id)listItemControllerForItem:(id)arg1;
- (void)updateWithItems:(id)arg1 listItemControllers:(id)arg2;
- (id)listItemControllerForSection:(unsigned int)arg1;
- (unsigned int)sectionForListItemController:(id)arg1;
- (id)initWithMapTable:(id)arg1;

@end

