//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewLayout.h"

@class IGListVerticalLayoutCache;

@interface IGListVerticalLayout : UICollectionViewLayout
{
    BOOL _stickyHeadersEnabled;
    BOOL _needsToPrepareAttributes;
    id <IGListVerticalLayoutDataSource> _dataSource;
    id <IGListVerticalLayoutEstimatingDataSource> _estimatingDataSource;
    float _sectionSpacing;
    float _stickyHeaderOriginYAdjustment;
    unsigned int _scrollState;
    IGListVerticalLayoutCache *_cache;
}

+ (Class)invalidationContextClass;
+ (Class)layoutAttributesClass;
@property(nonatomic) BOOL needsToPrepareAttributes; // @synthesize needsToPrepareAttributes=_needsToPrepareAttributes;
@property(readonly, nonatomic) IGListVerticalLayoutCache *cache; // @synthesize cache=_cache;
@property(nonatomic) unsigned int scrollState; // @synthesize scrollState=_scrollState;
@property(nonatomic) float stickyHeaderOriginYAdjustment; // @synthesize stickyHeaderOriginYAdjustment=_stickyHeaderOriginYAdjustment;
@property(nonatomic) BOOL stickyHeadersEnabled; // @synthesize stickyHeadersEnabled=_stickyHeadersEnabled;
@property(nonatomic) float sectionSpacing; // @synthesize sectionSpacing=_sectionSpacing;
@property(nonatomic) __weak id <IGListVerticalLayoutEstimatingDataSource> estimatingDataSource; // @synthesize estimatingDataSource=_estimatingDataSource;
@property(nonatomic) __weak id <IGListVerticalLayoutDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)lastIndexPath;
- (int)lastItemIndexInSection:(int)arg1;
- (BOOL)isEmptySection:(int)arg1;
- (void)enumerateAllIndexPathsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateIndexPathsInSectionRange:(struct _NSRange)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (int)numberOfItemsInSection:(int)arg1;
- (int)numberOfSections;
- (id)attributesAboveHeaderIndexPath:(id)arg1 estimated:(BOOL)arg2;
- (void)configureHeaderAttributes:(id)arg1 estimated:(BOOL)arg2 shouldQuerySize:(BOOL)arg3;
- (id)computeOrRetrieveSupplementaryViewAttributesAtIndexPath:(id)arg1 forKind:(id)arg2 estimated:(BOOL)arg3;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)attributesAboveItemIndexPath:(id)arg1 estimated:(BOOL)arg2 adjustmentForStickyHeader:(float *)arg3;
- (id)attributesAboveItemIndexPath:(id)arg1 estimated:(BOOL)arg2;
- (void)configureItemAttributes:(id)arg1 estimated:(BOOL)arg2;
- (id)computeOrRetrieveItemAttributesAtIndexPath:(id)arg1 estimated:(BOOL)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)processUpdateItems:(id)arg1;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (void)removeAttributesAtIndexPaths:(id)arg1;
- (void)reconfigureAttributesInSection:(unsigned int)arg1;
- (void)invalidateLayoutWithContext:(id)arg1;
- (unsigned int)findTargetItemInSection:(unsigned int)arg1 forElementsInRect:(struct CGRect)arg2 movingUp:(char *)arg3;
- (struct _NSRange)rangeForTargetSection:(int)arg1;
- (struct _NSRange)findTargetSectionRangeForElementsInRect:(struct CGRect)arg1;
- (id)attributesFromLastKnownAttributes:(id)arg1 inRect:(struct CGRect)arg2 targetRange:(struct _NSRange *)arg3;
- (void)configureHeaderAttributesForStickiness:(id)arg1;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (BOOL)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
- (void)prepareAllAttributes;
- (void)prepareLayout;
- (void)resetForDataSourceChange;
- (id)description;
- (id)init;
- (id)initWithDataSource:(id)arg1 estimatingDataSource:(id)arg2 layoutCache:(id)arg3;

@end

