//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class CALayer, UILabel;

@interface IGMarqueeContextView : UICollectionReusableView
{
    UILabel *_label;
    CALayer *_separatorLayer;
}

+ (float)heightForHeaderWithText:(id)arg1 width:(float)arg2;
+ (id)headerIdentifier;
@property(readonly, nonatomic) __weak CALayer *separatorLayer; // @synthesize separatorLayer=_separatorLayer;
@property(readonly, nonatomic) __weak UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)configureWithContext:(id)arg1;
- (void)setupAndConfigureViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

