//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGMarqueeViewLayoutSpec : NSObject
{
    BOOL _allowsInfiniteScrolling;
    float _interItemSpacing;
    float _verticalContentInset;
    float _horizontalContentPeeking;
    unsigned int _contentAlignment;
    float _contentAspectRatio;
    double _autoPagingInterval;
}

@property(readonly, nonatomic) float contentAspectRatio; // @synthesize contentAspectRatio=_contentAspectRatio;
@property(readonly, nonatomic) unsigned int contentAlignment; // @synthesize contentAlignment=_contentAlignment;
@property(readonly, nonatomic) BOOL allowsInfiniteScrolling; // @synthesize allowsInfiniteScrolling=_allowsInfiniteScrolling;
@property(readonly, nonatomic) float horizontalContentPeeking; // @synthesize horizontalContentPeeking=_horizontalContentPeeking;
@property(readonly, nonatomic) float verticalContentInset; // @synthesize verticalContentInset=_verticalContentInset;
@property(readonly, nonatomic) float interItemSpacing; // @synthesize interItemSpacing=_interItemSpacing;
@property(readonly, nonatomic) double autoPagingInterval; // @synthesize autoPagingInterval=_autoPagingInterval;
- (id)init;
- (id)initWithAutoPagingInterval:(double)arg1 interItemSpacing:(float)arg2 verticalContentInset:(float)arg3 horizontalContentPeeking:(float)arg4 allowsInfiniteScrolling:(BOOL)arg5 contentAlignment:(unsigned int)arg6 contentAspectRatio:(float)arg7;

@end

