//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionClearableObject.h"

@class NSMutableDictionary, NSString;

@interface IGMediaUploadManager : NSObject <IGUserSessionClearableObject>
{
    NSMutableDictionary *_activeUploads;
    int _maxAutoRetryConfigureCount;
    NSString *_userPK;
}

+ (void)clearForUserPK:(id)arg1;
+ (id)configureUrlFromUpload:(id)arg1;
+ (id)configureEndpointFromUpload:(id)arg1;
+ (id)unarchiveUploadsForPath:(id)arg1;
+ (id)sharedManager;
@property(retain, nonatomic) NSString *userPK; // @synthesize userPK=_userPK;
@property(nonatomic) int maxAutoRetryConfigureCount; // @synthesize maxAutoRetryConfigureCount=_maxAutoRetryConfigureCount;
- (void).cxx_destruct;
- (void)willLogOut;
- (void)willSwitchUsers;
- (void)endConfigureBackgroundTaskForUpload:(id)arg1;
- (void)endUploadBackgroundTaskForUpload:(id)arg1;
- (void)startConfigureBackgroundTaskForUpload:(id)arg1;
- (void)startUploadBackgroundTaskForUpload:(id)arg1;
- (void)manuallyCacheLocalImageData:(id)arg1 forItem:(id)arg2;
- (void)postFinishedWithServerResponse:(id)arg1 forUpload:(id)arg2;
- (BOOL)validateServerResponse:(id)arg1 forUpload:(id)arg2;
- (void)configureUploadFailed:(id)arg1 withError:(id)arg2;
- (void)configureUploadAutoRetryUpload:(id)arg1 withRetryError:(id)arg2;
- (void)finishConfigureForDirectShareUpload:(id)arg1;
- (id)generateConfigureParamsForUpload:(id)arg1;
- (void)configureUploadForStartTime:(id)arg1;
- (void)shareUploadForStartTime:(id)arg1;
- (void)uploadVideoDataForUpload:(id)arg1;
- (void)uploadVideoCoverPhotoForStartTime:(id)arg1;
- (void)uploadVideoForStartTime:(id)arg1;
- (id)paramsForHighResolutionUploadExperimentWithUpload:(id)arg1;
- (void)uploadPhotoForStartTime:(id)arg1;
- (id)uploadIdForUpload:(id)arg1;
- (id)validUploadsDirectedUploads;
- (id)validUploadsBroadcastUploads;
- (id)validUploadsForDirectedSharing:(BOOL)arg1;
- (void)notifyVideoConfigureFailureWithUploadTime:(id)arg1 andReason:(id)arg2;
- (void)notifyVideoUploadFailureWithUploadTime:(id)arg1 andReason:(id)arg2;
- (void)notifyImageUploadFailureWithUploadTime:(id)arg1 andReason:(id)arg2;
- (id)uploadForStartTime:(id)arg1;
- (void)cancelAllUploads;
- (void)removeCompletedUploads;
- (void)removeUploadsForKeys:(id)arg1;
- (void)showAlertProcessingFailed;
- (void)retryUploadWithStartTime:(id)arg1;
- (void)removeUploadWithStartTime:(id)arg1 isUserAction:(BOOL)arg2;
- (void)createUploadWithDataType:(int)arg1 startTime:(id)arg2;
- (id)createUploadForType:(int)arg1;
- (void)processUnarchivedUploads;
- (void)unarchiveUploads;
- (void)archiveUploadsWithAppEnteringBackground:(BOOL)arg1;
- (void)stashAllUploads;
- (void)removeUnusedSavedUploadsFromDisk;
- (void)onAppWillResume:(id)arg1;
- (void)onAppWillBackground:(id)arg1;
- (void)onAppWillTerminate:(id)arg1;
- (id)activeUploadsSynchronizedCopy;
- (void)dealloc;
- (id)initWithUserSessionPK:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

