//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGFeedVideoPlayerDelegate.h"

@class IGFeedVideoPlayer, IGMediaThumbnailSelectableOverlay, IGMediaThumbnailView, NSString, UIView;

@interface IGMediaThumbnailCell : UICollectionViewCell <IGFeedVideoPlayerDelegate>
{
    BOOL _showHighlight;
    BOOL _isSelectable;
    IGMediaThumbnailView *_thumbnailView;
    UIView *_highlightView;
    IGMediaThumbnailSelectableOverlay *_selectableOverlay;
    IGFeedVideoPlayer *_videoPlayer;
    UIView *_videoPlayerView;
}

+ (id)videoPool;
@property(retain, nonatomic) UIView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
@property(retain, nonatomic) IGFeedVideoPlayer *videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) IGMediaThumbnailSelectableOverlay *selectableOverlay; // @synthesize selectableOverlay=_selectableOverlay;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
@property(nonatomic) BOOL isSelectable; // @synthesize isSelectable=_isSelectable;
@property(nonatomic) BOOL showHighlight; // @synthesize showHighlight=_showHighlight;
@property(retain, nonatomic) IGMediaThumbnailView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)videoPlayer:(id)arg1 didUpdatePlaybackProgress:(float)arg2;
- (void)videoPlayer:(id)arg1 didUpdateLoadingProgress:(float)arg2;
- (void)videoPlayer:(id)arg1 didFailToPlaybackWithError:(id)arg2;
- (void)videoPlayerDidPlay:(id)arg1;
- (void)videoPlayerWillPrepareAssetForPlayback:(id)arg1;
- (void)videoPlayer:(id)arg1 playbackBufferLikelyToKeepUp:(BOOL)arg2;
- (void)videoPlayer:(id)arg1 playbackBufferEmpty:(BOOL)arg2;
- (void)videoPlayerDidPlayToEnd:(id)arg1;
- (void)videoPlayerLoadedFirstFrame:(id)arg1;
- (void)videoPlayer:(id)arg1 didLoadVideoInView:(id)arg2;
- (void)videoPrepareForReuse;
- (void)finishUsingPlayer:(id)arg1;
- (id)dequeueReusablePlayer;
- (void)playVideoWithURL:(id)arg1;
- (void)setImageURL:(id)arg1 isVideo:(BOOL)arg2 synchronous:(BOOL)arg3;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

