//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListItemController.h"

#import "IGListItemType.h"

@class IGExploreMainFeedLayoutConfiguration, IGFeedFocusCoordinator, IGFeedItem, IGFeedNetworkSource, NSString;

@interface IGMediaThumbnailItemController : IGListItemController <IGListItemType>
{
    IGFeedItem *_feedItem;
    IGFeedNetworkSource *_networkSource;
    IGFeedFocusCoordinator *_focusCoordinator;
    IGExploreMainFeedLayoutConfiguration *_layoutConfig;
    id <IGFeedNetworkSourceHideDelegate> _hideDelegate;
}

@property(readonly, nonatomic) __weak id <IGFeedNetworkSourceHideDelegate> hideDelegate; // @synthesize hideDelegate=_hideDelegate;
@property(readonly, nonatomic) IGExploreMainFeedLayoutConfiguration *layoutConfig; // @synthesize layoutConfig=_layoutConfig;
@property(readonly, nonatomic) IGFeedFocusCoordinator *focusCoordinator; // @synthesize focusCoordinator=_focusCoordinator;
@property(readonly, nonatomic) IGFeedNetworkSource *networkSource; // @synthesize networkSource=_networkSource;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
- (void).cxx_destruct;
- (unsigned int)contextualFeedInfiniteScrollCap;
- (id)newContexualFeedController;
- (id)newNetworkSource;
- (void)configureCell:(id)arg1 atIndex:(int)arg2;
- (id)displayDelegate;
- (id)supplementaryViewSource;
- (void)didSelectItemAtIndex:(int)arg1;
- (struct CGSize)estimatedSizeForItemAtIndex:(int)arg1;
- (struct CGSize)sizeForItemAtIndex:(int)arg1;
- (id)cellForItemAtIndex:(int)arg1;
- (unsigned int)numberOfItems;
- (id)cellClasses;
- (id)initWithFeedItem:(id)arg1 networkSource:(id)arg2 focusCoordinator:(id)arg3 layoutConfig:(id)arg4 hideDelegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

