//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerPreviewing.h"

@class NSString, UIGestureRecognizer, UIView, UIViewController;

@interface IGPreviewingHandler : NSObject <UIViewControllerPreviewing>
{
    id <UIViewControllerPreviewingDelegate> _delegate;
    UIView *_sourceView;
    UIGestureRecognizer *_previewingGestureRecognizerForFailureRelationship;
    UIViewController *_controller;
    struct CGRect _sourceRect;
    struct CGRect _originalSourceRect;
}

@property(readonly, nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
@property(readonly, nonatomic) struct CGRect originalSourceRect; // @synthesize originalSourceRect=_originalSourceRect;
@property(nonatomic) struct CGRect sourceRect; // @synthesize sourceRect=_sourceRect;
@property(readonly, nonatomic) UIGestureRecognizer *previewingGestureRecognizerForFailureRelationship; // @synthesize previewingGestureRecognizerForFailureRelationship=_previewingGestureRecognizerForFailureRelationship;
@property(readonly, nonatomic) UIView *sourceView; // @synthesize sourceView=_sourceView;
@property(readonly, nonatomic) id <UIViewControllerPreviewingDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)initWithDelegate:(id)arg1 sourceView:(id)arg2 presentingViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

