//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBaseStruct.h"

@class NSNumber, NSString;

@interface IGRaindropSearchQueryEvent : TBaseStruct
{
    NSNumber *__thrift_isTypeahead;
    NSNumber *__thrift_nullState;
    NSString *__thrift_searchQueryText;
    NSNumber *__thrift_rttInMillis;
    NSNumber *__thrift_totalResults;
    NSNumber *__thrift_numberOfLocalResults;
    struct NSMutableArray *__thrift_impressions;
}

- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)toDict;
- (id)description;
- (void)write:(id)arg1;
- (id)initWithIsTypeahead:(id)arg1 nullState:(id)arg2 searchQueryText:(id)arg3 rttInMillis:(id)arg4 totalResults:(id)arg5 numberOfLocalResults:(id)arg6 impressions:(struct NSMutableArray *)arg7;
- (id)init;

@end

