//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBaseStruct.h"

@class NSNumber, NSString;

@interface IGRaindropRankInfo : TBaseStruct
{
    int __thrift_searchType;
    NSString *__thrift_searchQueryText;
    int __thrift_viewSubType;
    NSString *__thrift_rankToken;
    NSNumber *__thrift_itemRankResponseOffset;
    NSNumber *__thrift_itemRankDisplayOffset;
    NSNumber *__thrift_rankDisplayRowSize;
    NSNumber *__thrift_rankDisplayColumnSize;
    int __thrift_sectionType;
    NSString *__thrift_searchSessionId;
    NSString *__thrift_entityId;
    NSString *__thrift_searchImpressionToken;
    NSString *__thrift_extra;
}

- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)toDict;
- (id)description;
- (void)write:(id)arg1;
- (id)rankToken;
- (int)viewSubType;
- (id)searchQueryText;
- (int)searchType;
- (id)initWithSearchType:(int)arg1 searchQueryText:(id)arg2 viewSubType:(int)arg3 rankToken:(id)arg4 itemRankResponseOffset:(id)arg5 itemRankDisplayOffset:(id)arg6 rankDisplayRowSize:(id)arg7 rankDisplayColumnSize:(id)arg8 sectionType:(int)arg9 searchSessionId:(id)arg10 entityId:(id)arg11 searchImpressionToken:(id)arg12 extra:(id)arg13;
- (id)init;

@end

