//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBaseStruct.h"

@class IGRaindropMarquee, IGRaindropPositionIn2D, NSNumber, NSString;

@interface IGRaindropMarqueeClickEvent : TBaseStruct
{
    IGRaindropMarquee *__thrift_marquee;
    NSNumber *__thrift_sectionNumber;
    IGRaindropPositionIn2D *__thrift_position;
    NSString *__thrift_algorithm;
    NSString *__thrift_clusterKey;
    int __thrift_sectionType;
    NSString *__thrift_targetId;
}

- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)toDict;
- (id)description;
- (void)write:(id)arg1;
- (id)initWithMarquee:(id)arg1 sectionNumber:(id)arg2 position:(id)arg3 algorithm:(id)arg4 clusterKey:(id)arg5 sectionType:(int)arg6 targetId:(id)arg7;
- (id)init;

@end

