//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGTextFieldDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class IGRetroRegistrationRequestSupportView, NSIndexPath, NSString, UITapGestureRecognizer;

@interface IGRetroRegistrationRequestSupportViewController : UIViewController <UIGestureRecognizerDelegate, UITableViewDataSource, UITableViewDelegate, IGTextFieldDelegate, UITextViewDelegate>
{
    BOOL _submitting;
    id <IGRetroRegistrationRequestSupportDelegate> _delegate;
    IGRetroRegistrationRequestSupportView *_requestSupportView;
    UITapGestureRecognizer *_tapGesture;
    NSString *_twoFactorIdentifier;
    NSString *_username;
    NSIndexPath *_checkedAccountTypeIndexPath;
    NSIndexPath *_checkedReasonIndexPath;
    unsigned int _requestSupportType;
    struct CGRect _activeFrame;
}

@property(nonatomic) BOOL submitting; // @synthesize submitting=_submitting;
@property(nonatomic) unsigned int requestSupportType; // @synthesize requestSupportType=_requestSupportType;
@property(nonatomic) struct CGRect activeFrame; // @synthesize activeFrame=_activeFrame;
@property(retain, nonatomic) NSIndexPath *checkedReasonIndexPath; // @synthesize checkedReasonIndexPath=_checkedReasonIndexPath;
@property(retain, nonatomic) NSIndexPath *checkedAccountTypeIndexPath; // @synthesize checkedAccountTypeIndexPath=_checkedAccountTypeIndexPath;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *twoFactorIdentifier; // @synthesize twoFactorIdentifier=_twoFactorIdentifier;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) IGRetroRegistrationRequestSupportView *requestSupportView; // @synthesize requestSupportView=_requestSupportView;
@property(nonatomic) __weak id <IGRetroRegistrationRequestSupportDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)selectedReasonType;
- (id)selectedAccountType;
- (id)descriptionForRequestSupportForm;
- (void)updateRequestSupportButton;
- (void)textViewDidChange:(id)arg1;
- (BOOL)textViewShouldBeginEditing:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (BOOL)textFieldShouldBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)keyboardWillHide;
- (void)keyboardWillShow:(id)arg1;
- (void)requestSupportFailureHandler:(id)arg1;
- (void)requestSupportSuccessHandler:(id)arg1;
- (void)supportButtonTapped;
- (void)backButtonTapped;
- (BOOL)prefersStatusBarHidden;
- (BOOL)prefersNavigationBarHidden;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithUsername:(id)arg1 twoFactorIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

