//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGClusterBrowsingCategoriesScrollView, IGRegistrationBackgroundView;

@interface IGRegistrationClusterBrowsingCategoriesView : UIView
{
    IGClusterBrowsingCategoriesScrollView *_categoriesScrollView;
    IGRegistrationBackgroundView *_backgroundView;
}

@property(retain, nonatomic) IGRegistrationBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) IGClusterBrowsingCategoriesScrollView *categoriesScrollView; // @synthesize categoriesScrollView=_categoriesScrollView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

