//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, UIViewController;

@interface IGScreenshotObserver : NSObject
{
    UIViewController *_controller;
    NSMutableArray *_extraLogBlocks;
}

@property(retain, nonatomic) NSMutableArray *extraLogBlocks; // @synthesize extraLogBlocks=_extraLogBlocks;
@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)stopObserving;
- (void)startObserving;
- (void)onTakenScreenshot;
- (void)addExtraLogBlock:(CDUnknownBlockType)arg1;
- (id)initForController:(id)arg1;

@end

