//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "UIGestureRecognizerDelegate.h"

@class IGProfilePictureImageView, IGUser, NSString, UIImageView, UILabel, UILongPressGestureRecognizer;

@interface IGSearchResultCollectionViewCell : UICollectionViewCell <UIGestureRecognizerDelegate>
{
    IGUser *_user;
    id <IGSearchResultCollectionViewCellDelegate> _delegate;
    IGProfilePictureImageView *_profileView;
    UILabel *_unseenLabel;
    UILabel *_usernameLabel;
    int _borderStyle;
    UIImageView *_verifiedBadgeImageView;
    UILongPressGestureRecognizer *_longPressRecognizer;
}

+ (struct CGSize)cellSize;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UIImageView *verifiedBadgeImageView; // @synthesize verifiedBadgeImageView=_verifiedBadgeImageView;
@property(nonatomic) int borderStyle; // @synthesize borderStyle=_borderStyle;
@property(retain, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(retain, nonatomic) UILabel *unseenLabel; // @synthesize unseenLabel=_unseenLabel;
@property(retain, nonatomic) IGProfilePictureImageView *profileView; // @synthesize profileView=_profileView;
@property(nonatomic) __weak id <IGSearchResultCollectionViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)longPress:(id)arg1;
- (BOOL)gestureRecognizerShouldBeginInCollectionView:(id)arg1;
- (void)configureWithUser:(id)arg1 delegate:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 andBorderStyle:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

