//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDKDiffable.h"

@class NSArray, NSString;

@interface IGSearchNullStateSuggestionModel : NSObject <IGDKDiffable>
{
    NSArray *_users;
    NSString *_diffIdentifier;
}

@property(retain, nonatomic) NSString *diffIdentifier; // @synthesize diffIdentifier=_diffIdentifier;
@property(readonly, nonatomic) NSArray *users; // @synthesize users=_users;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithUsers:(id)arg1;

@end

