//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGSearchAnalyticsLogger : NSObject
{
}

+ (void)logSearchBeginEvent:(id)arg1 navState:(id)arg2;
+ (void)logSearchClickEventWithSearchString:(id)arg1 sessionId:(id)arg2 userId:(id)arg3 searchType:(int *)arg4 indexPath:(id)arg5 rankToken:(id)arg6 navState:(id)arg7;

@end

