//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, UIColor;

@interface IGSegmentedProgressView : UIView
{
    UIColor *_activeSegmentColor;
    UIColor *_inactiveSegmentColor;
    unsigned int _activeSegmentIndex;
    NSMutableArray *_segments;
}

@property(retain, nonatomic) NSMutableArray *segments; // @synthesize segments=_segments;
@property(nonatomic) unsigned int activeSegmentIndex; // @synthesize activeSegmentIndex=_activeSegmentIndex;
@property(retain, nonatomic) UIColor *inactiveSegmentColor; // @synthesize inactiveSegmentColor=_inactiveSegmentColor;
@property(retain, nonatomic) UIColor *activeSegmentColor; // @synthesize activeSegmentColor=_activeSegmentColor;
- (void).cxx_destruct;
- (void)resetCurrentSegmentsWithProgressNumbers:(id)arg1;
@property(readonly, nonatomic) float totalProgress;
@property(copy, nonatomic) NSArray *progressNumbers;
- (void)updateProgress:(float)arg1 forSegmentAtIndex:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)updateProgress:(float)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (void)setProgressNumbers:(id)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

