//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor, UIVisualEffect;

@interface IGStatusBarVolumeViewConfiguration : NSObject
{
    UIColor *_trackTintColor;
    UIColor *_trackValueTintColor;
    UIColor *_backgroundColor;
    float _backgroundAlpha;
    UIVisualEffect *_backgroundEffect;
    float _volumeViewHeight;
}

+ (id)translucentBackground;
+ (id)darkBackground;
+ (id)defaultConfiguration;
@property(nonatomic) float volumeViewHeight; // @synthesize volumeViewHeight=_volumeViewHeight;
@property(retain, nonatomic) UIVisualEffect *backgroundEffect; // @synthesize backgroundEffect=_backgroundEffect;
@property(nonatomic) float backgroundAlpha; // @synthesize backgroundAlpha=_backgroundAlpha;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *trackValueTintColor; // @synthesize trackValueTintColor=_trackValueTintColor;
@property(retain, nonatomic) UIColor *trackTintColor; // @synthesize trackTintColor=_trackTintColor;
- (void).cxx_destruct;
- (id)init;

@end

