//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CALayer, IGKVOHandle, NSArray, NSString, UIFont, UILabel, UIScrollView;

@interface IGTabControl : UIView
{
    BOOL _shouldHideBottomSeparator;
    BOOL _canUseFallbackIcons;
    BOOL _scrollable;
    BOOL _showButtonBorder;
    UIView *_inchwormView;
    NSArray *_buttons;
    id <IGTabControlDelegate> _delegate;
    UIScrollView *_connectedScrollView;
    NSString *_title;
    IGKVOHandle *_contentOffsetHandle;
    CALayer *_bottomSeparator;
    UIScrollView *_scrollView;
    UILabel *_titleLabel;
    UIFont *_font;
}

+ (float)preferredHeight;
@property(readonly, nonatomic) BOOL showButtonBorder; // @synthesize showButtonBorder=_showButtonBorder;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) BOOL scrollable; // @synthesize scrollable=_scrollable;
@property(readonly, nonatomic) BOOL canUseFallbackIcons; // @synthesize canUseFallbackIcons=_canUseFallbackIcons;
@property(retain, nonatomic) CALayer *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(retain, nonatomic) IGKVOHandle *contentOffsetHandle; // @synthesize contentOffsetHandle=_contentOffsetHandle;
@property(nonatomic) BOOL shouldHideBottomSeparator; // @synthesize shouldHideBottomSeparator=_shouldHideBottomSeparator;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIScrollView *connectedScrollView; // @synthesize connectedScrollView=_connectedScrollView;
@property(nonatomic) __weak id <IGTabControlDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
- (void).cxx_destruct;
- (void)_stretchLayoutButtons;
- (void)layoutSubviews;
- (struct CGRect)frameForSegment:(unsigned int)arg1 withLayoutParameters:(struct IGTabControlLayoutParameters)arg2;
- (struct IGTabControlLayoutParameters)layoutParametersForFrame:(struct CGRect)arg1 segmentCount:(unsigned int)arg2;
- (void)onSegmentTapped:(id)arg1;
- (void)updateAccessibilityStateForButtons:(id)arg1 selectedIndex:(int)arg2;
- (void)updateScrollViewPosition;
- (void)highlightVisibleSegment;
- (void)setSelectedIndex:(unsigned int)arg1;
- (void)setSegments:(id)arg1;
- (id)newSegmentWithTitle:(id)arg1 font:(id)arg2 fallbackIcon:(id)arg3 accessibilityIdentifier:(id)arg4 showLeftBorder:(BOOL)arg5 showRightBorder:(BOOL)arg6;
@property(readonly, nonatomic) UIView *inchwormView; // @synthesize inchwormView=_inchwormView;
- (struct CGRect)scrollIndicatorBarFrameForScrollView:(id)arg1 layoutParameters:(struct IGTabControlLayoutParameters)arg2;
- (struct CGRect)scrollIndicatorBarFrameForScrollView:(id)arg1;
- (struct CGRect)verticalPositionForScrollIndicatorBar:(struct CGRect)arg1;
- (void)applyStyle;
- (id)initWithFrame:(struct CGRect)arg1 scrollable:(BOOL)arg2 tabFont:(id)arg3 showButtonBorder:(BOOL)arg4;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

