//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView, UIView;

@interface IGTabBarButton : UIButton
{
    BOOL _needsAttention;
    BOOL _clearsAttentionWhenSelected;
    UIView *_viewForVibrancyEffect;
    UIView *_customView;
    UIImageView *_markView;
}

+ (BOOL)shouldUseNewIcons;
+ (id)tabBarButtonWithIconNamed:(id)arg1 highlightedIconNamed:(id)arg2;
+ (id)profileButtonWithProfilePictureImageView:(id)arg1;
+ (id)profileButton;
+ (id)newsButton;
+ (id)cameraButton;
+ (id)exploreButton;
+ (id)homeButton;
@property(retain, nonatomic) UIImageView *markView; // @synthesize markView=_markView;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(retain, nonatomic) UIView *viewForVibrancyEffect; // @synthesize viewForVibrancyEffect=_viewForVibrancyEffect;
@property(nonatomic) BOOL clearsAttentionWhenSelected; // @synthesize clearsAttentionWhenSelected=_clearsAttentionWhenSelected;
@property(nonatomic) BOOL needsAttention; // @synthesize needsAttention=_needsAttention;
- (void).cxx_destruct;
- (void)updateMark;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

