//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UITabBar, UIVisualEffectView;

@interface IGTabBar : UIView
{
    NSMutableArray *_tabButtons;
    UIVisualEffectView *_blurView;
    UIVisualEffectView *_vibrancyView;
    UITabBar *_tabBarForBlurEffect;
}

@property(readonly, nonatomic) UITabBar *tabBarForBlurEffect; // @synthesize tabBarForBlurEffect=_tabBarForBlurEffect;
@property(readonly, nonatomic) UIVisualEffectView *vibrancyView; // @synthesize vibrancyView=_vibrancyView;
@property(readonly, nonatomic) UIVisualEffectView *blurView; // @synthesize blurView=_blurView;
@property(readonly, nonatomic) NSMutableArray *tabButtons; // @synthesize tabButtons=_tabButtons;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)addTabButton:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

