//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIVisualEffectView;

@interface IGTrackBarView : UIView
{
    float _trackValue;
    UIView *_trackView;
    UIView *_trackValueView;
    UIView *_backgroundView;
    UIView *_effectiveContentView;
    UIVisualEffectView *_visualEffectView;
}

@property(readonly, nonatomic) UIVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
@property(readonly, nonatomic) UIView *effectiveContentView; // @synthesize effectiveContentView=_effectiveContentView;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) UIView *trackValueView; // @synthesize trackValueView=_trackValueView;
@property(readonly, nonatomic) UIView *trackView; // @synthesize trackView=_trackView;
@property(nonatomic) float trackValue; // @synthesize trackValue=_trackValue;
- (void).cxx_destruct;
- (BOOL)isVisualEffectEnabled;
- (void)layoutSubviews;
- (void)setTrackValueTintColor:(id)arg1;
- (void)setTrackTintColor:(id)arg1;
- (void)setBackgroundOverlayColor:(id)arg1;
- (void)setBackgroundOverlayAlpha:(float)arg1;
- (void)setBackgroundOverlayVisualEffect:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

