//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIScrollViewDelegate.h"

@class IGUnifiedWebViewToolbar, NSString, UIScrollView;

@interface IGUnifiedWebViewScrollViewToolbarCoordinator : NSObject <UIScrollViewDelegate>
{
    BOOL _navigationToolbarIsTransitioning;
    BOOL _navigationToolbarIsPresented;
    UIScrollView *_scrollView;
    IGUnifiedWebViewToolbar *_navigationToolbar;
}

@property(nonatomic) BOOL navigationToolbarIsPresented; // @synthesize navigationToolbarIsPresented=_navigationToolbarIsPresented;
@property(nonatomic) BOOL navigationToolbarIsTransitioning; // @synthesize navigationToolbarIsTransitioning=_navigationToolbarIsTransitioning;
@property(readonly, nonatomic) __weak IGUnifiedWebViewToolbar *navigationToolbar; // @synthesize navigationToolbar=_navigationToolbar;
@property(readonly, nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)panGestureRecognizerEnded:(id)arg1;
- (void)scrollViewPanGestureRecognized:(id)arg1;
- (void)hideToolbar;
- (void)presentToolbar;
- (id)initWithScrollView:(id)arg1 navigationToolbar:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

