//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUnifiedWebViewControllerSharingLogger.h"

@class IGFeedItem, IGSponsoredFeedItemTracker;

@interface IGUnifiedWebViewControllerStandardSharingLogger : NSObject <IGUnifiedWebViewControllerSharingLogger>
{
    IGFeedItem *_feedItem;
    IGSponsoredFeedItemTracker *_tracker;
}

@property(readonly, nonatomic) IGSponsoredFeedItemTracker *tracker; // @synthesize tracker=_tracker;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
- (void).cxx_destruct;
- (id)concatenatedURLsForItems:(id)arg1;
- (void)webViewController:(id)arg1 forItems:(id)arg2 activityType:(id)arg3 wasCompleted:(BOOL)arg4 returnedItems:(id)arg5 activityError:(id)arg6;
- (void)webViewController:(id)arg1 displayedShareActionsForItems:(id)arg2;
- (id)initWithFeedItem:(id)arg1;

@end

