//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGVideoViewLogging.h"

@class IGPost, NSDictionary, NSNumber, NSString;

@interface IGVideoViewLogger : NSObject <IGVideoViewLogging>
{
    NSNumber *_lastPlaybackTime;
    int _originalPlaybackReason;
    IGPost *_post;
    NSDictionary *_extra;
}

@property(retain, nonatomic) NSDictionary *extra; // @synthesize extra=_extra;
@property(retain, nonatomic) IGPost *post; // @synthesize post=_post;
@property int originalPlaybackReason; // @synthesize originalPlaybackReason=_originalPlaybackReason;
@property(retain) NSNumber *lastPlaybackTime; // @synthesize lastPlaybackTime=_lastPlaybackTime;
- (void).cxx_destruct;
- (id)playbackInfoForPlayer:(id)arg1 withTimingInfo:(BOOL)arg2;
- (void)logVideoDisplayed;
- (void)logVideoShouldStart;
- (void)logVideoError;
- (void)logVideoUnpauseForPlayer:(id)arg1 playbackReason:(int)arg2;
- (void)logVideoStartForPlayer:(id)arg1 playbackReason:(int)arg2 videoStartDelay:(float)arg3;
- (void)logVideoComplete;
- (void)logVideoTapForPlayer:(id)arg1;
- (void)logAudioWillPlay:(BOOL)arg1 player:(id)arg2 reason:(int)arg3;
- (void)logVideoStopForPlayer:(id)arg1 reason:(int)arg2;
- (id)initWithPost:(id)arg1 extraFields:(id)arg2;
- (id)initWithPost:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

