//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGBaseCameraViewController.h"

#import "IGCameraNavigationControllerDelegate.h"
#import "IGClipCollectionControllerDelegate.h"
#import "IGEditorTabBarDelegate.h"
#import "IGFilterCollectionControllerDelegate.h"
#import "IGFilterControlViewDelegate.h"
#import "IGOverlayNuxControllerDelegate.h"
#import "IGShareViewControllerDelegate.h"
#import "IGVideoPlaybackViewDelegate.h"
#import "IGVideoScrubberViewDelegate.h"
#import "IGVideoTrimConfirmationDelegate.h"
#import "IGVideoTrimControllerDelegate.h"

@class IGClipCollectionController, IGEditorTabBar, IGFilterCollectionController, IGFilterControlView, IGMediaMetadata, IGOverlayNuxController, IGSegmentedProgressView, IGVideoComposition, IGVideoInfo, IGVideoPlayButton, IGVideoPlaybackView, IGVideoScrubberView, IGVideoTrimViewController, NSMutableDictionary, NSString, UIBarButtonItem, UICollectionView, UIImageView, UILabel, UIView;

@interface IGVideoEditorViewController : IGBaseCameraViewController <IGFilterCollectionControllerDelegate, IGClipCollectionControllerDelegate, IGVideoPlaybackViewDelegate, IGShareViewControllerDelegate, IGEditorTabBarDelegate, IGVideoScrubberViewDelegate, IGFilterControlViewDelegate, IGOverlayNuxControllerDelegate, IGCameraNavigationControllerDelegate, IGVideoTrimControllerDelegate, IGVideoTrimConfirmationDelegate>
{
    BOOL _needsVideoUpdate;
    BOOL _trimAnimationAlreadyShown;
    BOOL _isClipTrimMode;
    BOOL _didReorderTray;
    BOOL _videoIsReady;
    BOOL _viewLoaded;
    IGVideoInfo *_videoInfo;
    IGVideoComposition *_workingVideoComposition;
    IGVideoPlaybackView *_playerView;
    IGVideoPlayButton *_playButton;
    IGMediaMetadata *_mediaMetadata;
    NSMutableDictionary *_adjustedFilterStrengthValues;
    UIBarButtonItem *_doneButton;
    UIBarButtonItem *_cancelButton;
    UIImageView *_cinemaButton;
    UIImageView *_audioMuteButton;
    UIImageView *_coverFrameButton;
    UIImageView *_trimmerButton;
    UIImageView *_multiClipButton;
    UIImageView *_filtersButton;
    UIView *_audioMuteOverlayView;
    UILabel *_audioMutedLabel;
    UILabel *_audioOnLabel;
    int _audioMuteToggleTick;
    float _originalVideoLength;
    float _maxVideoDuration;
    UIView *_toolsContainerView;
    IGEditorTabBar *_toolsTabBar;
    UIView *_toolView;
    UIView *_rearrangeFilterOverlayView;
    UIView *_rearrangeClipOverlayView;
    UICollectionView *_filterCollectionView;
    IGFilterCollectionController *_filterTrayController;
    IGFilterControlView *_filterControlView;
    IGClipCollectionController *_clipTrayController;
    IGVideoTrimViewController *_videoTrimViewController;
    IGSegmentedProgressView *_trimProgressView;
    IGVideoScrubberView *_scrubberView;
    IGOverlayNuxController *_overlayNuxController;
    IGClipCollectionController *_clipCollectionController;
    int _videoOrigin;
    struct CGSize _videoDisplaySize;
    CDStruct_1b6d18a9 _keyTime;
    CDStruct_e83c9415 _previousTrimmedRange;
}

@property(nonatomic) int videoOrigin; // @synthesize videoOrigin=_videoOrigin;
@property(nonatomic) BOOL viewLoaded; // @synthesize viewLoaded=_viewLoaded;
@property(nonatomic) BOOL videoIsReady; // @synthesize videoIsReady=_videoIsReady;
@property(retain, nonatomic) IGClipCollectionController *clipCollectionController; // @synthesize clipCollectionController=_clipCollectionController;
@property(nonatomic) BOOL didReorderTray; // @synthesize didReorderTray=_didReorderTray;
@property(nonatomic) CDStruct_1b6d18a9 keyTime; // @synthesize keyTime=_keyTime;
@property(nonatomic) BOOL isClipTrimMode; // @synthesize isClipTrimMode=_isClipTrimMode;
@property(nonatomic) BOOL trimAnimationAlreadyShown; // @synthesize trimAnimationAlreadyShown=_trimAnimationAlreadyShown;
@property(nonatomic) BOOL needsVideoUpdate; // @synthesize needsVideoUpdate=_needsVideoUpdate;
@property(retain, nonatomic) IGOverlayNuxController *overlayNuxController; // @synthesize overlayNuxController=_overlayNuxController;
@property(retain, nonatomic) IGVideoScrubberView *scrubberView; // @synthesize scrubberView=_scrubberView;
@property(retain, nonatomic) IGSegmentedProgressView *trimProgressView; // @synthesize trimProgressView=_trimProgressView;
@property(nonatomic) CDStruct_e83c9415 previousTrimmedRange; // @synthesize previousTrimmedRange=_previousTrimmedRange;
@property(retain, nonatomic) IGVideoTrimViewController *videoTrimViewController; // @synthesize videoTrimViewController=_videoTrimViewController;
@property(retain, nonatomic) IGClipCollectionController *clipTrayController; // @synthesize clipTrayController=_clipTrayController;
@property(retain, nonatomic) IGFilterControlView *filterControlView; // @synthesize filterControlView=_filterControlView;
@property(retain, nonatomic) IGFilterCollectionController *filterTrayController; // @synthesize filterTrayController=_filterTrayController;
@property(retain, nonatomic) UICollectionView *filterCollectionView; // @synthesize filterCollectionView=_filterCollectionView;
@property(retain, nonatomic) UIView *rearrangeClipOverlayView; // @synthesize rearrangeClipOverlayView=_rearrangeClipOverlayView;
@property(retain, nonatomic) UIView *rearrangeFilterOverlayView; // @synthesize rearrangeFilterOverlayView=_rearrangeFilterOverlayView;
@property(retain, nonatomic) UIView *toolView; // @synthesize toolView=_toolView;
@property(retain, nonatomic) IGEditorTabBar *toolsTabBar; // @synthesize toolsTabBar=_toolsTabBar;
@property(retain, nonatomic) UIView *toolsContainerView; // @synthesize toolsContainerView=_toolsContainerView;
@property(nonatomic) float maxVideoDuration; // @synthesize maxVideoDuration=_maxVideoDuration;
@property(nonatomic) float originalVideoLength; // @synthesize originalVideoLength=_originalVideoLength;
@property(nonatomic) int audioMuteToggleTick; // @synthesize audioMuteToggleTick=_audioMuteToggleTick;
@property(retain, nonatomic) UILabel *audioOnLabel; // @synthesize audioOnLabel=_audioOnLabel;
@property(retain, nonatomic) UILabel *audioMutedLabel; // @synthesize audioMutedLabel=_audioMutedLabel;
@property(retain, nonatomic) UIView *audioMuteOverlayView; // @synthesize audioMuteOverlayView=_audioMuteOverlayView;
@property(retain, nonatomic) UIImageView *filtersButton; // @synthesize filtersButton=_filtersButton;
@property(retain, nonatomic) UIImageView *multiClipButton; // @synthesize multiClipButton=_multiClipButton;
@property(retain, nonatomic) UIImageView *trimmerButton; // @synthesize trimmerButton=_trimmerButton;
@property(retain, nonatomic) UIImageView *coverFrameButton; // @synthesize coverFrameButton=_coverFrameButton;
@property(retain, nonatomic) UIImageView *audioMuteButton; // @synthesize audioMuteButton=_audioMuteButton;
@property(retain, nonatomic) UIImageView *cinemaButton; // @synthesize cinemaButton=_cinemaButton;
@property(retain, nonatomic) UIBarButtonItem *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIBarButtonItem *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) NSMutableDictionary *adjustedFilterStrengthValues; // @synthesize adjustedFilterStrengthValues=_adjustedFilterStrengthValues;
@property(retain, nonatomic) IGMediaMetadata *mediaMetadata; // @synthesize mediaMetadata=_mediaMetadata;
@property(retain, nonatomic) IGVideoPlayButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) IGVideoPlaybackView *playerView; // @synthesize playerView=_playerView;
@property(retain, nonatomic) IGVideoComposition *workingVideoComposition; // @synthesize workingVideoComposition=_workingVideoComposition;
@property(retain, nonatomic) IGVideoInfo *videoInfo; // @synthesize videoInfo=_videoInfo;
@property(nonatomic) struct CGSize videoDisplaySize; // @synthesize videoDisplaySize=_videoDisplaySize;
- (void).cxx_destruct;
- (id)analyticsModule;
- (void)showInvalidVideoError;
- (void)updateVideoDependentViews;
- (void)videoInfoReady:(id)arg1;
- (void)updateVideoDisplaySize;
- (BOOL)isValidVideo:(id)arg1;
- (void)cancelRenderAndUpload;
- (void)videoTrimControllerDidRejectChanges:(id)arg1;
- (void)videoTrimController:(id)arg1 didConfirmTrimmedRange:(CDStruct_e83c9415)arg2;
- (void)videoTrimController:(id)arg1 didFinishUpdatingWithTrimmedRange:(CDStruct_e83c9415)arg2;
- (void)videoTrimController:(id)arg1 didUpdateWithTrimmedRange:(CDStruct_e83c9415)arg2;
- (void)videoTrimController:(id)arg1 willBeginUpdatingWithTrimmedRange:(CDStruct_e83c9415)arg2;
- (id)cacheKeyForClip:(id)arg1 filter:(id)arg2 time:(CDStruct_1b6d18a9)arg3;
- (id)cachedThumbnailForClip:(id)arg1 andTime:(CDStruct_1b6d18a9)arg2;
- (void)cacheThumbnail:(id)arg1 forClip:(id)arg2 andTime:(CDStruct_1b6d18a9)arg3;
- (void)populateThumbnailCacheForClipIndex:(unsigned int)arg1;
- (void)generateScrubberFrames;
- (void)scrubberViewDidTapOnHandle;
- (void)scrubberViewFinishedMovingHandle;
- (void)scrubberViewBeganMovingHandle;
- (void)scrubberViewDidMoveHandleToPosition:(float)arg1;
- (float)trimViewTimeScaleForClipDuration:(float)arg1;
- (void)showVideoTrimmer;
- (void)showCoverFramePicker;
- (void)showClips;
- (void)showFilters;
- (void)reconcileVideoPlayer;
- (void)cameraControllerDidFinishWithVideoComposition:(id)arg1;
- (void)cameraControllerDidFinishWithDirectShare:(BOOL)arg1;
- (void)cameraControllerDidFinishWithPhoto:(id)arg1 fromOrigin:(int)arg2;
- (void)cameraControllerDidCancel;
- (void)exitTrimControlView;
- (void)filterControlView:(id)arg1 didChangetintIntensity:(float)arg2 tintType:(unsigned int)arg3;
- (void)filterControlView:(id)arg1 didChangeTintColor:(unsigned int)arg2 withTintType:(unsigned int)arg3;
- (void)filterControlViewNeedUpdateValue;
- (void)filterControlViewDidToggleGrid:(BOOL)arg1;
- (void)filterControlViewDidTapRotate:(id)arg1;
- (void)filterControlView:(id)arg1 didChangeBorderSelection:(BOOL)arg2;
- (void)filterControlView:(id)arg1 didChangeValue:(float)arg2;
- (void)filterControlViewDidEndDragging:(id)arg1;
- (void)filterControlViewDidStartDragging:(id)arg1;
- (void)filterControlViewDidPressCancel:(id)arg1;
- (void)filterControlViewDidPressDone:(id)arg1;
- (void)onToolCancel:(id)arg1;
- (void)onToolDone:(id)arg1;
- (void)dismissFilterControlView:(id)arg1;
- (void)presentFilterControlView:(id)arg1 withTitle:(id)arg2 subtitle:(id)arg3 leftBarButtonItem:(id)arg4 rightBarButtonItem:(id)arg5 andCompletion:(CDUnknownBlockType)arg6;
- (void)presentFilterControlView:(id)arg1 withTitle:(id)arg2 subtitle:(id)arg3 andCompletion:(CDUnknownBlockType)arg4;
- (id)titleForItem:(id)arg1;
- (void)tabBar:(id)arg1 didSelectTabView:(id)arg2 previousTabView:(id)arg3;
- (BOOL)tabBar:(id)arg1 shouldSelectTabView:(id)arg2;
- (void)showTrimAnimation;
- (void)addScissorsAnimationToImageView:(id)arg1 tintColor:(id)arg2;
- (id)trimmerAnimationImagesWithTintColor:(id)arg1;
- (void)overlayNuxControllerWillDismiss;
- (void)shareViewControllerWillFinish:(id)arg1;
- (void)shareViewControllerDidCancel:(id)arg1;
- (void)shareViewControllerDidAppear:(id)arg1;
- (void)toggleStabilization;
- (BOOL)stabilizationEnabled;
- (void)toggleAudioMuting;
- (BOOL)isAudioMutingEnabled;
- (void)setNavigationItemTitle:(id)arg1 subtitle:(id)arg2;
- (id)createTitleView:(id)arg1 withSubtitle:(id)arg2;
- (id)draggingContainerViewForClipController:(id)arg1;
- (void)updateTrimProgressSegmentColors;
- (void)didTapClipAtIndexPath:(id)arg1;
- (void)clipControllerDidFinishReordering:(id)arg1;
- (void)clipController:(id)arg1 didChangeClipOrder:(id)arg2;
- (void)clipControllerDidStartReordering:(id)arg1;
- (void)filterControllerDidFinishReordering:(id)arg1;
- (void)filterControllerDidStartReordering:(id)arg1;
- (float)filterController:(id)arg1 filterStrengthForClass:(Class)arg2;
- (void)filterController:(id)arg1 didSelectFilterStrengthForClass:(Class)arg2;
- (void)filterController:(id)arg1 didSelectFilterWithClass:(Class)arg2 changed:(BOOL)arg3 willScroll:(BOOL)arg4;
- (void)playbackView:(id)arg1 didPlayToTime:(CDStruct_1b6d18a9)arg2;
- (void)filterPlayerViewDidFinishPlayingWithAnimation:(BOOL)arg1;
- (void)filterPlayerViewDidFinishPlaying;
- (id)sendAnalyticsEvent:(id)arg1;
- (void)startVideoRender;
- (void)done;
- (BOOL)shouldShowDismissPrompt;
- (void)didTapCancel:(id)arg1;
- (void)cancel;
- (void)togglePlayback;
- (void)onVideoTapped;
- (void)filterControllerDidSelectAddMoreFilters:(id)arg1;
- (id)accessibilityHintForView:(id)arg1;
- (id)accessibilityLabelForView:(id)arg1;
- (void)configureAccessibilityForTabBar:(id)arg1;
- (void)updateModeTabBarButtons;
- (void)buildToolsTabBar;
- (struct CGSize)toolsTabBarSizeForToolsContainerSize:(struct CGSize)arg1;
- (void)buildToolContainerView;
- (void)buildNavbar;
- (void)updateWithVideoComposition:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppearInner:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)applicationWillResignActive:(id)arg1;
- (BOOL)overlayIsOpaque;
- (void)trimClips;
- (id)initWithAssetInMediaMetadata:(id)arg1;
- (id)initWithOrigin:(int)arg1 videoInfo:(id)arg2 mediaMetadata:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

