//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGServiceHelperProtocol.h"
#import "IGWeiboAuthDelegate.h"

@class IGNonCurrentUserDefaults, NSString;

@interface IGWeiboHelper : NSObject <IGWeiboAuthDelegate, IGServiceHelperProtocol>
{
    NSString *_accessToken;
    NSString *_refreshToken;
    IGNonCurrentUserDefaults *_sessionUserDefaults;
}

+ (id)serviceNameForTokenStore;
+ (id)serviceName;
+ (void)logoutFromDefaults:(id)arg1;
+ (void)clearForUserPK:(id)arg1;
+ (id)shortServiceName;
+ (id)sharedHelper;
@property(retain, nonatomic) IGNonCurrentUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
@property(copy, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (void).cxx_destruct;
- (void)weiboAuthControllerLoginFailed:(id)arg1;
- (void)weiboAuthController:(id)arg1 didLoginWithAccessToken:(id)arg2 andRefreshToken:(id)arg3;
- (void)saveAccessToken:(id)arg1 andRefreshToken:(id)arg2;
- (void)saveNewRefreshToken:(id)arg1;
- (void)saveNewAccessToken:(id)arg1;
- (int)tokenLife;
- (void)reauthorize;
- (BOOL)hasEverBeenConfigured;
- (id)sharingInfo;
- (BOOL)requiresLocationCoordinate;
- (BOOL)supportsMediaType:(int)arg1;
- (BOOL)isAvailableInCurrentLocale;
- (void)reauthorizeIfNeeded;
- (BOOL)needsToReauthorize;
- (BOOL)isConfigurable;
- (BOOL)hasAdvancedOptions;
- (BOOL)isConfigured;
- (void)logout;
- (void)logoutAndUnlink;
- (id)viewControllerForAdvancedOptions;
@property(readonly, nonatomic) BOOL accessTokenExpired;
- (id)authURLString;
- (id)callbackURLString;
- (id)clientID;
- (id)initWithSessionUserDefaults:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

