//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSIndexSet, NSString, RCTRefreshControl, UIView;

@interface RCTCustomScrollView : UIScrollView <UIGestureRecognizerDelegate>
{
    UIView *_dockedHeaderView;
    BOOL _centerContent;
    NSIndexSet *_stickyHeaderIndices;
    RCTRefreshControl *_refreshControl;
}

@property(retain, nonatomic) RCTRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(nonatomic) BOOL centerContent; // @synthesize centerContent=_centerContent;
@property(copy, nonatomic) NSIndexSet *stickyHeaderIndices; // @synthesize stickyHeaderIndices=_stickyHeaderIndices;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dockClosestSectionHeader;
- (void)setContentOffset:(struct CGPoint)arg1;
- (BOOL)touchesShouldCancelInContentView:(id)arg1;
- (void)scrollRectToVisible:(struct CGRect)arg1 animated:(BOOL)arg2;
- (void)handleCustomPan:(id)arg1;
- (BOOL)_shouldDisableScrollInteraction;
- (id)contentView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

