//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTShadowView.h"

#import "RCTImageComponent.h"

@class NSString, RCTBridge, RCTImageSource, UIImage;

@interface RCTShadowVirtualImage : RCTShadowView <RCTImageComponent>
{
    RCTBridge *_bridge;
    CDUnknownBlockType _cancellationBlock;
    UIImage *_image;
    RCTImageSource *_source;
    int _resizeMode;
}

@property(nonatomic) int resizeMode; // @synthesize resizeMode=_resizeMode;
@property(retain, nonatomic) RCTImageSource *source; // @synthesize source=_source;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didSetProps:(id)arg1;
- (id)init;
- (id)initWithBridge:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

