//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@interface RCTUITextView : UITextView
{
    BOOL _jsRequestingFirstResponder;
    BOOL _textWasPasted;
}

@property(nonatomic) BOOL textWasPasted; // @synthesize textWasPasted=_textWasPasted;
- (void)reactDidMakeFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)reactWillMakeFirstResponder;
- (void)paste:(id)arg1;

@end

