//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSObject<ToolControllerDelegate>, NSString, ToolControllerConfig, UICollectionView;

@interface ToolController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
    NSArray *_tools;
    ToolControllerConfig *_config;
    NSObject<ToolControllerDelegate> *_delegate;
    UICollectionView *_collectionView;
    int _currentToolIndex;
}

@property(nonatomic) int currentToolIndex; // @synthesize currentToolIndex=_currentToolIndex;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak NSObject<ToolControllerDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) ToolControllerConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) NSArray *tools; // @synthesize tools=_tools;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)toolCellWithToolTile:(id)arg1;
- (void)updateState;
- (float)height;
- (void)_updateLayout;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

