//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@interface UICollectionView (Instagram)
- (id)ig_visibleCellsIntersectingCollectionViewBounds;
- (id)visibleCellsConformingToProtocol:(id)arg1;
- (id)visibleCellsOfClass:(Class)arg1;
- (unsigned int)mostVisibleSection;
- (void)enumerateVisibleViewsWithClass:(Class)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateVisibleCellsWithClass:(Class)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateViews:(id)arg1 class:(Class)arg2 block:(CDUnknownBlockType)arg3;
@end

