//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@interface UINavigationController (Instagram)
- (void)pushCommentsViewControllerForFeedItem:(id)arg1 loggingDelegate:(id)arg2 animated:(BOOL)arg3 keyboardShowing:(BOOL)arg4 replyText:(id)arg5;
- (void)pushCommentsViewControllerForFeedItem:(id)arg1 loggingDelegate:(id)arg2 animated:(BOOL)arg3 keyboardShowing:(BOOL)arg4;
- (void)pushLikesViewControllerForFeedItemPK:(id)arg1 animated:(BOOL)arg2;
- (void)pushPhotomapViewControllerForUser:(id)arg1 animated:(BOOL)arg2 inReviewMode:(BOOL)arg3;
- (void)pushLocationViewControllerForLocation:(id)arg1 animated:(BOOL)arg2;
- (void)pushHashtagViewControllerForHashtag:(id)arg1 animated:(BOOL)arg2;
- (void)pushUserViewControllerForUser:(id)arg1 ctaPresenterContext:(id)arg2 animated:(BOOL)arg3;
- (void)pushUserViewControllerForUser:(id)arg1 animated:(BOOL)arg2;
@end

